### ISSUE TITLE
VkAudioUrlDecodeError

### ISSUE THREAD

**Issue by withoutnameuser** [python273/vk_api#101]
i get this error:

` File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\audio_url_decoder.py", line 44, in decode_audio_url
    'Unknown decode cmd: "{}"; Please send bugreport'.format(cmd)
vk_api.exceptions.VkAudioUrlDecodeError: Unknown decode cmd: "i"; Please send bugreport`

**Comment by vanyasem** [comment]
Походу опять гайки закрутили, сменили алгоритм декодинга

**Comment by vanyasem** [comment]
Печаль, тоска...

**Comment by vanyasem** [comment]
`https://m.vk.com/mp3/audio_api_unavailable.mp3?extra=mMj1zMeUoc1mDM82Auu5DJKVp1KTqwjmy3nSnduOvZvOugG6zs9LCtLkCY9Ov1jHnNvbmJfiudvpwI9fu3rNttfelOrrvwrfu2OOEdD2Cdy1rNaYoefystnRoh0OCZfZA2fsEw1LzvbkCJqOBOi4tMHNELbWqKn4mxPVrLHLqxnktNjtrgf3AJjkBdbyzNPNn3uZwuj1lLLynNHOnZDJywKXn1LpqJzWCwzPswvdCgWUyM9or3PNpxLQtJHKzuO1zfn1AfbJlOzktZfxBKrJrhq4ogC1C1jXmMm#AqSOmZu` new extra format for audios

**Comment by vanyasem** [comment]
No wonder it fails to decode that

**Comment by vanyasem** [comment]
https://github.com/vodka2/vkaudio код дешифратора обновлён, через пару часов пульну ПР

**Comment by withoutnameuser** [comment]
THX
Give that man a beer :)

**Comment by vanyasem** [comment]
he only drinks vodka. read his name carefully @withoutnameuser

**Comment by python273** [comment]
Жду PR ¯\\\_(ツ)_/¯

**Comment by HaCk3Dq** [comment]
Все ждём ;)

**Comment by vanyasem** [comment]
Первый раз за неделю поспал нормально, сразу очередь недовольных выстроилась )

Мама говорила, надо было на экономиста идти

**Comment by python273** [comment]
Пофикшено @vanyasem 👍

**Comment by HaCk3Dq** [comment]
@vanyasem 
> недовольных 
скорее ожидающих)

спасиб
