### ISSUE TITLE
AUR пакеты

### ISSUE THREAD

**Issue by vanyasem** [python273/vk_api#107]
Запаковал пакеты в AUR _(Arch User Repository)_. С их помощью модуль можно поставить на Arch Linux в 1 команду, появляется возможность указывать модуль в завимостях других пакетов.

**Релизная версия:**
Python2: https://aur.archlinux.org/packages/python2-vk_api
Python3: https://aur.archlinux.org/packages/python-vk_api

**Git-версия:**
Python2: https://aur.archlinux.org/packages/python2-vk_api-git
Python3: https://aur.archlinux.org/packages/python-vk_api-git

Установка: `pacaur -S python-vk_api`. pacaur - самый популярный хелпер AUR для Arch, пользователи знают, если они пользуются чем-то другим по N-ной причине и сами поймут, о чём речь.

Было бы классно, если бы это появилось в README.

**Comment by python273** [comment]
имхо не особо нужно, потому что:
1. И так можно ставить из PyPI
2. Модуль не бинарный, смысла в сборке нет

**Comment by vanyasem** [comment]
Это может быть не очевидно, но вот у меня есть модуль, который зависит от этого, и добавить его в AUR без присутствия там vk_api нельзя. Она зависит от него. Сделать то я их уже сделать, добавлять в readme или нет - дело уже не моё

**Comment by vanyasem** [comment]
К слову, бинарные модули вообще запрещены в AUR, с редкими исключениями, например, если ПО проприетарное.

**Comment by python273** [comment]
В общем думаю не очень нужно в ридми ¯\\\_(ツ)_/¯

Скрипты можно в PyPI заливать вообще
