### ISSUE TITLE
wall.post без логина/пароля

### ISSUE THREAD

**Issue by saber-nyan** [python273/vk_api#109]
Вопрос, на самом деле, больше по самому API, но в ВК мне ответят минимум дня через четыре.
Да и я пользуюсь Вашей обвязкой.

**Можно ли постить на стену моего сообщества, имея только `access_token`, как на скриншоте?**

![image](https://user-images.githubusercontent.com/25345196/35199802-68a9cabc-ff14-11e7-8f5f-563394f5aeea.png)

И если нет, то дайте пинок: как это сделать наиболее удобно для пользователя (автообновление токена, идеально — просто один аргумент, приложение консольное)?
<br/>

_%%В этом API черт ногу сломит...%%_

**Comment by python273** [comment]
https://vk.com/dev/methods там рядом с методами значки. У wall.post нету, значит нельзя

**Comment by saber-nyan** [comment]
Эх, грустно. `vk_api` умеет генерировать ссылки для Implicit flow?

**Comment by python273** [comment]
Нет, можно напрямую через VkApi.auth

**Comment by saber-nyan** [comment]
Понял, спасибо.
