### ISSUE TITLE
LongPoll

### ISSUE THREAD

**Issue by crinny** [python273/vk_api#114]
Обрабатываю апдейты в LongPoll, вот мой код:

```
api = session.get_api()
longpoll = VkLongPoll(session, mode=32)

for event in longpoll.listen():
    api.messages.send(user_id=event.user_id, message=event.text)
```

Первое сообщение ловит и отвечает отлично, на втором падает и выдаёт следующую ошибку:

```
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: message is empty or invalid
```

**Comment by python273** [comment]
в longpoll разные евенты, нужно фильтровать как тут например: https://github.com/python273/vk_api/blob/master/examples/messages_bot/messages_bot.py#L37
