### ISSUE TITLE
vk_api.exceptions.ApiError: [15] Access denied: can't set typing activity for this peer

### ISSUE THREAD

**Issue by konstantin42127** [python273/vk_api#116]
мой код:
vk.messages.setActivity(peer_id=event.chat_id,type='typing')
ошибка:
vk_api.exceptions.ApiError: [15] Access denied: can't set typing activity for this peer

**Comment by python273** [comment]
https://vk.com/dev/messages.setActivity
> For chat:
> 2000000000 + chat_id
