### ISSUE TITLE
tools, messages.getHistory offset control

### ISSUE THREAD

**Issue by xkord** [python273/vk_api#122]
offset - смещение, необходимое для выборки определенного подмножества сообщений, должен быть >= 0, если не передан параметр start_message_id, и должен быть <= 0, если передан.

При передаче параметра start_message_id в метод tools.get_all  хотелось бы пофиксить offset.

Сейчас tools.get_all('messages.getHistory', 200, {'user_id': user_id, 'start_message_id': latest_id}) возвращает историю сообщений до latest_id. А по логике должно быть наоборот. Начиная от latest_id и выше...

**Comment by python273** [comment]
Наверное можно использовать параметр rev: 1 – возвращать сообщения в хронологическом порядке. 0 – возвращать сообщения в обратном хронологическом порядке (по умолчанию).

**Comment by xkord** [comment]
К сожалению не помогло.

**Comment by python273** [comment]
Это из-за: `One of the parameters specified was missing or invalid: rev param can not be used with start_message_id` 🤔

**Comment by python273** [comment]
Если предполагается загрузка с конца (от новых сообщений к старым) до какого-то id, то можно использовать stop_fn

**Comment by xkord** [comment]
Да, про stop_fn помню, сам же его и добавлял. Только в моем случае не удобно писать лямбду которая должна будет выкачать часть сообщений, а потом еще и отбросить то, что уже было ранее. Хотелось бы отсекать item-ы проще. Думаю в моем случае самый оптимальный вариант сделать через https://vk.com/dev/messages.getLongPollHistory с указанием max_msg_id. Ну либо предложить pull request с учетом параметра start_message_id :)
