### ISSUE TITLE
Получение файла видеозаписи

### ISSUE THREAD

**Issue by movis08** [python273/vk_api#127]
```
videos = vk_session_api.video.get(owner_id=user_id, album_id=album["id"], count=10)
            while videos["items"]:
                for video in videos["items"]:
                    video_number += 1
                    video_print = " видео " + str(video_number) + " из " + str(videos["count"])
                    print(album_print + video_print)
                    # Сохраняем видео в папку с названием как у альбома
                    video_path = album_path + "\\" + str(video["date"]) + ".mp4"
                    # Если файла не существует (не загружали ранее), то сохраняем его
                    if not os.path.exists(video_path):
                        # Определение максимального разрешения видео
                        video_keys = video["files"].keys()
```

video - объект видеозаписи. Если верить документации VK, то там есть поле files которое является массивом и содержит прямые ссылки на видеофайлы различного разрешения.
Но у вас этого поля нет.

https://vk.com/dev/video.get
https://cdn1.savepice.ru/uploads/2018/4/9/0e7c75ed9a4a3370cbf72e5007a66cc1-full.png

**Comment by python273** [comment]
> Если в Вашем приложении используется прямая авторизация, возвращается дополнительное поле files, содержащее ссылку на файл с видео

В vk_api не используется прямая авторизация, поэтому ссылок нет
