### ISSUE TITLE
Future method

### ISSUE THREAD

**Issue by aaamoymozg** [python273/vk_api#130]
self.opened_files.clear() в upload.py отдает AttributeError: 'list' object has no attribute 'clear', так как этот метод появился только в Python 3.3

https://stackoverflow.com/questions/39944586/clear-for-list-not-working-python/39944686
https://github.com/python273/vk_api/commit/91210470a347b7f7e6b92c75007e6e44b6d722ef#diff-6fba27a0ce26e72a2e920c76f2d3b406

**Comment by hdk5** [comment]
Действительно, моя ошибка.
@python273 
Исправь на 
```self.opened_files *= 0```
пжлст

**Comment by python273** [comment]
@hdk5 а какой-то смысл есть не перезаписывать `[]`, а очищать? `self.opened_files *= 0` выглядит слишком магично для списка
