### ISSUE TITLE
Ошибка при vk.auth()

### ISSUE THREAD

**Issue by Helow19274** [python273/vk_api#137]
Возникает абсолютно рандомно, иногда может 10 раз подряд зайти нормально, а иногда первый раз за сутки с таким багом. Но всё равно заходит если попробовать ещё раз.
![default](https://user-images.githubusercontent.com/20171143/39703779-f7f7c7dc-5211-11e8-93d4-4ba56843871a.png)

**Comment by python273** [comment]
```
json.dump(self._settings, f, indent=2, sort_keys=True)
```
там сохранение с сортировкой идет, поэтому ломается когда в ключах строки и числа

Можешь перед этой строкой добавить печать `self._settings` и посмотреть где ключи смешанных типов?

**Comment by Helow19274** [comment]
Я возможно ошибаюсь, но мне кажется, что такая фигня появляется намного чаще, если vk_config.v2.json уже был создан(но звучит бредово, ибо питон его открывает для перезаписи)

**Comment by python273** [comment]
`НОМЕР БЕЗ КАВЫЧЕК!!!!!!!!!!(он int):{`

Это номер телефона? Может ты его как int передаешь?

**Comment by Helow19274** [comment]
Получается я во всём виноват? Да, я номер телефона как int передаю
