### ISSUE TITLE
Как изменить встроеное приложение на свое

### ISSUE THREAD

**Issue by VadVergasov** [python273/vk_api#138]
Когда пытаю сделать это т.е. вставляю свой app_id выдает, что неверная redicret_uri (Сделал сам изменив код библиотеки, добавив дамп response). Можно инструкцию как настроить свое приложение для этого всего?

**Comment by python273** [comment]
А id от Standalone приложения?

**Comment by VadVergasov** [comment]
Было сделано приложение Веб-Сайт. Сделал Standalone помогло. Спасибо большое! Моя невнимательность!
