### ISSUE TITLE
Ошибка "You don't have permissions to browse user's audio"

### ISSUE THREAD

**Issue by valeev98** [python273/vk_api#142]
При передачи для прочтения аудио в vk_api.VkApi() логина и пароля, то доступ к аудио есть, но если передать в vk_api.VkApi() токен(в токен передал все scope, что были) и app_id то выходит ошибка "You don't have permissions to browse user's audio"
`
tok = 'my_token'
vk_session = vk_api.VkApi(token=tok,app_id=6240100)
    vkaudio = VkAudio(vk_session)

    artists = collections.Counter()

    offset = 0
    urls = []
    while True:
        audios = vkaudio.get(owner_id=454520432, offset=offset)

        if not audios:
            break`

**Comment by python273** [comment]
VkAudo парсит мобильную версию сайта, так что без кук оно не работает
