### ISSUE TITLE
поиск аудиозаписей

### ISSUE THREAD

**Issue by re1ard** [python273/vk_api#149]
https://github.com/python273/vk_api/blob/a9e425cafa552cc8d528987c5adf5e8d106a304b/vk_api/audio.py#L201

там контакт опять сломал аудиозаписи,а именно (что я заметил только) глобальный поиск поломали

![prf2](https://user-images.githubusercontent.com/20165536/42544562-2e592e5c-84a2-11e8-9b70-a3bdb611e8cf.PNG)
![prf1](https://user-images.githubusercontent.com/20165536/42544563-2e75780a-84a2-11e8-8686-3ced56a4ef47.PNG)

**Comment by python273** [comment]
https://m.vk.com/audio?act=search&q=seas+of+years

похоже оно на стороне ВК сломано

**Comment by re1ard** [comment]
![prf4](https://user-images.githubusercontent.com/20165536/42585983-873b6ac4-8526-11e8-9c02-3c507b43b30c.PNG)
![prf3](https://user-images.githubusercontent.com/20165536/42585985-875d0102-8526-11e8-8d70-f9d74cd7b243.PNG)

я вот что заметил после накатки прокси,что трафик "понюхать", что терь немного по другому он запрашивает страницу, собственная вместо (audio?act=search&q=gachibass) надо теперь переделать под (audio?_ajax=1&q=gachibass)
