### ISSUE TITLE
Добавить README.md для examples

### ISSUE THREAD

**Issue by python273** [python273/vk_api#150]
Можно короткое описание сделать для каждого файла

**Comment by skar404** [comment]
Может еще документацию начать писать? 
Иногда очень не хватает удобной доки для данной lib 

Как вариант использовать:
- http://www.sphinx-doc.org/en/master/
- https://readthedocs.org/

Могу этим заняться если интересно.

**Comment by python273** [comment]
В доке ссылка на папку с примерами, так что думаю лучше README.md добавить
