### ISSUE TITLE
vk_api ломает автодополнение spyder3

### ISSUE THREAD

**Issue by Ungaminga** [python273/vk_api#151]
https://github.com/spyder-ide/spyder/issues/5782 Есть такая иссуя, судя по всему - не обязательно использовать библиотеку enum34. Если есть возможность - уберите её из требований.
Заранее спасибо.

**Comment by python273** [comment]
enum34 нужна для python2

**Comment by python273** [comment]
скорее всего достаточно будет использовать отдельный virtualenv для spyder и проекта
