### ISSUE TITLE
User Long Poll: добавить 52 событие 

### ISSUE THREAD

**Issue by python273** [python273/vk_api#158]
https://vk.com/dev/using_longpoll
> 52 | $type_id (integer) $peer_id (integer) $info(integer) | Изменение информации чата $peer_id с типом $type_id,  $info  — дополнительная информация об изменениях, зависит от типа события. См. 3.2 Дополнительные поля чатов

Нужно парсить дополнительные поля: (enum)
https://vk.com/dev/using_longpoll_2?f=3.1.%20%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9

**Comment by deker104** [comment]
Окей, сегодня сделаю
