### ISSUE TITLE
Unknown API auth error при авторизации через своё приложение

### ISSUE THREAD

**Issue by roland-x** [python273/vk_api#164]
Добрый день, сделал авторизацию через свое приложение

    def auth(self):
        # если токен есть в базе авторизируемся по токену
            self.vk_session = vk_api.VkApi(self._login, self._password, captcha_handler=self._captcha_handler,
            app_id=2274003, client_secret="hHbZxrka2uZ6jB1inYsH")

Как только задаю app_id и client_secret вываливается ошибка Unknown API auth error

Как в вашей библиотеке правильно авторизироваться через свое приложение

**Comment by python273** [comment]
возможно приложение не standalone

**Comment by roland-x** [comment]
[Android] 
clientID = 2274003 
clientSecret = "hHbZxrka2uZ6jB1inYsH"

**Comment by python273** [comment]
#134

Прямая авторизация не сделана. Параметр `client_secret` используется для серверной аутентификации

**Comment by roland-x** [comment]
просто я уже авторизировался подобным образом через обычные запросы

``        params = {
            'client_id': '3140623',
            # 'client_id': '3682744',
            'scope': 'wall,groups,messages',
            'client_secret': 'VeWdmVclDCtn6ihuP1nt',
            'username': str(self.__login),
            'password': str(self.__password),
            'captcha_sid': '',
            'captcha_key': ''
        }
response=utilities.safety_request('https://oauth.vk.com/token?grant_type=password',params).json()

**Comment by Helow19274** [comment]
Только если приложение прошло проверку у службы поддержки
> Для подачи заявки на получение доступа Вам необходимо обратиться в службу поддержки по адресу https://vk.com/support, указав ID Вашего приложения.

Иначе:
```json
{
    "error": "invalid_request",
    "error_description": "This grant_type available only for approved applications"
}
```
