### ISSUE TITLE
Прблемы с BotLongpoll

### ISSUE THREAD

**Issue by Dev-TorTikProd** [python273/vk_api#172]
Не очень понял по документации использование BotLongpoll
Сделайте пожалуйста наглядный пример чтения сообщений

Если с обычным лонгпулом работает нечто такое
for event in longpoll.listen():
	if event.type == VkEventType.MESSAGE_NEW:

То при получении сообщения через BotLongpool я получаю ошибку 
 if self.obj.peer_id < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

использовал код:
for event in botlongpoll.listen():
		print(event)
		if event.type == VkBotMessageEvent.from_user:
			print('a')

 спасибо

**Comment by Akakiidvachevskiy** [comment]
поле peer_id появилось в api версии 5.80. в настройках сообщества выбериверсию 5.80+
