### ISSUE TITLE
Vk Bot Api Bug

### ISSUE THREAD

**Issue by DevRedOWL** [python273/vk_api#174]
Ошибка в BotLongpoll появляется даже при выполнении кода, приведенного в примере

> Печатает 85514032 для -170800454
> 
> Traceback (most recent call last):
>   File "C:\Users\User\Desktop\hsehelper\vkbot.py", line 67, in <module>
>     main()
>   File "C:\Users\User\Desktop\hsehelper\vkbot.py", line 17, in main
>     for event in longpoll.listen():
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\bot_longpoll.py", line 271, in listen
>     for event in self.check():
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\bot_longpoll.py", line 251, in check
>     for raw_event in response['updates']
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\bot_longpoll.py", line 251, in <listcomp>
>     for raw_event in response['updates']
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\bot_longpoll.py", line 212, in _parse_event
>     return event_class(raw_event)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\bot_longpoll.py", line 158, in __init__
>     if self.obj.peer_id < 0:
> TypeError: '<' not supported between instances of 'NoneType' and 'int'

````
# -*- coding: utf-8 -*-
import vk_api
import options as o
from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType


def main():
    """ Пример использования bots longpoll

        https://vk.com/dev/bots_longpoll
    """

    vk_session = vk_api.VkApi(логин, пароль)
    vk_session.auth()
    longpoll = VkBotLongPoll(vk_session, идгруппы)

    for event in longpoll.listen():

        if event.type == VkBotEventType.MESSAGE_NEW:
            print('Новое сообщение:')

            print('Для меня от: ', end='')

            print(event.obj.from_id)

            print('Текст:', event.obj.text)
            print()

        elif event.type == VkBotEventType.MESSAGE_REPLY:
            print('Новое сообщение:')

            print('От меня для: ', end='')

            print(event.obj.peer_id)

            print('Текст:', event.obj.text)
            print()

        elif event.type == VkBotEventType.MESSAGE_TYPING_STATE:
            print('Печатает ', end='')

            print(event.obj.from_id, end=' ')

            print('для ', end='')

            print(event.obj.to_id)
            print()

        elif event.type == VkBotEventType.GROUP_JOIN:
            print(event.obj.user_id, end=' ')

            print('Вступил в группу!')
            print()

        elif event.type == VkBotEventType.GROUP_LEAVE:
            print(event.obj.user_id, end=' ')

            print('Покинул группу!')
            print()

        else:
            print(event.type)
            print()


if __name__ == '__main__':
    main()
```

**Comment by Helow19274** [comment]
![default](https://user-images.githubusercontent.com/20171143/45028189-bb3adc00-b04c-11e8-83a5-8119967be2a6.png)

**Comment by python273** [comment]
https://github.com/python273/vk_api/blob/master/vk_api/bot_longpoll.py#L160

нужно посмотреть почему тут у объекта может не быть peer_id

**Comment by Dev-TorTikProd** [comment]
> python273 commented 41 minutes ago
> https://github.com/python273/vk_api/blob/master/vk_api/bot_longpoll.py#L160
> нужно посмотреть почему тут у объекта может не быть peer_id

Не очень понял, что мне нужно сделать, чтобы код заработал. И могул ли как то влиять настройки у самой группы?

**Comment by python273** [comment]
Падает при получении сообщения? Можешь запустить и скинуть вывод после чего обычно падает?

```python
# -*- coding: utf-8 -*-
import vk_api
from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType


class VkBotLongPollRaw(VkBotLongPoll):
    CLASS_BY_EVENT_TYPE = {}


def main():
    vk_session = vk_api.VkApi(логин, пароль)
    vk_session.auth()
    longpoll = VkBotLongPollRaw(vk_session, идгруппы)

    for event in longpoll.listen():
        print(event.raw)


if __name__ == '__main__':
    main()

```

**Comment by python273** [comment]
Возможно в этом дело: `vk_session = vk_api.VkApi(логин, пароль)`, для бота нужно токен группы передавать, а не логин с паролем

**Comment by Dev-TorTikProd** [comment]
> python273

Ближе к вечеру попробую запустить и скину результаты.
 
Если передавать надо токен группы, то где мне его взять? Это те, которые ключи доступа и создаются через настройки? Ибо ы разделе лонгпула в вк не создается ключ.

**Comment by python273** [comment]
> Это те, которые ключи доступа и создаются через настройки?

Да

> Без разницы. Если пользователь админ в группе group_id, то работает и от имени пользователя

Хмм, может там есть какие-то особенности для юзеров 🤔

**Comment by Helow19274** [comment]
@python273 я проверял, и так и так работает. Даже проверял не от создателя группы, а от администратора

**Comment by Dev-TorTikProd** [comment]
python273, скажи свой вк, я напишу, потому, как тут с ботами происходит нечто странное

**Comment by Dev-TorTikProd** [comment]
Коротко говоря, через raw заработало

`
# -*- coding: utf-8 -*-
import vk_api
import options as o
from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType

class VkBotLongPollRaw(VkBotLongPoll):
    CLASS_BY_EVENT_TYPE = {}

def main():

    vk_session = vk_api.VkApi(o.login, o.password)
    vk_session.auth()
    longpoll = VkBotLongPollRaw(vk_session, o.group_id)

    for event in longpoll.listen():

        if event.type == VkBotEventType.MESSAGE_NEW:
            print('Новое сообщение:')
            print('Для меня от: ',event.obj.user_id, end='')
            print('Текст:', event.obj.body)
            print()
`

**Comment by python273** [comment]
Ну с raw понятно, что заработает 😃 
Скинь вывод скрипта https://github.com/python273/vk_api/issues/174#issuecomment-418533599 , а то не понятно как фиксить

**Comment by rdstonech** [comment]
Встретился с той же проблемой, падает при получении сообщения. Авторизуюсь через токен

backtrace:
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\rdsto\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\rdsto\develop\python\projects\pythoncoding\pythoncoding\server.py", line 30, in run
    for event in bot_longpoll.listen():
  File "C:\Users\rdsto\develop\python\projects\pythoncoding\venv\lib\site-packages\vk_api\bot_longpoll.py", line 271, in listen
    for event in self.check():
  File "C:\Users\rdsto\develop\python\projects\pythoncoding\venv\lib\site-packages\vk_api\bot_longpoll.py", line 251, in check
    for raw_event in response['updates']
  File "C:\Users\rdsto\develop\python\projects\pythoncoding\venv\lib\site-packages\vk_api\bot_longpoll.py", line 251, in <listcomp>
    for raw_event in response['updates']
  File "C:\Users\rdsto\develop\python\projects\pythoncoding\venv\lib\site-packages\vk_api\bot_longpoll.py", line 212, in _parse_event
    return event_class(raw_event)
  File "C:\Users\rdsto\develop\python\projects\pythoncoding\venv\lib\site-packages\vk_api\bot_longpoll.py", line 158, in __init__
    if self.obj.peer_id < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'`

![image](https://user-images.githubusercontent.com/31804440/45235944-1b4ab000-b2e3-11e8-81ac-848956c2308e.png)

**Comment by python273** [comment]
Можешь запустить https://github.com/python273/vk_api/issues/174#issuecomment-418533599 и скинуть вывод? Видимо peer_id не всегда есть в сообщении

**Comment by rdstonech** [comment]
Всё запустил, вот вывод:

> {'type': 'message_new', 'object': {'id': 14, 'date': 1536382284, 'out': 0, 'user_id': 157817863, 'read_state': 0, 'title': '', 'body': 'Привет мир!'}, 'group_id': 171055070}

как видно, peer_id отсутствует

**Comment by Dev-TorTikProd** [comment]
> Можешь запустить [#174 (comment)](https://github.com/python273/vk_api/issues/174#issuecomment-418533599) и скинуть вывод? Видимо peer_id не всегда есть в сообщении

Челодой моловек, вам тут ответили

**Comment by python273** [comment]
Фиксится установкой версии API 5.80+. Не уверен стоит ли фиксы для прошлых версий добавлять
<img width="561" alt="screen shot 2018-10-02 at 10 12 37 pm" src="https://user-images.githubusercontent.com/3097956/46371166-521ca780-c690-11e8-976b-20c7e7d2d69d.png">
