### ISSUE TITLE
Получение документов по ID

### ISSUE THREAD

**Issue by Loskir** [python273/vk_api#175]
Не могу вытащить документы по ID, в обоих случаях `[]`
В коде ничего не нашел, в документации тоже

```
vk = vk_session.get_api()
doc1 = vk.docs.get_by_id(docs='275003723_473695458')
doc2 = vk.docs.getById(docs='275003723_473695458')
```

**Comment by python273** [comment]
https://vk.com/dev/docs.getById

на этой странице с нужным ID выводит нужный документ?

**Comment by Loskir** [comment]
Да

**Comment by python273** [comment]
а до `vk = vk_session.get_api()` код какой?

**Comment by Helow19274** [comment]
Может быть недостаточно прав. Я сейчас эти айди на сайте вбил, мне вернулись пустые массивы.
![default](https://user-images.githubusercontent.com/20171143/45093421-058d8d00-b121-11e8-8ecd-a927c2bd3439.png)
https://vk.com/dev/access_key

**Comment by Loskir** [comment]
Может и недостаточно, это доки, которые прислали пользователю в лс (но из браузера их видно)
Главный вопрос - как правильно писать? camelCase или через подчеркивание? Дальше разберусь😁

**Comment by Helow19274** [comment]
@Loskir docs.getById

**Comment by python273** [comment]
В python лучше писать `vk.docs.get_by_id`, потому что по PEP8 названия функций должны быть в snake_case. Оно потом само конвертируется в `docs.getById` для отправки в запросе:
https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L635-L638

**Comment by python273** [comment]
На счет документов из лс, там передается access_key, возможно его не хватает:
https://vk.com/dev/access_key

**Comment by Loskir** [comment]
спасибо, совсем про него забыл

**Comment by justxor** [comment]
@Loskir, @python273 
zz=vk.docs.get_by_id(doc='4004138_493171827',access_token='792***')
передаю  токен и все равно получаю ошибку vk_api.exceptions.ApiError: [5] User authorization failed: no access_token passed.

если делаю через  токеном группы ,то  получаю vk_api.exceptions.ApiError: [5] User authorization failed: method is unavailable with group auth.

подскажите в чем причина ?  не могу скачать документ никак
