### ISSUE TITLE
Cyrillic characters are not accepted by VK in search methods

### ISSUE THREAD

**Issue by ArtArtAn** [python273/vk_api#19]
search_str = 'психология'
groups = tools.get_all('groups.search', 20, {'q': search_str})
print(groups)

Because json.dumps expects ensure_ascii=True and request to VK will contain 
{"q": "\u043f\u0441\u0438\u0445\u043e\u043b\u043e\u0433\u0438\u044f"} this will lead to empty json response from VK 

I guess in vk_tools.py it is required to change
 while True:
            run_code = code_get_all_items % (max_count, offset, key,
                                             json.dumps(values, **ensure_ascii=False**),
                                             method, method)

**Comment by python273** [comment]
Fix in dev branch, thx

https://github.com/python273/vk_api/commit/7bf9dc2886cbb99616fc5f874bbd4967958abfcf
