### ISSUE TITLE
Unresolved reference 'VkKeyboard'

### ISSUE THREAD

**Issue by code2319** [python273/vk_api#190]
from vk_api.keyboard import VkKeyboard - Unresolved reference 'VkKeyboard'
Есть актуальные примеры с кнопками?

**Comment by Helow19274** [comment]
> Есть актуальные примеры с кнопками?

https://github.com/python273/vk_api/blob/master/examples/keyboard.py

> Unresolved reference 'VkKeyboard'

Первый раз слышу про такую ошибку вообще

**Comment by code2319** [comment]
> 
> 
> > Есть актуальные примеры с кнопками?
> 
> https://github.com/python273/vk_api/blob/master/examples/keyboard.py
> 
> > Unresolved reference 'VkKeyboard'
> 
> Первый раз слышу про такую ошибку вообще

Гениальный ответ
https://imgur.com/a/9uB7teq

**Comment by code2319** [comment]
Traceback (most recent call last):
  line 3, in <module>
    from vk_api.keyboard import VkKeyboard, VkKeyboardColor
ImportError: No module named keyboard

**Comment by Helow19274** [comment]
> Гениальный ответ

Не пользуюсь PyCharm'ом

Точно последняя версия? Точно рядом нет папки vk_api?

**Comment by code2319** [comment]
> 
> 
> > Гениальный ответ
> 
> Не пользуюсь PyCharm'ом
> 
> Точно последняя версия? Точно рядом нет папки vk_api?

Н-да... в пичарме не показывает последнюю версию только у этой либы, поэтому и нет 'галки' обновить, обновил, все гуд
