### ISSUE TITLE
Error on VkApi.auth()

### ISSUE THREAD

**Issue by TerryChan2003** [python273/vk_api#191]
/usr/lib/python3.7/site-packages/vk_api/vk_api.py in auth(self, reauth, token_only)
    169             self._auth_token(reauth=reauth)
    170         else:
--> 171             self._auth_cookies(reauth=reauth)
    172 
    173     def _auth_cookies(self, reauth=False):

/usr/lib/python3.7/site-packages/vk_api/vk_api.py in _auth_cookies(self, reauth)
    200             )
    201 
--> 202             self._api_login()
    203         else:
    204             self.logger.info('access_token from config is valid')

/usr/lib/python3.7/site-packages/vk_api/vk_api.py in _api_login(self)
    437             )['scope_' + str(self.scope)] = token
    438 
--> 439             self.storage.save()
    440 
    441             self.logger.info('Got access_token')

/usr/lib/python3.7/site-packages/jconfig/jconfig.py in save(self)
     39     def save(self):
     40         with open(self._filename, 'w') as f:
---> 41             json.dump(self._settings, f, indent=2, sort_keys=True)

/usr/lib/python3.7/json/__init__.py in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    177     # could accelerate with writelines in some versions of Python, at
    178     # a debuggability cost
--> 179     for chunk in iterable:
    180         fp.write(chunk)
    181 

/usr/lib/python3.7/json/encoder.py in _iterencode(o, _current_indent_level)
    429             yield from _iterencode_list(o, _current_indent_level)
    430         elif isinstance(o, dict):
--> 431             yield from _iterencode_dict(o, _current_indent_level)
    432         else:
    433             if markers is not None:

/usr/lib/python3.7/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    351         first = True
    352         if _sort_keys:
--> 353             items = sorted(dct.items(), key=lambda kv: kv[0])
    354         else:
    355             items = dct.items()

`TypeError: '<' not supported between instances of 'int' and 'str'`
Где то вы перепутали типы данных поступающие к ним... Зато со второго-третьего раза успешно срабатывает

**Comment by Helow19274** [comment]
Если логин - номер телефона, пишите в кавычках.

**Comment by TerryChan2003** [comment]
@Helow19274 теперь понял. Спасибо
