### ISSUE TITLE
'Event' object has no attribute 'type'

### ISSUE THREAD

**Issue by tryonelove** [python273/vk_api#194]
Появляется следующая ошибка совершенно рандомно, даже при использовании кода из примера. [bot_longpoll.py](https://github.com/python273/vk_api/blob/master/examples/bot_longpoll.py)
![putty_2018-11-04_22-17-45](https://user-images.githubusercontent.com/20541870/47968791-ce375000-e07f-11e8-956d-90871ee629fa.png)

**Comment by SANYAINC** [comment]
> Нашел решение?

> Сделал костыль
> 
> ```
> while True:
>           try:
>              for event in longpoll.listen():
>                    ....
>                    ....
>                    ....
>           except AttributeError:
>                   print('error')
> ```

**Comment by AndreyKaBelka** [comment]
> > Нашел решение?
> 
> > Сделал костыль
> > ```
> > while True:
> >           try:
> >              for event in longpoll.listen():
> >                    ....
> >                    ....
> >                    ....
> >           except AttributeError:
> >                   print('error')
> > ```
> 
> Либо устанавливай vk_api с гитхаба, а не с `pip`

Спасибо. Пойду бота чинить(

**Comment by python273** [comment]
Теперь должно работать с PyPI (`pip install -U vk_api`)

**Comment by geosonic** [comment]
Баг до сих пор не исправлен
