### ISSUE TITLE
AttributeError: 'Event' object has no attribute 'type'

### ISSUE THREAD

**Issue by SANYAINC** [python273/vk_api#198]
Вылетает, когда кто-либо отправляет голосовое сообщение.
![image](https://user-images.githubusercontent.com/31994610/48626646-78d63980-e9c3-11e8-9341-4f88f6b34813.png)

**Comment by SANYAINC** [comment]
Сделал костыль
```
while True:
          try:
             for event in longpoll.listen():
                   ....
                   ....
                   ....
          except AttributeError:
                  print('error')
```

**Comment by steamlinux** [comment]
возникает та же самая ошибка в тот момент, когда с другой стороны начинают(!) записывать голосовое сообщение

**Comment by Nix1304** [comment]
а если print(event.raw)

**Comment by SANYAINC** [comment]
> возникает та же самая ошибка в тот момент, когда с другой стороны начинают(!) записывать голосовое сообщение

Так же фиксил?

**Comment by python273** [comment]
Затестите версию из master, если все ок, то залью на PyPI

**Comment by burninggoose** [comment]
Так в мастере же щас последний коммит 29 дней назад. Или я туплю?

**Comment by python273** [comment]
Так и есть 😅 https://github.com/python273/vk_api/commit/3eba6688b05fdf09e97f1b75282fe4969c23fb92

**Comment by burninggoose** [comment]
При установке с гита у меня все работает, думаю, можно в pypi отправлять

**Comment by python273** [comment]
Теперь должно работать с PyPI (`pip install -U vk_api`)
