### ISSUE TITLE
Не получается авторизоваться

### ISSUE THREAD

**Issue by Kondra007** [python273/vk_api#20]
Здравствуйте! Помогите, пожалуйста! 
Делаю аналогично Вашим примерам, но авторизация не удаётся, всегда перекидывает на страницу, где предлагается ввести свои логин и пароль (ввожу, конечно же, правильные данные)

т.е. делаю вот так:
```
RE_LOGIN_HASH = re.compile(r'name="lg_h" value="([a-z0-9]+)"')
header = {
    'User-agent': 'Mozilla/5.0 (Windows NT 6.1; rv:38.0) '
                  'Gecko/20100101 Firefox/38.0'
}
session = requests.Session()
headers = {  # Притворимся браузером
            'User-agent': 'Mozilla/5.0 (Windows NT 6.1; rv:38.0) '
            'Gecko/20100101 Firefox/38.0'
}
response = requests.get('https://vk.com/')
params = {
    'act': 'login',
    'utf-8': 1,
    'email': username,
    'pass': password,
    'lg_h': search_re(RE_LOGIN_HASH, response.text)
}
response = requests.post('https://login.vk.com/', params=params, headers=headers)
```

И в результате прилетает страница, на которой надо ввести логин и пароль (вижу это выводом `print(response.text)`. В куках, соответственно, нет remixsid

После POST-запроса возвращается ссылка:
`http://vk.com/login.php?&to=&s=0&m=1&email=`

**Comment by Kondra007** [comment]
Тупанул. Неправильно поработал с Cookies

**Comment by kuraga** [comment]
@Kondra007 а есть код?

**Comment by Kondra007** [comment]
@kuraga Вот [тут](http://pastebin.com/isDw0K97) пример авторизации в ВК, взятый из одного моего проекта.
Там будет парочка переменных типа `config.username`, `config.password`, я не стал из заменять, думаю, Вы разберетесь.

**Comment by kuraga** [comment]
@Kondra007 Спасибо! А "серверный" вариант авторизации каков, не знаете?

**Comment by Kondra007** [comment]
@kuraga Увы, не подскажу, не работал с такой авторизацией.

**Comment by python273** [comment]
[Серверная авторизация](https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L307) есть
