### ISSUE TITLE
Не отправляется сообщение get_api messages.send.

### ISSUE THREAD

**Issue by 0xBFFFF0A4** [python273/vk_api#204]
ебланская разметка итак все понятно в пизду
>>> vk_session.auth()
>>> api = vk_session.get_api()
>>> api.messages.send("-1", "test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() takes 1 positional argument but 3 were given

Хуета сегодня какая-то, ничего работать не хочет.
Обычно я делаю через method('messages.send'... но раз так тоже можно, хочется и так попробовать.

**Comment by 0xBFFFF0A4** [comment]
божечьки-кошечьки

**Comment by ALEXREDX** [comment]
если используете `get_api()` правильное написание будет так:
`api.messages.send(user_id=123, message='test')`

только обратите внимание, что начиная с версии апи 5.90+ параметр `random_id` в методе messages.send обязателен

можно например использовать таймстамп:
`import time`
`api.messages.send(user_id=123, message='test', random_id=time.time())`
