### ISSUE TITLE
Не загружает картинку из BytesIO

### ISSUE THREAD

**Issue by Nix1304** [python273/vk_api#205]
Приветствую. Проблема следующая. Я работаю с изображением средствами PIL. После окончания требуется загрузить картинку и отправить сообщением. Сделал так:
`f = io.BytesIO()
        image.save(f, format='png')
        f.seek(0)
        files = {'photo': f.getvalue()}
        server = self.api.photos.getMessagesUploadServer(peer_id=msg.peer_id)
        r = requests.post(server['upload_url'], files=files).json()
        attachment = self.api.photos.saveMessagesPhoto(photo=r['photo'],
                                                       server=r['server'],
                                                       hash=r['hash'])
        f.close()`
Но, получаю ошибку `vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: photos_list is invalid`. По какой-то причине фотография не загружается. Что делать?

**Comment by ALEXREDX** [comment]
используйте модуль [VkUpload](https://vk-api.readthedocs.io/en/latest/upload.html)

`from vk_api import VkUpload`

`upload = VkUpload(vk)`

`f = io.BytesIO()`
`image.save(f, format='png')`
`f.seek(0)`

`photo = upload.photo_messages(photos=f)[0]`
`attachment = f"photo{photo['owner_id']}_{photo['id']}"`

**Comment by Nix1304** [comment]
Спасибо

**Comment by Nix1304** [comment]
Проблема следующая. Делаю это из-под группы, и несмотря на наличие аттача, приходит только сообщение без картинки.
