### ISSUE TITLE
photo_messages вызывает ошибку 

### ISSUE THREAD

**Issue by gectus** [python273/vk_api#210]
@python273 update: можно добавить возможность передавать VkApi / VkApiMethod

---

При использовании метода photo_messages ошибка:
File "/usr/local/lib/python3.6/site-packages/vk_api/upload.py", line 77, in photo_messages 
url = self.vk.method('photos.getMessagesUploadServer')['upload_url']
TypeError: __call__() takes 1 positional argument but 2 were given

Код:
bot = vk_api.VkApi(token=channel.token)
vk = bot.get_api()
upload = VkUpload(vk)

photo = upload.photo_messages(photos=image_path)[0]

attachments = []
attachments.append('photo{}_{}'.format(photo['owner_id'], photo['id']))

**Comment by ALEXREDX** [comment]
`upload = VkUpload(bot)`

[VkUpload](https://vk-api.readthedocs.io/en/latest/upload.html)

> Parameters:	vk – объект VkApi

**Comment by gectus** [comment]
спасибо большое!!!

**Comment by gectus** [comment]
можно закрывать

**Comment by python273** [comment]
Можно добавить возможность передавать любые
