### ISSUE TITLE
Cant get forward message

### ISSUE THREAD

**Issue by andeyzin** [python273/vk_api#218]

**Comment by python273** [comment]
Покажи код/ответы сервера. Если это про лонгпул, то там вроде через апи нужно подгружать сообщения, чтобы получить все прикрепления

**Comment by andeyzin** [comment]
Лонгпул. У меня в attachments поле fwd_messages содержит "0_0"

**Comment by marataziat** [comment]
лол у меня тоже!

**Comment by marataziat** [comment]
```
    for event in longpoll.listen():
        # event.chatid==135
        if event.type == VkEventType.MESSAGE_NEW:
            #print(vk.messages.getById(message_ids=event.random_id))
            print(event.attachments)
            #print(event["fwd_messages"][0]["text"])
```
```
{}
{}
{'fwd': '0_0'}
```

**Comment by dev-0xFF** [comment]
сделайте, пожалуйста, туториал о том, как получать прикрепления из пересланных)

**Comment by ALEXREDX** [comment]
> как получать прикрепления из пересланных)

Используй метод `messages.getById`
