### ISSUE TITLE
Add auto random_id! You can just use uuid.uuid1().int for vk.messages.send

### ISSUE THREAD

**Issue by marataziat** [python273/vk_api#222]
Add uuid.uuid1().int to vk.messages.send by default!
```
        vk.messages.send(
                    user_id=,
                    message="LOL",
                    random_id=uuid.uuid1().int
		)
```

**Comment by ALEXREDX** [comment]
уже добавлен в `utils.py`
https://github.com/python273/vk_api/blob/2990bb70ab11dae7bc3db2dd7862b48bfbfb736f/vk_api/utils.py#L40-L42

> random_id=uuid.uuid1().int

к тому же `uuid.uuid1().int` это не `int32`

**Comment by marataziat** [comment]
Тогда почему random_id обязательный? Или у меня pip не обновился?

**Comment by ALEXREDX** [comment]
Он и будет обязательным https://github.com/python273/vk_api/blob/2990bb70ab11dae7bc3db2dd7862b48bfbfb736f/examples/messages_bot/user_messages_bot.py#L74

**Comment by marataziat** [comment]
А, ок это надо из тулз вытаскивать
```
from vk_api.utils import get_random_id
```
