### ISSUE TITLE
reply_to have to be message from same chat (Как боту ответить на сообщение?)

### ISSUE THREAD

**Issue by fojetin** [python273/vk_api#224]
Мой код примерно такой:

```
import vk_api
from vk_api.bot_longpoll import VkBotLongPoll

vk_session = vk_api.VkApi(token='мой токен')
vk = vk_session.get_api()

longpoll = VkBotLongPoll(vk_session, 'айди моей группы')

for event in longpoll.listen():
        
        if event.from_chat and event.obj.text.lower() == 'Привет':
            vk.messages.send(
                chat_id=event.chat_id,
                random_id=get_random_id(),
                message='Привет!',
                reply_to=event.obj.conversation_message_id,
            )
```

При попытке отправить сообщение получаю ошибку:
`vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: reply_to have to be message from same chat`

**Comment by Sergey-Volchkov** [comment]
Вероятнее всего это сам bot long poll не позволяет это реализовать

**Comment by BrokenFG** [comment]
conversation_message_id это не тоже самое, что message_id, который нужен вам. Так же могу вас разочаровать, группы не получают message_id, для них его не хранят, тобишь в беседе вы никогда не сможете переслать какое-либо сообщение

**Comment by ALEXREDX** [comment]
![image](https://user-images.githubusercontent.com/31490684/52181699-9f0ab900-27fd-11e9-9f52-6d7e425cfd99.png)

**Comment by Lephin** [comment]
Как грустно все это. Хорошо, что нашел эту статью. А то я несколько дней искал и пытался понять, что я делаю не так. Спасибо!

**Comment by muxui** [comment]
@BrokenFG, спасибо за ответ.
Пол интернета перерыл, так и не нашел инструкции как пересылать.

**Comment by altbrace** [comment]
Год прошел, а проблема осталась.

**Comment by dan0nchik** [comment]
2020 уже, а бот все еще не может отвечать в беседах

**Comment by Sergey-Volchkov** [comment]
Не знаю с чем у вас проблема, ребят. Если пишете бота, работающего от имени группы, то нужно настроить везде доступы + сделать бота админом.
Если пишете бота, который отвечает от страницы пользователя, то сделайте отправку на peer_id
В видео пример корректного, рабочего кода: https://www.youtube.com/watch?v=gsSZ7VPlkKs

**Comment by dan0nchik** [comment]
@Sergey-Volchkov 
А бот может писать в беседе? У меня настроен везде доступ, админка ему дана в беседе, но отвечает в личные сообщения

**Comment by edwardgushchin** [comment]
> @Sergey-Volchkov
> А бот может писать в беседе? У меня настроен везде доступ, админка ему дана в беседе, но отвечает в личные сообщения

Вместо user_id вставляйте peer_id беседы, и бот ответит в беседу

**Comment by dan0nchik** [comment]
> > @Sergey-Volchkov
> 
> > А бот может писать в беседе? У меня настроен везде доступ, админка ему дана в беседе, но отвечает в личные сообщения
> 
> 
> 
> Вместо user_id вставляйте peer_id беседы, и бот ответит в беседу

Спасибо :)

**Comment by bxkr** [comment]
Хорошие новости, если мне правдиво ответили:
![image](https://user-images.githubusercontent.com/66333241/94479968-3fd19780-01de-11eb-8366-430bb958fc79.png)
Ждём 5.125, или что-то в этом роде...

**Comment by kirillbiktya** [comment]
Прошло больше года, а проблема так и не решена.

Библиотеку не использовал, на обычных requests, но сам факт.

**Comment by Stirven13** [comment]
До сих пор не исправили, сейчас проверил. Осталось месяц подождать до годовщины ошибки и будет два года.

**Comment by DragonGamees** [comment]
Вроде как есть способ. По крайней мере у меня работает. В методе vk.messages.send есть метод forward, вот через него можно и переслать сообщение:
```
import vk_api
import json
from vk_api.bot_longpoll import VkBotLongPoll

vk_session = vk_api.VkApi(token='мой токен')
vk = vk_session.get_api()

longpoll = VkBotLongPoll(vk_session, 'айди моей группы')

for event in longpoll.listen():

        if event.from_chat and event.obj.text.lower() == 'Привет':
            fwdmsg = {"peer_id": event.chat_id, "conversation_message_ids": [event.obj.conversation_message_id], "reply_to": 1 }
            vk.messages.send(
                chat_id=event.chat_id,
                random_id=get_random_id(),
                message='Привет!',
                forward=json.dumps(fwdmsg) 
            )
```

Если нужно переслать сообщение, то "reply_to" ставим в 0. Тогда можно пересылать несколько сообщений.

**Comment by owoPeef** [comment]
>@DragonGamees
>Вроде как есть способ. По крайней мере у меня работает. В методе vk.messages.send есть метод forward, вот через него можно и переслать сообщение:

Уже прошло больше 2-х лет, а так и не сделали, но спасибо тебе за это! (сам пытался сделать через forward, вообще не получалось)

**Comment by Den473321** [comment]
пошло 4 года, интересно, решил ли он проблему?)

**Comment by dan0nchik** [comment]
> пошло 4 года, интересно, решил ли он проблему?)

лет через 10 пофиксят )

**Comment by DragonGamees** [comment]
Скорее всего и не исправят, останется только тот способ что я написал

**Comment by DragonGamees** [comment]
Хах, мой код уже не умеет отвечать на сообщения, только пересылать их. VK очень классная контора.

**Comment by Den473321** [comment]
а как ты пересылаешь их? я так и не разобрался

**Comment by DragonGamees** [comment]
Вот кусок кода, он по идее отвечает и пересылает на любое сообщение в беседе и в личном сообщении, но сейчас почему то он только пересылает. Версия API 5.95. 


`from random import randint

from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType

vk_session = vk_api.VkApi(token='КЛЮЧ СООБЩЕСВА')
vk = vk_session.get_api()

longpoll = VkBotLongPoll(vk_session, "ИД СООБЩЕСВА")

for event in longpoll.listen():
        if event.type == VkBotEventType.MESSAGE_NEW:
            vk.messages.send(
                peer_id=event.obj.peer_id,
                random_id=randint(-2147483648, 2147483647),
                message='reply_to 1',
                forward = json.dumps({"peer_id": event.obj.peer_id, "conversation_message_ids": [event.obj.conversation_message_id], "reply_to": 1 })
            )
            vk.messages.send(
                peer_id=event.obj.peer_id,
                random_id=randint(-2147483648, 2147483647),
                message='reply_to 0',
                forward = json.dumps({"peer_id": event.obj.peer_id, "conversation_message_ids": [event.obj.conversation_message_id], "reply_to": 0 })
            )
           `

Если нужно только в личных сообщениях, есть другой код

**Comment by Den473321** [comment]
> Вот кусок кода, он по идее отвечает и пересылает на любое сообщение в беседе и в личном сообщении, но сейчас почему то он только пересылает. Версия API 5.95. 
> 
> 
> ```
> from random import randint
> 
> from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
> 
> vk_session = vk_api.VkApi(token='КЛЮЧ СООБЩЕСВА')
> vk = vk_session.get_api()
> 
> longpoll = VkBotLongPoll(vk_session, "ИД СООБЩЕСВА")
> 
> for event in longpoll.listen():
>         if event.type == VkBotEventType.MESSAGE_NEW:
>             vk.messages.send(
>                 peer_id=event.obj.peer_id,
>                 random_id=randint(-2147483648, 2147483647),
>                 message='reply_to 1',
>                 forward = json.dumps({"peer_id": event.obj.peer_id, "conversation_message_ids": [event.obj.conversation_message_id], "reply_to": 1 })
>             )
>             vk.messages.send(
>                 peer_id=event.obj.peer_id,
>                 random_id=randint(-2147483648, 2147483647),
>                 message='reply_to 0',
>                 forward = json.dumps({"peer_id": event.obj.peer_id, "conversation_message_ids": [event.obj.conversation_message_id], "reply_to": 0 })
>             )
> ```
> 
> Пример работы кода
> ![Снимок экрана 2023-02-19 222237](https://user-images.githubusercontent.com/34072297/219975779-c77d3156-3c2e-49dd-a6f6-cfbddcae6f50.png)
> 
> Если нужно только в личных сообщениях, есть другой код, где все работает
> Если нужно можешь обращаться   
> 
> 

да, в личных сообщениях я умею, а вот пересылать не понял как. Спасибо

**Comment by DragonGamees** [comment]
Все, я разобрался, мне тех поддержка помогла, в моем коде была ошибка froward принимает is_reply  
Вот полностью рабочий код
```
from random import randint

from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType

vk_session = vk_api.VkApi(token='КЛЮЧ СООБЩЕСВА')
vk = vk_session.get_api()

longpoll = VkBotLongPoll(vk_session, "ИД СООБЩЕСВА")

for event in longpoll.listen():
        if event.type == VkBotEventType.MESSAGE_NEW:
            vk.messages.send(
                peer_id=event.obj.peer_id,
                random_id=randint(-2147483648, 2147483647),
                message='is_reply  1',
                forward = json.dumps({"peer_id": event.obj.peer_id, "conversation_message_ids": [event.obj.conversation_message_id], "is_reply ": 1 })
            )
            vk.messages.send(
                peer_id=event.obj.peer_id,
                random_id=randint(-2147483648, 2147483647),
                message='is_reply  0',
                forward = json.dumps({"peer_id": event.obj.peer_id, "conversation_message_ids": [event.obj.conversation_message_id], "is_reply ": 0 })
            )
```

Вообще судя по всему использовать этот код, так как он работает и в личных и в беседах

**Comment by mikhaildegtuarev** [comment]
Прошло 5 лет :) reply_to  так и не работает

**Comment by DragonGamees** [comment]
> Прошло 5 лет :) reply_to так и не работает

reply_to работает, только он требует message_id, который есть только в личных сообщениях и в беседах созданные сообществом.

**Comment by delameter** [comment]
> "is_reply ": 1

он прямо так  и работает, с пробелом в ключе?

**Comment by Stirven13** [comment]
С 23 февраля

**Comment by DragonGamees** [comment]
Способ через ```conversation_message_id``` работает как в лс так и в беседах, также и редактировать сообщения можно как в лс так и в беседах. Этот способ предпочтительное, ```message_id``` для ботов лучше забыть... Уже десяток ботов пишу и через ```conversation_message_id``` все прекрасно работает

**Comment by delameter** [comment]
нашел таки страничку про работу ботов в беседах:
https://dev.vk.com/ru/api/bots/development/messages

вот бы её пару дней назад обнаружить
