### ISSUE TITLE
bot_vk.py

### ISSUE THREAD

**Issue by Vlad3lou** [python273/vk_api#227]
while True:
    response = vk.method('messages.get', values)
    if response['items']:
        values['last_message_id'] = response['items'][0]['id']
    for item in response['items']:
            write_msg(item[u'user_id'],u'Привет, Хабр!')
    time.sleep(1)

**Comment by python273** [comment]
@Vlad3lou у тебя какой-то вопрос?

---

Вообще ужасная статья на хабре, все поставьте минусики 😬 Лонгпул нужно использовать

**Comment by TerryChan2003** [comment]
@python273 полностью согласен). Сейчас я работаю над портом VK API для Rust. Могу ли я у вас взять реализацию авторизации? Либо у всех авторизация исключительно через токены идут

**Comment by python273** [comment]
> Могу ли я у вас взять реализацию авторизации?

Да
