### ISSUE TITLE
Прикрыли messages, что делать??

### ISSUE THREAD

**Issue by Andreuno** [python273/vk_api#231]
Все, прикрыли API для ЛС. Что дальше? У меня большой софт построен на этом методе, спасите пожалуйста))

**Comment by hikiko4ern** [comment]
Хотя бы почитать другие issues на эту тему #219, #230
Можно получать токен с app_id оф. приложений, но [люди говорят](https://vk.com/wall-1_390510?z=photo-1_456241584%2Fwall-1_390516), что за это скоро банить аккаунты начнут.

**Comment by python273** [comment]
-> #219
