### ISSUE TITLE
Не могу Сохранить вложение из лс бота (группы)

### ISSUE THREAD

**Issue by justxor** [python273/vk_api#232]
В группу отправляю .txt файл , необходимо сохранить его на пк , перепробовал уже все методы ,ничего не работает . id документа , который вытащило при загрузке 4004149_493171827

`vk.docs.get_by_id(doc='4004149_493171827',access_token='792***')` 
это попытка через токен группы ,получаю -`User authorization failed: method is unavailable with group auth.`
хотя токен приложения тоже передавал, 

пробовал тоже самое через авторизацию аккаунта ,получаю ошибку -
`vk_api.exceptions.ApiError: [5] User authorization failed: no access_token passed.`

подскажите ,как сохранить документ на локалку  , что нужно исправить или может еще какой то другой способ ?

**Comment by python273** [comment]
На счет загрузки не уверен

Токен перезаписывается с токеном из объекта VkApi, нельзя передавать как параметр `access_token`

https://github.com/python273/vk_api/blob/a70b2b513c6706a8a244f2c544c3565a8f418666/vk_api/vk_api.py#L586-L587

Может имеет смысл пофиксить.
