### ISSUE TITLE
Формулировка "побитовое сложение" в документации

### ISSUE THREAD

**Issue by NickKaramoff** [python273/vk_api#233]
В документации обнаружил следующее:

![image](https://user-images.githubusercontent.com/6566248/54086365-de2aad80-4359-11e9-8b4c-730bc3bf923a.png)

Разве `x & y` — это не побитовое _умножение_?

**Comment by python273** [comment]
Там видимо просто ошибка `&` -> `|`:
```python
# e.g.
# 0b01 - perm #1
# 0b10 - perm #2
0b01 | 0b10 == 0b11
```
