### ISSUE TITLE
Дополнение в документацию метода code_auth

### ISSUE THREAD

**Issue by InnokentyDM** [python273/vk_api#237]
Не могу разобраться как работает метод code_auth. 
Что такое 'code', где его взять?

Для прояснения контекста. 
Я использую еще один сторонний app для oauth авторизации. И не могу сообразить как правильно отправлять запросы после oauth авторизации.
https://github.com/python-social-auth/social-app-django

**Comment by python273** [comment]
Оно наверное должно уже токен возвращать, его можно просто как `token='...'` передавать в `VkApi`
