### ISSUE TITLE
[911] Keyboard format is invalid

### ISSUE THREAD

**Issue by Nexsus3467** [python273/vk_api#238]
Появляется ошибка даже в коде из примера
`[911] Keyboard format is invalid`

**Comment by ketsu8** [comment]
Такая же проблема.

**Comment by PimyDev** [comment]
Да, тоже самое

**Comment by fdend1** [comment]
И как фиксить?

**Comment by fdend1** [comment]
Ещё и 901 выбрасывает, если не отправлять клавиатуру

**Comment by NikitaMikhailov** [comment]
столкнулся с тем же самым, пойду думать, что изменилось в запросе

**Comment by NikitaMikhailov** [comment]
@fdend1 901-ошибка, если пользователь закрыл сообщения от сообществ, все работает без клавиатуры

**Comment by ketsu8** [comment]
Я тут проверил даже если отправлять JSON официального примера с [vk.com/dev](https://vk.com/dev/bots_docs_3?f=%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%2B%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B%), то он все равно выдает ошибку 911.

**Comment by NikitaMikhailov** [comment]
проверил формат JSON в библиотеке, сравнил с аналогичным в документации ВК-совпадают
JSON ВК не работает 
раз в час посылаю запрос, если починят-напишу

**Comment by Gwynbleidd0** [comment]
Вк что-то поменяли в api и нигде об этом не написали?

**Comment by fdend1** [comment]
Ещё интересно почему не все боты отвалились

**Comment by Laminariy** [comment]
Я нашел причину проблемы. payload теперь нельзя оставлять None. Необходимо хотя бы payload=[]
Похоже, вк что-то поменяли и не предупредили.

**Comment by GitBib** [comment]
> Я нашел причину проблемы. При добавлении кнопки, payload теперь нельзя оставлять None. Необходимо хотя бы payload=[]
> Похоже, вк что-то поменяли и не предупредили.

в vk переделали валидатор клавиатуры и теперь не нужно передавать payload.

**Comment by python273** [comment]
Сейчас работает без фикса или нет? У меня вроде ок

**Comment by GitBib** [comment]
> Сейчас работает без фикса или нет? У меня вроде ок

Работает без фикса. Закрывай.
