### ISSUE TITLE
Проблема с User Long Poll API (Access denied)

### ISSUE THREAD

**Issue by ketsu8** [python273/vk_api#240]
У меня возникла проблема при использовании [User Long Poll API](https://vk.com/dev/using_longpoll).

```python
import vk_api
from vk_api.longpoll import VkLongPoll

login, password = 'login', 'pass'
vk_session = vk_api.VkApi(login, password)
vk_session.auth(token_only=True)

longpoll = VkLongPoll(vk_session)

for event in longpoll.listen():
    print(event.type)
```

При запуске возникает следующая ошибка:

```bash
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    longpoll = VkLongPoll(vk_session)
  File "/usr/local/lib/python3.6/dist-packages/vk_api-11.4.0-py3.6.egg/vk_api/longpoll.py", line 503, in __init__
  File "/usr/local/lib/python3.6/dist-packages/vk_api-11.4.0-py3.6.egg/vk_api/longpoll.py", line 513, in update_longpoll_server
  File "/usr/local/lib/python3.6/dist-packages/vk_api-11.4.0-py3.6.egg/vk_api/vk_api.py", line 636, in method
vk_api.exceptions.ApiError: [15] Access denied: no access to call this method
```

Проблема в аккаунте или в коде?

**Comment by dismorale** [comment]
Аналогичная проблема. Попытался запустить старый код, но получил эту ошибку. 
`vk_api.exceptions.ApiError: [15] Access denied: no access to call this method`
Скорее всего контакт опять что-то поменял и не предупредил никого.

**Comment by python273** [comment]
#219

**Comment by Stepan47** [comment]
Я конечно поздно пишу, но как решить эту проблему?
У меня не получается пишет вот что:

`vk_api.exceptions.ApiError: [15] Access denied: group messages are disabled`

помогите.

**Comment by nanavizhuniki** [comment]
> Я конечно поздно пишу, но как решить эту проблему?
> У меня не получается пишет вот что:
> 
> `vk_api.exceptions.ApiError: [15] Access denied: group messages are disabled`
> 
> помогите.

Хмм... Здесь сказанно, что сообщения группы выключены... Может это так и есть?

**Comment by Fedos-py** [comment]
Получилось решить проблему?
У меня тоже ошибка vk_api.exceptions.ApiError: [15] Access denied: no access to call this method
Помогите, пожалуйста, если Вы разобрались.
