### ISSUE TITLE
Bots LongPool Access denied

### ISSUE THREAD

**Issue by xkord** [python273/vk_api#247]
```python
vk_session = vk_api.VkApi(token='***')
longpoll = VkBotLongPoll(vk_session, 1234567)
```

Подскажите что делаю не так. Поставил LongPool Api 5.80 в настройках. Сам LongPoll Api включен. Авторизация через ключ доступа. 

vk_api.exceptions.ApiError: [15] Access denied: no access to call this method

**Comment by Oktai15** [comment]
@python273 тоже столкнулся с такой проблемой

**Comment by python273** [comment]
Не уверен какие могут быть проблемы кроме неверного токена или ид группы 🤔

**Comment by Oktai15** [comment]
Все аргументы верные, перепроверил...

**Comment by Oktai15** [comment]
Нашел причину проблемы: если на вход стоит двухфакторная авторизация, то по токену войти не выходит. По логину и паролю с auth_handler все норм.

**Comment by Oktai15** [comment]
Ага, но это все равно не дает доступ к сообщениям, например, так как нужна авторизация по токену

**Comment by Oktai15** [comment]
Починил. @xkord, убедись, что вот это выставлено в настройках группы:
![image](https://user-images.githubusercontent.com/17337773/57821105-f96dcb00-7797-11e9-8a7d-ffceee5303f2.png)

**Comment by klassik2k16** [comment]
Пересоздать токен пробовали?

**Comment by ruselcmplx** [comment]
Ребятки, а не подскажете как так залогиниться без логина только с токеном?
vk_session = vk_api.VkApi(token='***')

**Comment by ALEXREDX** [comment]
> Ребятки, а не подскажете как так залогиниться без логина только с токеном?
> vk_session = vk_api.VkApi(token='***')

vk_session.auth(token_only=True)

**Comment by python273** [comment]
`auth` нужно вызывать только если нужно получить токен (или куки). `token_only` просто отключает проверку кук, чтобы лишний раз не логиниться, когда токен валидный. Если токен уже есть, то вызывать `auth` не нужно

**Comment by drygdryg** [comment]
При создании токена сообщества нужно указывать права на управление сообществом помимо доступа к сообщениям.
