### ISSUE TITLE
Получение куки для vk_api

### ISSUE THREAD

**Issue by ishiro-dev** [python273/vk_api#249]
Прочитав [этот](https://github.com/python273/vk_api/issues/142), не знаю как получить куки. Подскажет кто?

**Comment by python273** [comment]
https://github.com/python273/vk_api/blob/master/examples/get_all_audio.py#L11-L18

**Comment by ishiro-dev** [comment]
Я приведу пример. Я создал небольшое веб-приложение на flask, где я хочу реализовать скачивание аудио. Официальный ВК АПИ там подключен,и я имею доступ к токену ,если пользователь авторизуется. Получается, я не могу использовать Вашу версию ВК АПИ, чтобы получить аудиозаписи?

**Comment by python273** [comment]
`VkAudio` - Модуль для получения аудиозаписей без использования официального API. Он работает через скрапинг m.vk.com. Поэтому чтобы использовать VkAudio нужно пройти аутентификацию на vk.com и получить куки пользователя.

В случае веб приложения это возможно только в случае, если юзеры будут вводить свои логин и пароль. Скорее всего будет проще получать ссылки на скачивание со своего аккаунта, но из-за настроек приватности не всегда могут быть доступны аудио пользователей.
