### ISSUE TITLE
VkRequestsPool do not expect "False" as API response

### ISSUE THREAD

**Issue by Filarius** [python273/vk_api#25]
Example
```
with vk_api.VkRequestsPool(vk_session) as pool:
  user_id = 3
  friends[user_id] = pool.method('friends.get', {'user_id': user_id})
```
This raise exception in vk_tools.py on line
`                    self.pool[i + x][2].update(response[x])`
because **update** expect dictionary, but **False** given

User with ID 3 is not exists now. So API reply with error. But in Execute API method it reply with **False** instead of dictionary with response data or error data

**Comment by python273** [comment]
https://github.com/python273/vk_api/commit/b5893ebb44033ae685dd271c4e1937633a17dbd2 Fixed in dev branch
