### ISSUE TITLE
User LongPoll не работает

### ISSUE THREAD

**Issue by vit1-irk** [python273/vk_api#254]
Проблема может быть как-то связана с #247 

Пробую скрипт из примеров вот такой:
```python

import vk_api
from vk_api.longpoll import VkLongPoll, VkEventType

login, password = '+7-номер', 'pass'
vk_session = vk_api.VkApi (login, password)

try:
    vk_session.auth (token_only = True)
except vk_api.AuthError as error_msg:
    print (error_msg)
    exit()

longpoll = VkLongPoll(vk_session)

for event in longpoll.listen (vk_session):
........
```

Выдаёт ошибку

```
Traceback (most recent call last):
  File "./vk-api-test.py", line 18, in <module>
    longpoll = VkLongPoll(vk_session)
  File "/usr/local/lib/python3.7/dist-packages/vk_api/longpoll.py", line 503, in __init__
    self.update_longpoll_server()
  File "/usr/local/lib/python3.7/dist-packages/vk_api/longpoll.py", line 513, in update_longpoll_server
    response = self.vk.method('messages.getLongPollServer', values)
  File "/usr/local/lib/python3.7/dist-packages/vk_api/vk_api.py", line 636, in method
    raise error
vk_api.exceptions.ApiError: [15] Access denied: no access to call this method
```

Пробовал даже логиниться отдельно по токену, полученному из OAuth в браузере. Пробовал создавать приложение и указывать app_id в конструкторе сессии + токен, всё без толку.

Обычное VK API работает нормально, запросы делает, но longpoll почему-то ни в какую не хочет.

**Comment by ALEXREDX** [comment]
https://github.com/python273/vk_api/issues/219

**Comment by vit1-irk** [comment]
Так, походу, это общая для всех проблема из-за администрации ВК
Можно закрывать тогда

**Comment by ZI7PPER** [comment]
А делать то что? Я смотрел на других ветках, так пишут что-то про обходы и т. д. А  то есть нормально уже боту нельзя отправлять сообщения?
