### ISSUE TITLE
Обновление VkKeyboard

### ISSUE THREAD

**Issue by PaveTranquil** [python273/vk_api#256]
Сегодня выкатили обновление клавиатур для ботов. Появились не только type=text, но и vkpay, location и open_app. Модуль VkKeyboard ещё не обновлён: в нём можно создавать только кнопки type=text. Приходится дополнительно самому оптимизировать код и добавлять костыли.

Просьба обновить VkKeyboard в соответствие с [документацией ВКонтакте](https://vk.com/dev/bots_docs_3?f=4.%20Клавиатуры%20для%20ботов). Заранее спасибо.

**Comment by klassik2k16** [comment]
[Уже в примерах](https://github.com/python273/vk_api/blob/master/examples/keyboard.py)

**Comment by BulatSa** [comment]
pip не обновлен 
Last released: Jan 30, 2019
https://pypi.org/project/vk-api/
