### ISSUE TITLE
VkBotLongPoll не распознает вход или покидание пользователем чата

### ISSUE THREAD

**Issue by EugeneTheDev** [python273/vk_api#258]
При присоединении/покидании чата event.type по логике должен быть VkBotEventType.GROUP_JOIN или VkBotEventType.GROUP_LEAVE, однако он остается VkBotEventType.MESSAGE_NEW

**Comment by klassik2k16** [comment]
Нет. Это как раз таки сообщение с доп. полем action.
```

if event.type == VkBotEventType.MESSAGE_NEW:
    print(event.object.action)
 

```

**Comment by EugeneTheDev** [comment]
А зачем тогда нужны те два типа событий?

**Comment by PaveTranquil** [comment]
События типов group_join и group_leave отвечают за вступление в сообщество и выход из него. На обработку событий из чатов это никак не влияет.
