### ISSUE TITLE
не работают сообщения в беседе

### ISSUE THREAD

**Issue by cheesegaproj** [python273/vk_api#259]
Не получается получить\отправить сообщение в беседу. В лс работает без проблем, а вот в беседах нет.
vk.messages.send( #Отправляем сообщение
                    user_id=event.user_id,
                    message='Ваш текст',
                    random_id=random.randint(-2147483648, +2147483648)
		)
работает, а вот беседы нет:
send_message(vk_session, 'chat_id', event.chat_id, message='Держите котиков!', attachment=None)
def send_message(vk_session, id_type, id, message=None, attachment=None, keyboard=None):
    vk_session.method('messages.send',{id_type: id, 'message': message, 'random_id': random.randint(-2147483648, +2147483648), "attachment": attachment, 'keyboard': keyboard})

**Comment by klassik2k16** [comment]
Покажи полный код как это должно работать. Желательно на pastbin.

**Comment by cheesegaproj** [comment]
import vk_api
import random
from vk_api.longpoll import VkLongPoll, VkEventType
def write_msg(user_id, message):
    vk.method('messages.send', {'user_id': user_id, 'message': message, 'random_id':10})

# API-ключ созданный ранее
token = "токен"
vk_session = vk_api.VkApi(token=token)
longpoll = VkLongPoll(vk_session)
# Авторизуемся как сообщество
vk = vk_session.get_api()


# Основной цикл
for event in longpoll.listen():
    if event.type == VkEventType.MESSAGE_NEW and event.to_me and event.text:
   #Слушаем longpoll, если пришло сообщение то:			
        if event.text == '1' or event.text == 'Второй вариант фразы': #Если написали заданную фразу
            if event.from_user: #Если написали в ЛС
                vk.messages.send( #Отправляем сообщение
                    user_id=event.user_id,
                    message='Ваш текст',
                    random_id=random.randint(-2147483648, +2147483648)
		)
            elif event.from_chat: #Если написали в Беседе
                vk.messages.send( #Отправляем собщение
                    chat_id=event.chat_id,
                    message='Ваш текст'
		)
В лс отвечает без проблем

**Comment by cheesegaproj** [comment]
ищу сейчас какие-то варианты решения этого - ничего толкового не нашел. Может быть ошибка в правах сообщества, но не думаю. У токена есть все права, в беседе бот админ

**Comment by klassik2k16** [comment]
Попробуй без elif`a.

**Comment by ALEXREDX** [comment]
> ```python
>             elif event.from_chat: #Если написали в Беседе
>                 vk.messages.send( #Отправляем собщение
>                     chat_id=event.chat_id,
>                     message='Ваш текст'
> 		)
> ```

`random_id` где?

**Comment by xDorus** [comment]
Используй VkBotLongPoll.

**Comment by dvuhvosty** [comment]
При использовании VkBotLongPoll перестаёт работать и ЛС. В [документации VK API](https://vk.com/dev/bots_longpoll) сказано, что методу надо передавать ещё server и key, но метод VkBotLongPoll этого не предусматривает:
`    longpoll = VkBotLongPoll(vk_session, group_id = group_id, key = key, server = server)
TypeError: __init__() got an unexpected keyword argument 'key'`

**Comment by dvuhvosty** [comment]
При использовании VkBotLongPoll отваливается и ЛС. В [документации VK API](https://vk.com/dev/bots_longpoll) сказано, что методу надо передавать ещё server и key, но пр попытке передать их методу получаю ошибку:
```
longpoll = VkBotLongPoll(vk_session, group_id = group_id, key = key, server = server)
TypeError: __init__() got an unexpected keyword argument 'key'
```
А если их не передавать, то уведомления о событиях просто не приходят, хотя с user longpoll всё работало

**Comment by snowwm** [comment]
> При использовании VkBotLongPoll отваливается и ЛС.

В настройках всё включено?
`https://vk.com/<group>?act=longpoll_api`
`https://vk.com/<group>?act=longpoll_api_types`

> В документации VK API сказано, что методу надо передавать ещё server и key

Библиотека получает их сама, передавать не нужно.

P.S. Сам не пробовал BotLongPoll, могу что-то напутать.

**Comment by cheesegaproj** [comment]
Все разрешения стоят

**Comment by dvuhvosty** [comment]
> В настройках всё включено?

> `https://vk.com/<group>?act=longpoll_api_types`

Включил, заработало. Спасибо

**Comment by Ol3gNoz** [comment]
Твоя проблема в том, что ты используешь обычный Longpoll.
Нужно использовать VkBotLongpoll документация есть в данном репозиторий)))
Но код оставлю:
https://pastebin.com/JNGwYYNe

**Comment by cheesegaproj** [comment]
![image](https://user-images.githubusercontent.com/32526934/60745474-0a121480-9f83-11e9-9b68-d757de83a357.png)
Теперь ошибка доступа при запуске, но не знаю что не так

**Comment by Ol3gNoz** [comment]
Зайди в настройки группы, работа с АРI, там выбираешь Лонгполл, типы событий, нужные включаешь и ставишь последнию версию Апи (там найдешь) и если это все сделал, то проверь токен на доступ к сообщениям

**Comment by cheesegaproj** [comment]
![image](https://user-images.githubusercontent.com/32526934/60745942-2747e280-9f85-11e9-97fe-5d859fe266b7.png)
Всё стоит и в токене стоят все разрешения

**Comment by Ol3gNoz** [comment]
Хм, по идеи, у меня такое было, когда метод для пользователей, я вызывал сообществом, может стоит проверить требования метода B dev

**Comment by cheesegaproj** [comment]
Там используется вроде всё как везде
![image](https://user-images.githubusercontent.com/32526934/60746551-eef5d380-9f87-11e9-9b47-8766d2342184.png)
