### ISSUE TITLE
No handler for two-factor authorization.

### ISSUE THREAD

**Issue by levin-kelevra** [python273/vk_api#26]
Привет!
На моем аккаунте настроена двух-факторная аутентификация.
При попытке залогиниться получаю следующее:

`AuthorizationError: No handler for two-factor authorization.`

Будет ли написан обработчик?

**Comment by python273** [comment]
Обработчик каждый себе сам пишет, вот самый простой

`
import vk_api

def two_factor():
    code = input('Code? ')
    return code


def main():
    login, password = 'log', 'pass'
    vk = vk_api.VkApi(login, password, auth_handler=two_factor)

    try:
        vk.authorization()
    except vk_api.AuthorizationError as error_msg:
        print(error_msg)
        return

    print('ok!')
    

if __name__ == '__main__':
    main()
`
