### ISSUE TITLE
Токен не работает

### ISSUE THREAD

**Issue by wenhaug** [python273/vk_api#261]
Python version 3.6.6.
vk-api version '11.4.0'
В вк зарегистрировал стандалоне приложение. Через него получил токен через url: https://oauth.vk.com/authorize?client_id={}&display=page&redirect_uri=https://oauth.vk.com/blank.html&scope=photos,audio,video,docs,notes,pages,status,offers,questions,wall,groups,email,notifications,stats,ads,offline,docs,pages,stats,notifications&response_type=token&v=5.95""".format(client_id)

Я логинюсь как юзер, с данными своей странице в вк. А токен из стандалоне приложения, которое принадлежит моей странице.
'''    
user = User()
    client_id = 72*6*87
    token = "mytokenfromOath"
    vk_session = vk_api.VkApi(login=user.login,
                              password=user.password,
                              token=token)
    try:
        vk_session.auth(token_only=True)
    except vk_api.AuthError as error_msg:
        print(error_msg)
        raise NotImplementedError
'''

Данные пользователя получаю следующим образом:
'''   
optional_fields = ["home_town", "sex", "city",
                           "photo_400_orig", "bdate"]
        users = vk_session.method('users.get',
                                  values={
                                      'user_ids': user_ids,
                                      'fields': optional_fields,
                                      })
'''
Проблема в том, что токен не работает почему-то. Я ожидал также вывод всех optional fields. Но почему-то только bdate показывается. У некоторых пользователей на страницах есть их город, но он мне не доступен для чтения через ['city]. Хотя визуально я вижу, что на страницах пользователей есть город.

Я считаю, что Токен не сработал, и мне по-прежнему доступны только ограниченные fields. Может в коде ошибка?

**Comment by wenhaug** [comment]
Еще при использовании функции vk_api.VkApi() такое ощущение, что этому методу все равно какой токен я использую. Я использовал настоящий токен, а затем придуманный. И не было проблем с логином, и не было предупреждений.

**Comment by python273** [comment]
> Через него получил токен через url: 

В VkApi можно пердавать `app_id` и `scope`, тогда токен сам будет запрашиваться при вызове `auth`

> Еще при использовании функции vk_api.VkApi() такое ощущение, что этому методу все равно какой токен я использую. Я использовал настоящий токен, а затем придуманный. И не было проблем с логином, и не было предупреждений (при верных логине и пароле).

Токен проверяется только при вызове `auth`

> `'fields': optional_fields,`

Список нельзя передавать в `.method`, нужно конвертировать в строку с разделением запятыми:
`'fields': ','.join(optional_fields),`

Еще можно использовать:
```python
vk = vk_session.get_api()
users = vk.users.get(
    user_ids=user_ids,
    fields=optional_fields,
)
```

**Comment by wenhaug** [comment]
Спасибо, разобрался. Теперь все работает.
