### ISSUE TITLE
Загрузка изображений из сети в VkUpload

### ISSUE THREAD

**Issue by PaveTranquil** [python273/vk_api#266]
Добрый день, попал в затруднительное положение. Хотел воcпользоваться подмодулем VkUpload, чтобы загрузить изображение в сообщения при помощи photo_messages. Делал это двумя способами:
1. Прогонял через requests и кидал как параметр photos (декодировал в utf-8 тоже пробовал)
![image](https://user-images.githubusercontent.com/22418658/60378866-ece4bf80-9a31-11e9-8d13-e14a18824844.png)
2. Напрямую подавал url-адрес как параметр photos
![image](https://user-images.githubusercontent.com/22418658/60378972-819bed00-9a33-11e9-865c-f7bcb0eef95d.png)

Оба способа, как видно из скриншотов, оказались проигрышными. Также видно, что используется функция open(), которая не принимает на вход url'ы. Есть какая-то альтернатива внутри vk_api или же придётся костылиться обычными методами API?

Жду ответов, заранее спасибо.

P,S. Про неправильное место import'а говорить не надо: файл тестовый

**Comment by python273** [comment]
https://github.com/python273/vk_api/blob/master/examples/messages_bot/user_messages_bot.py#L64-L65

**Comment by PaveTranquil** [comment]
![image](https://user-images.githubusercontent.com/22418658/60388882-9a061900-9ac0-11e9-94fa-0c2183314f82.png)
![image](https://user-images.githubusercontent.com/22418658/60388884-ac805280-9ac0-11e9-83c8-ee79f2531a7e.png)
![image](https://user-images.githubusercontent.com/22418658/60388904-139e0700-9ac1-11e9-8a9d-efebee378531.png)
![image](https://user-images.githubusercontent.com/22418658/60388919-565fdf00-9ac1-11e9-9cc8-eec7625af1c3.png)
В продолжение предыдущему вопросу: изображения по-видимому загружаются на сервер VK, но почему-то не крепятся к сообщению. Смотрите код: изображение рабочее, функция msg() работала в других ботах, upload возвращает результат типа `"photo<group_id>_<photo_id>_<access_key>"`, разделяя каждое фото запятой без пробелов. Пробовал и с access_key и без — не работает. Пробовал передавать не строку, а массив типа `["photo<group_id>_<photo_id>_<access_key>", "photo<group_id>_<photo_id>_<access_key>"...]` — тоже не работает. Что делать, подскажите, пожалуйста?
