### ISSUE TITLE
Загрузка изображений в параметр attachments

### ISSUE THREAD

**Issue by PaveTranquil** [python273/vk_api#267]
![image](https://user-images.githubusercontent.com/22418658/60388882-9a061900-9ac0-11e9-94fa-0c2183314f82.png)
![image](https://user-images.githubusercontent.com/22418658/60388884-ac805280-9ac0-11e9-83c8-ee79f2531a7e.png)
![image](https://user-images.githubusercontent.com/22418658/60388904-139e0700-9ac1-11e9-8a9d-efebee378531.png)
![image](https://user-images.githubusercontent.com/22418658/60389120-1864ba00-9ac5-11e9-8319-4c23bc2955d3.png)

В продолжение предыдущему вопросу: изображения по-видимому загружаются на сервер VK, но почему-то не крепятся к сообщению. Смотрите код: изображение рабочее, функция msg() работала в других ботах, upload возвращает результат типа `"photo<group_id>_<photo_id>_<access_key>"`, разделяя каждое фото запятой без пробелов. Пробовал и с access_key и без — не работает. Пробовал передавать не строку, а массив типа `["photo<group_id>_<photo_id>_<access_key>", "photo<group_id>_<photo_id>_<access_key>"...]` — тоже не работает. Что делать, подскажите, пожалуйста?

_Originally posted by @PaveTranquil in https://github.com/python273/vk_api/issues/266#issuecomment-506983605_

**Comment by python273** [comment]
параметр называется `attachment`, а ты передаешь `attachments`
