### ISSUE TITLE
Авторизация с неверными данными

### ISSUE THREAD

**Issue by violet1one** [python273/vk_api#269]
- Верный логин, неверный пароль
- Неверный логин, верный пароль
- Неверный логин, неверный пароль
Одна и та же ошибка  

`Unexpected error: <class 'vk_api.exceptions.BadPassword'>
     vk_session.auth()
    self._auth_cookies(reauth=reauth)
    self._vk_login()
    raise BadPassword('Bad password')
vk_api.exceptions.BadPassword: Bad password`

**Comment by prostomarkeloff** [comment]
Я конечно всё понимаю, но это ни разу не баг.

**Comment by violet1one** [comment]
просто напросто в response = self.http.post('https://login.vk.com/', values) (vk.api, line 267)
при любых неверных  данных

`parent.onLoginFailed(4, {"email":"%email%"});`
