### ISSUE TITLE
Parallel requests

### ISSUE THREAD

**Issue by kuraga** [python273/vk_api#27]
Good day!

https://gist.github.com/kuraga/c7d733fa9e9c67669c23

Interesting? It works! Up to 7x boost on my comp!

Also what about thread-safety in VkApi?

**Comment by python273** [comment]
Привет. Не совсем понял где буст. Про execute все понятно ([vk_tools](https://github.com/python273/vk_api/blob/master/vk_api/vk_tools.py) с ним и сделаны). Зачем запускать потоки с задержкой в 0.5 тоже не понятно.

С thread-safety скорее всего никак, для этого нужно локи ставить на запросы, т.к. быстрее 3 запросов в секунду слать нельзя, поэтому без локов может быть все плохо.

**Comment by kuraga** [comment]
У меня запрос приходит 4-5 секунд. Так мы не ожидаем ответа.
Ждать .34 наверное все же не нужно... Если thread-safety, то точно не надо.

**Comment by python273** [comment]
Ага, понял. Но тут нужно проверить, что не вызывается too_many_rps_handler и как после таких запросов идут другие запросы, т.к. это может быть не быстрее, чем мы бы их слали в один поток.

**Comment by kuraga** [comment]
Ну у меня прокатило, 1000 запросов `get.wall`, поэтому написал. Правда, отвечает он потом медленнее (ну или канал забивается). Feel free to close, просто к сведению...
--
Отправлено из Mail.Ru для Android пятница, 18 марта 2016г., 11:13 +01:00 от Kirill Python < notifications@github.com> :
