### ISSUE TITLE
Нужен фикс к VkUpload

### ISSUE THREAD

**Issue by TheDeaX-Lab** [python273/vk_api#270]
stories.getPhotoUploadServer сказано что можно использовать link_text и link_url почему от вас идут свои ошибки?

**Comment by prostomarkeloff** [comment]
Какие ошибки?

**Comment by TerryChan2003** [comment]
> Какие ошибки?

https://ibb.co/KxPBTqR вот что я посчитал нужным закоментировать в файле upload.py 2 строки в функции story

**Comment by TerryChan2003** [comment]
@prostomarkeloff ?
