### ISSUE TITLE
Как сделать бота на vk_api с такой командой:

### ISSUE THREAD

**Issue by TheDN17** [python273/vk_api#273]
Например:
Команда: пнуть "заданный участник"
Ответ: участник пнул заданного участника

**Comment by vffuunnyy** [comment]
@TheDN17 мне кажется или за такое обычно платят?

Тебе нужно просто включить лонгполл/колбэк в группе, добавить в беседу, дать права админа и написать 10 строчек кода🤔, где будет авторизация с токеном, потом приём событий и потом обработка команды и собственно Кик человека, думаю, вам [сюда](vk.com/dev/methods).
