### ISSUE TITLE
В рандомное время вылетает ошибка KeyError: 'comments', фиксится перезагрузкой пк.

### ISSUE THREAD

**Issue by Bloodielie** [python273/vk_api#274]
Как я понял это ошибка в апи.Ибо мой код работает всегда рандомное количество времени.
Вот код мб ошибка в нем:
```python
import vk_api
import time
import random

vk = vk_api.VkApi(login = '', password = '')
vk.auth()

i = -1
comment = ['Привит работяги','Мда одмен курага','Сейчас бы манго','Наица','Не наица','Пользуясь случаем хочу сказать Володя арангутанг']
id = [-57846937, -28905875, -103083994, -156480091, -174949577]

print('Время старта:' + time.ctime() + '\n')

while True:
	i = i + 1
	if i > 4:
		i = 0
	with vk_api.VkRequestsPool(vk) as pool:
		newsfeed = pool.method('newsfeed.get', {'count': 1,'source_ids':id[i]})	    	    
	s = random.choice(comment)
	print(newsfeed.result)
	if newsfeed.result["items"][0]['comments']['can_post'] == 1 and newsfeed.result["items"][0]['comments']['count'] == 0:
		vk.method('wall.createComment',{'owner_id':newsfeed.result['items'][0]['source_id'],'post_id':newsfeed.result['items'][0]['post_id'],'message':s})
		print('Время:' + time.ctime())
		print('Оставлен комментарий.\nSource_id группы:' + str(newsfeed.result['items'][0]['source_id']) + '\nPost_id:' + str(newsfeed.result['items'][0]['post_id']) + '\nТекст:' + s + '\n')						
		time.sleep(0.00001)
```

**Comment by Bloodielie** [comment]
Через print чекаю, что выдает newsfeed глазами нахожу поле comments однако программа выдает KeyError:'comments'

**Comment by python273** [comment]
Не уверен как такое происходить, если в ответе есть comments. Можешь добавить проверку `'comments' in ...`, но скорее всего в чем-то другом проблема

VkRequestsPool тут смысла нет использовать, лучше поменяй на 
https://github.com/python273/vk_api/blob/master/examples/simple_example.py#L17-L24
или `vk.method(`

**Comment by Bloodielie** [comment]
Ты вроде писал, что VkRequestsPool работает через execut и выдает больше запросов.Тк это первонах и скорость тут нужна добавил его.

**Comment by python273** [comment]
Если ты только один запрос в нем делаешь, то разницы нет. Если бы ты проверял все группы в нем за раз, тогда бы был смысл

**Comment by Bloodielie** [comment]
А если код обернуть в vk.execut и переписать его то скорость увеличится?
