### ISSUE TITLE
VkTools().get_all('groups.search'), отдаёт лишь 1000 результатов

### ISSUE THREAD

**Issue by vffuunnyy** [python273/vk_api#275]
Сделал поиск по группам. Результаты:
```python
q = 'Music'
ses = VkApi(token='')

print(ses.get_api().groups.search(q=q, type='group', count=0)['count'])
# --> 74113

print(VkTools(ses).get_all('groups.search', 1000, {'q': q, 'type': 'group'})['count'])
# --> 1000
```

Почему он отдаёт лишь 1000 результатов?

**Comment by python273** [comment]
Потому что вк отдает только 1000, можно проверить, если поставить offset=999: https://vk.com/dev.php?params[q]=Music&params[future]=0&params[market]=0&params[offset]=999&params[v]=5.101

`get_all` в count записывает реальное количество загрузившихся объектов

**Comment by vffuunnyy** [comment]
с get_all_iter тоже самое, но там стоит while True и yield => он должен все 74к группы отдать.

**Comment by python273** [comment]
Я об этом и говорю, ВК отдает только 1000, поэтому ты никак не сможешь загрузить больше. Можешь попробовать `q` разный делать, но там думать нужно как сделать

**Comment by vffuunnyy** [comment]
лол, дичь, ладно, спасибо
