### ISSUE TITLE
Доступ  к сообщениям пользователя

### ISSUE THREAD

**Issue by bar2104y** [python273/vk_api#276]
#219 
Написано, что необходимо подключаться используя app_id верифицированного приложения(KAteMobile), 
```

vk_session = vk_api.VkApi(token=self.vk_token, app_id=self.app_id, 
                          client_secret=self.vk_client_secret)
self.vk = vk_session.get_api()
```

Возможно ли как-то авторизоваться только через логин и пароль или же необходимо получать токен через oauth?

**Comment by moonzlo** [comment]
Для доступа к сообщениям, необходимо указать scope='messages', рекомендую использовать именно pip install vk, у него таких проблем не наблюдается.

**Comment by bar2104y** [comment]
Это как не наблюдается, это же ограничение самого ВК, точнее его API?

**Comment by moonzlo** [comment]
> Это как не наблюдается, это же ограничение самого ВК, точнее его API?

Ну вот так, доступ к сообщения можно получить только выпустив соответствующий токен с разрешением на чтение лс, я использую этот сайт https://vkhost.github.io/ и Kate Mobile, так-как он гарантированно это разрешение выдаёт. Даже при ручном запросе не всегда получается прочитать или отправить сообщения, Kate Mobile работает железно. app_id нужен для специфических задач, в большинстве случае достаточного одного токена.
Авторизация через логин и пароль возможна, в случае если вы не используете двухфакторную аутентификацию

**Comment by bar2104y** [comment]
2685278 И получается вот этот app id?

**Comment by moonzlo** [comment]
> 2685278 И получается вот этот app id?

думаю да, эту ссылку вполне можно переиспользовать.

**Comment by TheDeadRaven** [comment]
Здравствуйте, есть новые методы обхода этого ограничения?

**Comment by vladshumetov** [comment]
> Здравствуйте, есть новые методы обхода этого ограничения?

смотрю ни 1 я вечно использовал логин/пасс, ибо получать новый токен для каждого тяжко)
Такая же проблема была в 2021-ом где-то. Нужен новый app_id

**Comment by TheDeadRaven** [comment]
> > Здравствуйте, есть новые методы обхода этого ограничения?
> 
> смотрю ни 1 я вечно использовал логин/пасс, ибо получать новый токен для каждого тяжко) Такая же проблема была в 2021-ом где-то. Нужен новый app_id
> 
> upd. форк с работающей авторизацией, устанавливается через pip install git+https://github.com/M1h4n1k/vk_api_fix_auth.git отсюда можете и ссылку достать посмотреть код если боитесь за безопасность

спасибо!
