### ISSUE TITLE
Не приходит ответ от LongPoll, если в сообщении больше 8ми вложений

### ISSUE THREAD

**Issue by bluepanee** [python273/vk_api#278]
При таком коде, взятым из примеров

```python
import vk_api
from vk_api.bot_longpoll import VkBotLongPoll

group_id = "xxx"
group_token = "xxx"

def main():
    vk_session = vk_api.VkApi(token=group_token)
    longpoll = VkBotLongPoll(vk_session, group_id)

    for event in longpoll.listen():
        print(event.obj)

if __name__ == "__main__":
    main()
```

Приходят все ответы от longpoll(Кроме редактирования сообщения, если это беседа), но если прикрепить больше 8ми фотографий/документов/видео, то ответа нет. Думал проблема в версии апи или в отмеченных типах запросов, менял - нет эффекта. Проблема наблюдается как в беседах, так и в лс сообщества

**Comment by prostomarkeloff** [comment]
Проблема поллинга ВКонтакте, но никак не библиотеки.

**Comment by nedogimov** [comment]
Исправлено. Но приходит только 1 вложение.

**Comment by Kwizchm** [comment]
Можно нормально извлекать вложения, если использовать messages.getById по тому id сообщения, что пришло `messages.getById(message_ids=[event.obj.message['id']], group_id='id_группы')['items'][0]`
