### ISSUE TITLE
'dict' object has no attribute 'access_key'

### ISSUE THREAD

**Issue by P2LOVE** [python273/vk_api#281]
Получаю в лс через лонгполл сообщение с атачем в виде картинки.
Для того, чтобы его переслать/сохранить итд, нужно иметь его аксес кей. 

Сам айди атача получается через event.attachments
Но при попытке получить что то из event.attachments.access_key и подобное, ловлю AttributeError.

Как получать ключи используя event? (Или другие способы)

**Comment by python273** [comment]
`['access_key']`

**Comment by P2LOVE** [comment]
Так словарь event впринципе не содержит в себе access_key же
Единственный способ, который я нашел - строить костыль через messages.getById

**Comment by python273** [comment]
А, для лонгпула юзеров сообщения с прикреплениями нужно отдельно подгружать
