### ISSUE TITLE
Нет информации про reply и forward в сообщениях 1 на 1 с ботом.

### ISSUE THREAD

**Issue by eboshare** [python273/vk_api#283]
**Это баг или я чего-то не понимаю?**

При ответе (reply) или пересылании (forward) сообщения в диалоге 1 на 1 с ботом информации о reply и forward нет в ивенте. Еще заметил что если добавить бота в беседу и общаться с ним там 1 на 1, то эта информация будет присутствовать в ивенте, но если добавить туда еще одного человека, то она опять пропадает.

![image](https://user-images.githubusercontent.com/45375305/63220717-785f0f00-c19e-11e9-90db-32966fd44a7b.png)

**Вот код для тестирования**
```python3
import vk_api
import json
from vk_api.bot_longpoll import VkBotLongPoll


GROUP_ID = None  # your group_id
TOKEN = None  # your token


vk_session = vk_api.VkApi(token=TOKEN)
bot = vk_session.get_api()
bot_longpoll = VkBotLongPoll(
    vk=vk_session, group_id=GROUP_ID
)


for event in bot_longpoll.listen():
    print(
        json.dumps(event.raw, ensure_ascii=False, indent=2)
    )

```

**Comment by prostomarkeloff** [comment]
тут скорее нужно смотреть в документации официальной

**Comment by eboshare** [comment]
> тут скорее нужно смотреть в документации официальной

Да смотрел уже, ничего там не нашел по этому поводу, а в поддержке еще не ответили.

**Comment by prostomarkeloff** [comment]
@eboshare https://vk.com/wall-160259808_33931

**Comment by eboshare** [comment]
Это был баг от вк
