### ISSUE TITLE
Формат битого ответа от лонгполла

### ISSUE THREAD

**Issue by P2LOVE** [python273/vk_api#285]
В последнее время, очень часто стал отмирать сессия лонгполла для сообществ, после 4-6 часов работы.
Если сделать реконнект, то все ок. Но вопрос в том, как понимать, когда пора обновлять сессию?
Мне сказали, что когда сессия протухает - приходят error вместо эвентов, но не уточнили в каком формате итд.
Можно краткий экскурс в то, как выглядят ответы от протухшей сессии?

**Comment by P2LOVE** [comment]
Добавлю, что очевидно, сидеть с открытым дебагером часами, чтобы поставить брейкпоинт когда сессия умрет - очень долго и почти нереально

**Comment by P2LOVE** [comment]
Все еще очень актуальный вопрос, так как по каким-то причинам, на  боте с запущенным лонгполлом он стал отваливаться уже через считанные часы

**Comment by xtess16** [comment]
@P2LOVE сервера вк перезагружаются ночью) Так ты просто не перехватывай ошибку или отлавливай через traceback.format_exc

**Comment by P2LOVE** [comment]
Ты видимо не понял. Спустя n часов, лонг перестает присылать эвенты. И это не только ночью.

**Comment by prostomarkeloff** [comment]
> Ты видимо не понял. Спустя n часов, лонг перестает присылать эвенты. И это не только ночью.

[Тут](https://github.com/python273/vk_api/blob/master/vk_api/bot_longpoll.py#L256) "ловятся" все ошибки при поллинге (конечно помимо того когда ВК просто не присылает эвенты), было бы не плохо обернуть реквест в try-except и при надобности засыпать на ~1 минуту когда сервера ВК перезагружаются.

**Comment by P2LOVE** [comment]
Попробую, спасибо
