### ISSUE TITLE
Лонгполл не отвечает на сообщения с вложениями

### ISSUE THREAD

**Issue by DojeFoggy** [python273/vk_api#288]
Привет. Вчера написал бота который при получении сообщений с фотографиями берет их и формирует из них отложенный пост в группе. Всё было норм, до тех пор пока я не попытался отправить более 7 вложений. Никакой ошибки не было, но и не было ответа от сервера. Поле event  не приходило. После попытки отправить 8-10 вложений я попробовал написать простой текст без ничего - ивент был получен. Что делать? Это проблема вк или вашей библиотеки?

**Comment by python273** [comment]
dup https://github.com/python273/vk_api/issues/278

Скорее всего проблема у ВК, пишите в поддержку
