### ISSUE TITLE
О полях кроме response и error

### ISSUE THREAD

**Issue by kuraga** [python273/vk_api#29]
Не все зпросы характеризуются только полями `response` и `error`. Например, метод `execute` может отдавать с двумя полями: `response` и `execute_errors` (хотя это незадокументировано.

Предлагаю:

1. Добавить метод `low_method` (или иное название), возвращающий сырой ответ, а не значение поля `response`/выбрасывающий исключение.
2. Внедрить использование метода `low_method` в метод `method` (и другие?)

Готов подготовить патч.

/cc @python273

**Comment by python273** [comment]
Нужно сделать класс Response с полем execute_errors и возвращать его вместо dict'а

**Comment by kuraga** [comment]
@python273 В него инкапсулировать сам ответ, который с `response`, `error`, `execute_errors`? И в каком методе его возвращать?

**Comment by python273** [comment]
Не, наследоваться от dict и возвращать его из VkApi.method

**Comment by kuraga** [comment]
Не получится. `method` сейчас возвращает не `dict`, а что придется (обычно это `list`).

**Comment by kuraga** [comment]
@python273 Не получится. `method` сейчас возвращает не `dict`, а что придется (обычно это `list`).

**Comment by python273** [comment]
Просто лучше сохранить обратную совместимость

**Comment by kuraga** [comment]
@python273 Я об этом и говорю. Если сделать так, как Вы говорите (если я не ошибаюсь), - это как раз нарушает совместимость... 

Вы предложили обернуть в класс `Response` [вот эту переменную `response`](https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L396), и ее возвращать (обернутую). Но сейчас возвращается не эта переменная, а [`response['response`]`](https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L427) (тип которой вообще говоря, неизвестен).

**Comment by python273** [comment]
Не, я предлагал response['response'], но там действительно с типами проблема.

В общем предлагаю добавить аргумент, при котором будет возвращаться response, вместо response['response']

**Comment by python273** [comment]
Добавил параметр raw, теперь можно отлавливать ошибки execute: https://github.com/python273/vk_api/commit/39e78df9373a3e49681ff187c2101f2041f0063b
