### ISSUE TITLE
Album Cover для Audio

### ISSUE THREAD

**Issue by vanyasem** [python273/vk_api#292]
В мобильной версии VK можно выдернуть ещё background песни, что будет обложкой альбома в маленьком разрешении.
```
<div class="ai_play" style="background-image:url(https://sun9-55.userapi.com/c637527/v637527452/6567e/NdzdhLSOKKg.jpg)"><i class="i_play"></i></div>
```

Настолько маленькая, что не уверен, имеет ли это вообще смысл, но возможно позже сделаю.

**Comment by qwertyadrian** [comment]
Реализовано в #340
