### ISSUE TITLE
Падение bot_longpoll при инициализации в Python 3.7

### ISSUE THREAD

**Issue by gva-dev** [python273/vk_api#296]
При инициализации  bot_longpoll, происходит сравнение  "elif self.obj.peer_id < CHAT_START_ID:". Так как объект может быть пустым - проект валится. Мне кажется, следует сделать проверку на пустоту объекта.

**Comment by gva-dev** [comment]
Локально сделал фикс проблемы, однако, не могу запушить и открыть Pull Request. Ругается на права (403)

**Comment by python273** [comment]
https://github.com/python273/vk_api/issues/174#issuecomment-426396218

**Comment by gva-dev** [comment]
А-а-а, вот оно что. Тогда да, можно закрывать.
