### ISSUE TITLE
callback_bot.py Ошибка

### ISSUE THREAD

**Issue by hydrapon** [python273/vk_api#301]
Решил разобраться  с callback_bot.py. Просто скопировав от туда код ловлю ошибку в строке с
data = request.get_json(force=True, silent=True)
текст ошибки: 
RuntimeError: Working outside of request context.
This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
Код в PyCharm Flask

**Comment by python273** [comment]
Это при открытии страницы?
