### ISSUE TITLE
Не отправляются события редактирования сообщения в беседе.

### ISSUE THREAD

**Issue by ViktorooReps** [python273/vk_api#307]
Использую vk_api.bot_longpoll
и печатаю события простым
```
from pprint import pprint as pp
for event in longpoll.listen():
    pp(event.raw)
```
Все нужные галочки в настройках сообщества проставлены, event'ы от получения сообщений в беседе/лс и редактирования сообщений в лс получаются и, соответсвенно, печатаются.

От редактирования в беседе - нет

**Comment by nedogimov** [comment]
Такие события используются только в LongPoll юзера.
