### ISSUE TITLE
[911] Keyboard format is invalid: row 4 contains too much columns

### ISSUE THREAD

**Issue by retart1337** [python273/vk_api#318]
При попытке отправить клавиатуру появляется данная ошибка. При этом, при отправке клавиатуры, содержащей только одну строку, данная ошибка не появляется. Пожалуйста, разберитесь.

**Comment by nedogimov** [comment]
Можете код прислать? У меня все работает.

**Comment by retart1337** [comment]
![image](https://user-images.githubusercontent.com/48867150/70375910-8df67100-1914-11ea-831c-72a18d9bf71a.png)
![image](https://user-images.githubusercontent.com/48867150/70375913-964eac00-1914-11ea-9853-3c6bfdaf5499.png)

**Comment by nedogimov** [comment]
> @nedogimov
> ![image](https://user-images.githubusercontent.com/48867150/70375910-8df67100-1914-11ea-831c-72a18d9bf71a.png)
> ![image](https://user-images.githubusercontent.com/48867150/70375913-964eac00-1914-11ea-9853-3c6bfdaf5499.png)

У вас на нижнем скриншоте 5 кнопок, вроде макс 4.

**Comment by retart1337** [comment]
это регулируется условие `if k != order2`

**Comment by nedogimov** [comment]
> Даже если так, это регулируется условие `if k != order2`
> Однако, максимальное число строк - 10
> https://vk-api.readthedocs.io/en/latest/keyboard.html#vk_api.keyboard.VkKeyboard.add_line
> ![image](https://user-images.githubusercontent.com/48867150/70463507-14a27e00-1ace-11ea-8ff7-00baea74d037.png)

Я про add_button. Там макс 4

**Comment by retart1337** [comment]
> > Даже если так, это регулируется условие `if k != order2`
> > Однако, максимальное число строк - 10
> > https://vk-api.readthedocs.io/en/latest/keyboard.html#vk_api.keyboard.VkKeyboard.add_line
> > ![image](https://user-images.githubusercontent.com/48867150/70463507-14a27e00-1ace-11ea-8ff7-00baea74d037.png)
> 
> Я про add_button. Там макс 4

у меня после добавления кнопки создается новая строка. Если бы у меня было более 4 кнопок на строке, я бы получил ошибку от самого модуля vk_api, а не при отправке клавиатуры в сообщении

**Comment by python273** [comment]
А что в `keyb.get_keyboard()`? В самой библиотеке могут не все ограничения быть добавлены, нужно смотреть документацию

**Comment by retart1337** [comment]
`{"one_time":false,"inline":false,"buttons":[[{"color":"default","action":{"type":"text","payload":null,"label":"buy` order1 "}}],[{"color":"default","action":{"type":"text","payload":null,"label":"buy order3 "}}],[{"color":"default","action":{"type":"text","payload":null,"label":"buy order4 "}}],[{"color":"default","action":{"type":"text","payload":null,"label":"buy order5 "}}],[]]}``
