### ISSUE TITLE
Не работает MESSAGE_REPLY

### ISSUE THREAD

**Issue by ilyapishchulin** [python273/vk_api#319]
Берем код из исходника или пишем сами 
if event.type == VkBotEventType.MESSAGE_REPLY:
метод не работает.
По кд приходит new

**Comment by nedogimov** [comment]
Он для лс сообществ.

**Comment by ilyapishchulin** [comment]
Так и для бот лонгпула же приходит.

**Comment by ilyapishchulin** [comment]
+ в примере он есть.
