### ISSUE TITLE
Аудио из альбомов с access_hash не скачивается

### ISSUE THREAD

**Issue by DaveScream** [python273/vk_api#320]
ссылка на альбом с access_hash:
https://m.vk.com/audio?act=audio_playlist63831405_415&access_hash=5f8c90e114ae340af7&api_view=862f34ebcc73fa586b9e66d088df10&lang=ru

при попытке скачать аудиозаписи из этого альбома вылетает ошибка:
![image](https://user-images.githubusercontent.com/3002276/70644562-50ffe680-1c54-11ea-97b4-95398c7eb04e.png)

Вопрос как правильно скачивать аудио из альбомов с access_hash

**Comment by python273** [comment]
`get_audio_by_id` не поддерживает access_hash, только `get` и `get_iter`
https://github.com/python273/vk_api/blob/623fa4e8cb1b7a9bc401d7e363fe8705494e60d9/vk_api/audio.py#L39-L45
