### ISSUE TITLE
Проверка на правильный телефон

### ISSUE THREAD

**Issue by pythonovskiy** [python273/vk_api#324]
phone=input('Телефон: ')
Как проверить, принадлежит веденный телефон к какой нибудь странице вконтакте?

**Comment by pythonovskiy** [comment]
phone=input('Телефон: ')
Как проверить, принадлежит веденный телефон к какой нибудь странице вконтакте?

**Comment by prostomarkeloff** [comment]
Проверить регулярным выражением.
