### ISSUE TITLE
Обработка payload`ов кнопок

### ISSUE THREAD

**Issue by dadyarri** [python273/vk_api#326]
В версии API 5.103 у текстовых кнопок появился новый параметр [payload](https://vk.com/dev/bots_docs_3?f=4.3.+%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0+%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B), строка, которая возвращается в событии [messages_new](https://vk.com/dev/groups_events).
Мне она не приходит, хотя использую последнюю версию:
```python
...
self.bot_session = vk_api.VkApi(token=self.token, api_version="5.103")
...
```
Клавиатура:
```json
{
  "one_time": false,
  "buttons": [
    [
      {
        "action": {
          "type": "text",
          "label": "Подтвердить",
          "payload": "{\"button\": \"confirm\"}"
        },
        "color": "positive"
      },
      {
        "action": {
          "type": "text",
          "label": "Отмена",
          "payload": "{\"button\": \"deny\"}"
        },
        "color": "negative"
      }
    ]
  ]
}
```

Сырой ответ от сервера:
![image](https://user-images.githubusercontent.com/51821039/71726227-7cd34e00-2e47-11ea-9611-1808a92accc8.png)

**Comment by ractyfree** [comment]
Сами кнопки создаются в чате?

**Comment by dadyarri** [comment]
> Сами кнопки создаются в чате?

Отправляется заранее созданный вручную json

**Comment by Xoma163** [comment]
Кнопки прилетают в event.object.payload
![image](https://user-images.githubusercontent.com/35608430/71770928-b93ca200-2f4c-11ea-8d0b-fcdafbd5b00c.png)

**Comment by dadyarri** [comment]
Кажется понял почему не работает. Удаленный вами скриншот помог.
Я пытался получать его вот так: 
```python
payload = json.loads(bot.event.payload)
```

> Попробуйте так отправить:
> "payload": json.dumps({"key": "val"})

**Comment by Xoma163** [comment]
> Кажется понял почему не работает. Удаленный вами скриншот помог.

У вас аналогичный скриншот выше, я его сразу не заметил, да, с бревном в глазу жить тяжело.
Получилось? В чём дело было?

**Comment by dadyarri** [comment]
У меня скриншот этого:
```python
pprint(event.raw)
```
А проверить сейчас нет возможности. Просто подумал, что должно помочь ваше обращение к пейлоаду через `event.object.payload`, потому что с моим `event.payload` не работает.
Но перечитал ещё раз вывод сырого ответа и понял что не в этом проблема, почему-то. В object нет параметра `payload` в принципе...
Завтра попробую ваше решение, отпишусь

**Comment by dadyarri** [comment]
Работает, спасибо
