### ISSUE TITLE
'<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by bagd1k** [python273/vk_api#327]
File "/home/bagdik/.local/lib/python3.7/site-packages/vk_api/bot_longpoll.py", line 160, in __init__
    if self.obj.peer_id < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

Cмотрел предыдущую проблему -- ключ доступа пробовал менять, версия API актуал (5.103)
Ошибку вызывает запрос на выполнение любого метода, как я понял

EDIT: Все хорошо работает с компьютера через PyCharm, но не работает на pythonanywhere. Почему так может быть?

**Comment by bagd123** [comment]
File "/home/bagdik/mysite/kadet/main.py", line 7, in listen
    for event in longpoll.listen():

Вот тут ошибка первая

**Comment by Hcerk** [comment]
Можно <<кусок>> кода, где выдаёт данную ошибку.

**Comment by DaniilSmirnov** [comment]
Все еще актуально

**Comment by DaniilSmirnov** [comment]
![image](https://user-images.githubusercontent.com/8039921/74593175-a16f3800-5039-11ea-8dda-03db78fa332b.png)
Проблему решил таким образом, файл bot_longpoll.py
