### ISSUE TITLE
SSLError только при втором запросе

### ISSUE THREAD

**Issue by Xoma163** [python273/vk_api#328]
При попытке отправить сообщение только при 2м запросе почему-то вылетает SSLError

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.vk.com', port=443): Max retries exceeded with url: /method/messages.send (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2488)')))`

После того, как нашёл в инете инструкции обновить какие-то модули связанные с ssl и requests:

`HTTPSConnectionPool(host='api.vk.com', port=443): Max retries exceeded with url: /method/messages.send (Caused by SSLError(SSLError("read error: Error([('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')])")))`

**Comment by Xoma163** [comment]
Я использую django/uwsgi+nginx

По каким-то неведомым причинам если отправлять запрос, который будет инициировать отправку сообщения через вкбота, то при конкретно второй попытке, будет какой-то треш типа SSLError, если стартовать дефолтный джанго сервер, всё ок.

Пока думаю дальше

**Comment by prostomarkeloff** [comment]
> Я использую django/uwsgi+nginx
> 
> По каким-то неведомым причинам если отправлять запрос, который будет инициировать отправку сообщения через вкбота, то при конкретно второй попытке, будет какой-то треш типа SSLError, если стартовать дефолтный джанго сервер, всё ок.
> 
> Пока думаю дальше. Как вообще связаны веб-сервер и отправка сообщений - не понимаю
> 
> Подозреваю, что ошибка как-то связана с requests

offtopic.

Ляпота, вы что-ли используете джангу для бота?

**Comment by Xoma163** [comment]
> > Я использую django/uwsgi+nginx
> > По каким-то неведомым причинам если отправлять запрос, который будет инициировать отправку сообщения через вкбота, то при конкретно второй попытке, будет какой-то треш типа SSLError, если стартовать дефолтный джанго сервер, всё ок.
> > Пока думаю дальше. Как вообще связаны веб-сервер и отправка сообщений - не понимаю
> > Подозреваю, что ошибка как-то связана с requests
> 
> offtopic.
> 
> Ляпота, вы что-ли используете джангу для бота?

использую как временное решение. Планирую разделять их на веб-приложение и на бота и делать между ними API, за те 4 месяца, что я с этим работаю, пока не придумал как это сделать максимально удобно, поэтому и не переношу, ибо выйдёт всё плохо

**Comment by Xoma163** [comment]
Решение нашлось [https://stackoverflow.com/questions/22752521/uwsgi-flask-sqlalchemy-and-postgres-ssl-error-decryption-failed-or-bad-reco](тут)

Виновник uWSGI
