### ISSUE TITLE
Баг с отправкой сообщений, в которых есть ссылка и 2+ вложений

### ISSUE THREAD

**Issue by Xoma163** [python273/vk_api#329]
При отправке сообщения, в котором содержится 2+ вложений и текстом прикреплена ссылка, второе вложение теряется

Пример работы:
Действия:
Отправляем картинку, гифку. text = "Произвольный текст"
Результат:
Бот прислал картинку, гифку, текст

Действия:
Отправляем картинку, гифку, text="https://example.com"
Результат:
Бот прислал картинку, текст
Ожидаемый результат:
Бот прислал картинку, гифку, текст

**Comment by Andreuno** [comment]
Такая же проблема(...

**Comment by 1MrEnot** [comment]
Это особенность вк - даже вручную через браузер нельзя прикрепить несколько вложений к тексту.

**Comment by Xoma163** [comment]
> Это особенность вк - даже вручную через браузер нельзя прикрепить несколько вложений к тексту.

Что? 
Я например могу отправить ссылку, документ и фотографию в одном сообщении

Более того, раньше всё работало и я ничего не обновлял, видимо что-то на стороне ВК поменялось и перестало работать

**Comment by 1MrEnot** [comment]
> > Это особенность вк - даже вручную через браузер нельзя прикрепить несколько вложений к тексту.
> 
> Что?
> Я например могу отправить ссылку, документ и фотографию в одном сообщении
> 
> Более того, раньше всё работало и я ничего не обновлял, видимо что-то на стороне ВК поменялось и перестало работать

Хех, значит всё это время это был баг
Попробуй отправить в сообщении несколько вложений и текст "0.00"
Отправится только первое вложение

**Comment by Xoma163** [comment]
> Попробуй отправить в сообщении несколько вложений и текст "0.00"

Ну, отправилось...

**Comment by Xoma163** [comment]
Решил проблему передачей в messages.send параметра `dont_parse_links`, в таком случае вк не пытается крепить ссылку как атачмент и всё нормально выводится.

**Comment by Xoma163** [comment]
Добил решение тем, что в attachments можно просто передать ссылку и она прикрепится... Без упоминания в тексте. Удобно.

Ишю можно закрывать, думаю
