### ISSUE TITLE
Игнорируется аргумент attachment в vk.messages.send

### ISSUE THREAD

**Issue by bagd1k** [python273/vk_api#330]
Получаю аргумент вида photo%owner_id%_%photo_id%_%secret_key%, передаю в messages.send, но это игнорируется. При этом текст в сообщениях отсылается

**Comment by Xoma163** [comment]
Приложите код как пытаетесь от править

**Comment by Xoma163** [comment]
У меня работает так:
attachments = ['photo-***_***', 'doc***_***']
vk_session.messages.send(...
                              attachment=','.join(attachments),
                              )

**Comment by prostomarkeloff** [comment]
Неверный формат значит. Библиотека никак не валидирует значения, вообще.

**Comment by Tka4uk-Andrei** [comment]
Хм, столкнулся с похожей проблемой.
Когда отправляю фото с параметром `access_key`, то фото просто не пересылается.
Пример attachment'а
`photo171411400_456240451_0e8cd85889663a6f96`
Его формат:
<type><owner_id>_<media_id>_<access_key>

**Comment by YorkDW** [comment]
Уточните, пожалуйста, с каким токеном отправляется запрос? С токеном сообщества нельзя прикреплять чужие вложения, защищенные access_key

**Comment by Tka4uk-Andrei** [comment]
Да, в моём случае бот работает через ключ сообщества. Как я понимаю пересылка вложений доступна только с ключом доступа пользователя?

**Comment by YorkDW** [comment]
В документации есть раздел с правилами отправки вложений сообществом. Прикреплять можно "публичные объекты", то есть те, у которых нет access_key, и загруженные в сообщество. 
https://vk.com/dev/bots_docs_2?f=3.%2BСообщения%2Bот%2Bбота

**Comment by Tka4uk-Andrei** [comment]
А кому тогда разрешена пересылка приватных вложений? Только обычным пользователям?

**Comment by YorkDW** [comment]
Да, обычный пользователь может просто переслать вложение. Сообществу нужно его скачать и загрузить от своего имени.

**Comment by Tka4uk-Andrei** [comment]
А если авторизовывать бота через Authorization code flow или Implicit flow, то доступ к пересылке будет возможен?

**Comment by YorkDW** [comment]
1. Не совсем понимаю, как можно авторизировать сообщество каким-то особенным образом. Если речь о доступе к работе от лица сообщества при доступе через токен пользователя (у которого есть такие права), вряд ли это сработает, но я не проверял. 
2. Эту дискуссию можно перенести в беседу в телеграме (ссылка есть в readme), а этот issue можно было бы и закрыть

**Comment by Tka4uk-Andrei** [comment]
ок, для меня в принципе всё понятно с отправкой

**Comment by Xoma163** [comment]
Решил проблему передачей в messages.send параметра `dont_parse_links`, в таком случае вк не пытается крепить ссылку как атачмент и всё нормально выводится.

**Comment by z00ma** [comment]
отправляю аудио сообщение так, если отправлять самому себе, то приходит, а если другому контакту то пустота, хотя текстовые сообщения отправляет
```
vk.messages.send(
    user_id=owner_id, 
    random_id=getRandomInt64(), 
    attachment=f'audio_message{owner_id}_{audio_msg_id}_{access_key}'
)
```
