### ISSUE TITLE
Если вложений в сообщение больше 7 приходит только одно

### ISSUE THREAD

**Issue by Kwizchm** [python273/vk_api#335]
Работая с bot longpoll API мониторю сообщения входящие. Если боту отправить сообщение с семи или меньше фотографиями, он нормально всё примет. Если же их будет 8-10, то в сообщении будет только первое вложение (в event.raw то же самое)

Точно не буду говорить, но вроде несколько дней назад всё работало. 

### Окружение

vk_api: 11.6.1

API: 5.103

### Пример

Код обычный, просто принимает евенты, как и в примере репы.

При принятии какого-либо сообщения в лог помимо всего записывается длина массива 'attachments'. Так вот если отправить 7 вложений

    2020-01-28 03:28:45,361 [INFO] = Got event (VkBotEventType.MESSAGE_NEW)
    2020-01-28 03:28:45,361 [INFO] = {'message': {'date':  ...
    2020-01-28 03:28:45,365 [INFO] = ATTACHMENTS LENGTH IS 7

Далее отправляю 10 вложений

    2020-01-28 03:30:03,251 [INFO] = Got event (VkBotEventType.MESSAGE_NEW)
    2020-01-28 03:30:03,252 [INFO] = {'message': {'date':  ...
    2020-01-28 03:30:03,252 [INFO] = ATTACHMENTS LENGTH IS 1

Пример кода на который распространяется проблема

        for event in longpoll.listen():

        if event.type == VkBotEventType.MESSAGE_NEW:
            print('Attachments = ', len(event.obj.message['attachments']))
            print('Новое сообщение:')

            print('Для меня от: ', end='')

            print(event.obj.message['from_id'])

            print('Текст:', event.obj.message['text'])
            print()

**Comment by python273** [comment]
Тут обсуждалось https://github.com/python273/vk_api/issues/278. Что-то у вк сломано

**Comment by Kwizchm** [comment]
Извиняюсь, не увидел
