### ISSUE TITLE
Методы VkAudio возвращают пустую строку вместо ссылки на аудиозапись

### ISSUE THREAD

**Issue by qwertyadrian** [python273/vk_api#339]
_Методы VkAudio возвращают пустую строку вместо ссылки на аудиозапись_
Наверняка проблема не в библиотеке, а просто ВК снова что-то шаманит с аудиозаписями, так как теперь тег `<input type="hidden" value="">` пустой.

### Окружение

vk_api: _11.7.0_
python: _3.8_

API: _5.92_

### Пример

```python
vk_session = VkApi("login", "password")
vk_session.auth()

vk_audio = VkAudio(vk_session)
tracks = vk_audio.get()
```

Используя инструменты разработчика в браузере я выяснил, что при нажатии на кнопку начала воспроизведения (в мобильной версии сайта) отправляется POST запрос на URL https://m.vk.com/audio c параметрами `act=reload_audio` и `ids`, а результатом запроса является нечто подобное: `{'data': [[[456240032, 118264010, 'https://m.vk.com/mp3/audio_api_unavailable.mp3?extra=qxrqDO5AEhrWlZDfsLHPntPXqLHTCdGOzxnSyxqVsu9mCJfuns5LwxDyv2fLzdqXELH4qOLJzvboDNn5DgnOmxnInc1ZounUyMzTEMvqmtb0Dw5zus9UyxPPnJzIyxHksZbzmwnzx3zdCJaZBdz3ou1iyu5Uutq5C3PdB1fJswiXqwLmBM1YEw03s1rrrJaXt3u1lva1A2rdywrLBMrwmwDOy3PbCtrKDwmYm3v0zw94tI55n29PvZ1wAtuVBLD4vZ94t1DJsgiVEdHduOW3ow54x2vblOfZBLHsyxP1uNbWzdjVqwDzvY5yq28#AqS1nZi', 'One For The Money ', 'Escape The Fate', 198, 0, 0, '', 0, 2, ''...`

**Comment by qwertyadrian** [comment]
В ходе экспериментов, я пришел к выводу, что в теле POST запроса о котором я писал выше передается параметр `act=reload_audio` и `ids`, который равен `<owner_id>_<id>_a043dd532e760f8a76_c6a794bd5fdf2ccfd8` (они могут быть перечислены через запятую).
Что означают последние два параметра я выяснить не смог, но могу точно сказать одно: они берутся из тега `<div>` в HTML странице с аудиозаписями под значением `data-audio[13]`.
Пример: 
`<div data-id="118264010_456240024" data-audio="[456240024,118264010, "", "never too late (three days grace  )", "radio tapok",208,0,0, "",0,2, "", "[]", "ac6ecceab0d40461c5//a043dd532e760f8a76///c6a794bd5fdf2ccfd8/", "", {"duration":208, "content_id": "118264010_456240024", "puid22":11, "account_age_type":3, "_siteid":276, "vk_id":211843669, "ver":251116}, "", "", "", false, "a8c6152b7et9gtrkbep1skjjwwhfvdza6s5ghbnojkjludk",0,0, true, "9bcd12b77fef6fb27d"]" class="audio_item_118264010_456240024 ai_has_btn audio_item" onclick="audioplayer. Playpause(event, '118264010_456240024' , true); ">`
Тогда `data-audio[13]` равен `ac6ecceab0d40461c5//a043dd532e760f8a76///c6a794bd5fdf2ccfd8/`
При этом для передачи в запросе используются последние два значения.

В случае успеха результам запроса является подобное:
```
{'data': [[[456239938, 118264010, 'https://m.vk.com/mp3/audio_api_unavailable.mp3?extra=zhnJz3vWAwjjnYO2CY9UswzIrhmWzdrvrhHsAwzkntbNyxjHyxHbvtq2lMn2yJzvx2LgzNjRyZvYt3rOCeLKuwmVCNHLyu1VANv1ouGUmergrxzvEh04s2y2ne9eAdu4Ds1ny3nJCgTLuuW5m25qmY9eEMzZvuqWwK5Mmc86vg9mm296AxfZDwq5ztfUnKS/A2z4wMnJzty5EI9cvu9QyxzUC3LJlL9yrg1OsgvwAha9EffHDdrgBuDXru50lunRmu1enfuZs2DbmZbVmtvMzwrAl2m3EK4YnvHXA2vWENnlBuyWn2jOBJnKBG#AqSXotC', 'California Dreaming', 'Hollywood Undead', 234, 0, 0, '', 0, 1090, '', '[]', '57088509acfb5c4877//441b19c85f92932931///af7efcbcdef52183ff/', 'https://sun9-24.userapi.com/c851032/v851032326/8f9e6/Z2w2XBz9RQM.jpg,https://sun9-18.userapi.com/c851032/v851032326/8f9e3/JUDBxDlTSn0.jpg', {'duration': 234, 'content_id': '118264010_456239938', 'puid22': 4, 'account_age_type': 3, '_SITEID': 276, 'vk_id': 211843669, 'ver': 251116}, '', [{'id': '2298334889017491891', 'name': 'Hollywood Undead'}], '', [-2000987232, 1987232, '23ee63c29d03a5ab82'], 'ec9536d7iLpkzeoByriI8gki-OTx6o4', 0, 0, True, '2582c240cf986a017b']]], 'version': '74b9937af4af5e019779f17b9b80913a85ab2c79289288f7ed9a1791b30d48d0', 'counters': [0, 0, 5, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0], 'type': 0}
```
В случае неудачи: 
```
{'data': [], 'version': '74b9937af4af5e019779f17b9b80913a85ab2c79289288f7ed9a1791b30d48d0', 'counters': [0, 0, 5, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0], 'type': 0}
```

**Comment by qwertyadrian** [comment]
Можно отправлять не более 1 запроса в 1.5 секунды, в противном случае после нескольких запросов ссылки перестанут возвращаться на какое-то время.

И в одном запросе можно передать до 10 id аудиозаписей.

**Comment by grwlf** [comment]
+1

К сожалению, в 11.7.0 мне не удалось видеть не-пустые url. Нужно что-то делать.

**Comment by edombek** [comment]
У меня всё интерестнее:

import vk_api
from vk_api.audio import VkAudio
vk_session = vk_api.VkApi(login)
vk_session.auth()
vkaudio = VkAudio(vk_session)
vkaudio.get(user_id)

KeyError                                  Traceback (most recent call last)
<ipython-input-4-a387582c8a42> in <module>
----> 1 vkaudio.get(user_id)

/usr/lib/python3.8/site-packages/vk_api/audio.py in get(self, owner_id, album_id, access_hash)
     94         """
     95 
---> 96         return list(self.get_iter(owner_id, album_id, access_hash))
     97 
     98     def get_albums_iter(self, owner_id=None):

/usr/lib/python3.8/site-packages/vk_api/audio.py in get_iter(self, owner_id, album_id, access_hash)
     72                 )
     73 
---> 74             tracks = scrap_data(
     75                 response.text,
     76                 self.user_id,

/usr/lib/python3.8/site-packages/vk_api/audio.py in scrap_data(html, user_id, filter_root_el)
    242         duration = int(audio.select_one('.ai_dur')['data-dur'])
    243         full_id = tuple(
--> 244             int(i) for i in RE_AUDIO_ID.search(audio['id']).groups()
    245         )
    246         link = audio.select_one('.ai_body').input['value']

/usr/lib/python3.8/site-packages/bs4/element.py in __getitem__(self, key)
   1319         """tag[key] returns the value of the 'key' attribute for the Tag,
   1320         and throws an exception if it's not there."""
-> 1321         return self.attrs[key]
   1322 
   1323     def __iter__(self):

KeyError: 'id'

**Comment by qwertyadrian** [comment]
@edombek, какую версию vk_api вы используете. Просто судя по скриншоту у вас не последняя версия (можно заметить по фрагмету файла `/usr/lib/python3.8/site-packages/vk_api/audio.py`).

**Comment by edombek** [comment]
@qwertyadrian, твоя версия с правками, актуальная на данный момент

**Comment by qwertyadrian** [comment]
@edombek, тогда странно, что строка, в которой произошла ошика не совпадает со строкой в моем коде: https://github.com/qwertyadrian/vk_api/blob/62d25146092bb9abe1ef53d42047aba5e52df8bc/vk_api/audio.py#L244

**Comment by edombek** [comment]
@qwertyadrian, прошу прощения установил неправильно, работает)

**Comment by edombek** [comment]
@qwertyadrian, только количество аудио резко сократилось с 252 до 180, не все записи выходит получить

**Comment by qwertyadrian** [comment]
@edombek, интересно, у меня не было таких "потерь" (максимум 4 аудиозаписи я терял из 870). Если хотите, можете обратиться ко мне лично и я сам попробую выяснить, что не так, сообщив мне ID пользователя (сообщества), в котором так много аудиозаписей теряется (если профиль не закрыт, конечно).

**Comment by edombek** [comment]
@qwertyadrian, а также записи в полученном результате дублируються, например взял аудиозаписи пользователя у которого их 2005, всего 1877 уникальных id, но на выходе я вижу 3698. Дублируються они группами

**Comment by edombek** [comment]
> @edombek, интересно, у меня не было таких "потерь" (максимум 4 аудиозаписи я терял из 870). Если хотите, можете обратиться ко мне лично и я сам попробую выяснить, что не так, сообщив мне ID пользователя (сообщества), в котором так много аудиозаписей теряется (если профиль не закрыт, конечно).

ну тут был мой профиль, аудиозаписи закрыты для внешних людей, профиль не закрыт, получал аудио со своего профиля

**Comment by python273** [comment]
Ага, в результатах дублирующие аудио есть

**Comment by qwertyadrian** [comment]
@python273, насчёт дублирования. Оно было и в предыдущих версия vk_api, и до моих изменений, но с чем это связано я не знаю.

**Comment by edombek** [comment]
@qwertyadrian, когда получаю свои аудио дублирований нет, а вот когда аудио много они есть. На старой версии такого не наблюдал

**Comment by qwertyadrian** [comment]
@edombek, тут я с вами соглашусь. На этих выходных я постараюсь разобраться в чем дело.

**Comment by qwertyadrian** [comment]
Проблема с дублированием аудиозаписей была решена. Нужно было всего лишь увеличить разницу в смещении TRACKS_PER_USER_PAGE с 50 до 100.

**Comment by mayflowerr** [comment]
Вы поняли, в чем проблема с пустой ссылкой?

**Comment by edombek** [comment]
Да, но напрягает что много аудио исчезло, из моих 261 получаю 101... хотя то что без твоих фиксов получает все

**Comment by qwertyadrian** [comment]
@edombek честно говоря, я не знаю с чем это может быть связано. Я тестировал работу на трех пользователях с 890, 102 и 1354 аудиозаписями и из них получено 864, 101 и 1314 аудиозаписей соответственно, а также на сообществе с 3706 аудиозаписями - из них получено 3472.

**Comment by CyJimmy264** [comment]
@qwertyadrian опять что-то изменилось на стороне ВК?

```
>>> vkaudio = VkAudio(vk_session)
>>> import time
>>> for track in vkaudio.get_iter():
...   print(track)
...   time.sleep(5)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mveynberg/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/vk_api/audio.py", line 122, in get_iter
    tracks = scrap_data(
  File "/home/mveynberg/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/vk_api/audio.py", line 358, in scrap_data
    result = http.post(
  File "/home/mveynberg/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/mveynberg/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/mveynberg/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mveynberg/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by qwertyadrian** [comment]
@CyJimmy264 вроде нет, за последние два месяца я проблем не наблюдал.

**Comment by arkhipovkm** [comment]
**TL;DR**: Получение аудиозаписей простым "скрапингом" html страниц неэффективно и, как оказалось, не годится для получения ссылок. Предлагаю перейти на на старый добрый PHP'шный вконтактовский бэкэнд- **al_audio.php**.

Как вы наверняка знаете, Вконтакте, как и Facebook, написан на PHP. некоторые (многие) функции Вконтакте доступны по соответствующим сервису `al_<service_name>.php` пути:
- al_wall.php
- al_job.php
- al_profile.php
- al_video.php
- al_audio.php
- и т.д.

Вереницы этих запросов хорошо видны, если зайти на сайт, включить консоль разработчика и во вкладке запросов ввести "al_" в поле фильтра.

В  принципе, нет особых причин пользоваться этим бэкендом - Вконтакте и так предоставляет API для разработчиков, дублирующее эти сервисы. За исключением, конечно, мызыки - ведь она как-раз по API недоступна.

Музыкальный функционал ВК, логично предположить, доступен по пути `al_audio.php`
Это ровно те POST запросы, что усмотрел @qwertyadrian у себя в браузере в консоли.

У этого сервиса 3 основных "акта" - метода:

- `section`  
    Поисковой метод. Принимает запрос (query) и возвращает результаты поиска: аудиозаписи, альбомы, исполнители
    > Этот метод не ограничен лимитами
    ```http
    POST /al_audio.php HTTP/1.1
    Host: vk.com
    Cookie: remixsid=<remixsid>
    Content-Type: application/x-www-form-urlencoded

    al:1
    act:section
    owner_id:<owner_id>
    section:search
    q:<query>
    ```

- `load_section`  
    Этот метод используется для загрузки плейлистов (альбомов) - всей информации о плейлисте, в том числе списка аудиозаписей со всей информацией о каждой из них (кроме URL).  
    > Ограничен лимитом в 20 запросов в 10 секунд  
    ```http
    POST /al_audio.php HTTP/1.1
    Host: vk.com
    Cookie: remixsid=<remixsid>
    Content-Type: application/x-www-form-urlencoded

    al:1
    act:load_section
    owner_id:<owner_id>
    playlist_id:<playlist_id>
    offset:0
    type:playlist
    access_hash:<access_hash>
    is_loading_all:1
    ```

- `reload_audio`  
    Этот метод позволяет запросить URL'ы аудиозаписей по их id, до 10 `id` в запросе.  
    > Ограничен лимитом в 40 запросов в 60 секунд
    ```http
    POST /al_audio.php HTTP/1.1
    Host: vk.com
    Cookie: remixsid=<remixsid>
    Content-Type: application/x-www-form-urlencoded

    al:1
    act:reload_audio
    ids:<id>,<id>,<id>
    ```

Обратите внимание: единственный требующийся "Сookie" - хорошо нам всем знакомый `remixsid`, а единственный "header" - Content-Type. API, как видно, не привиредливый.

Типичный "workflow" с этим API таков:  

1. (опционально). **act:section** .Поиск алюбомов по поисковому запросу -> получаем список альбомов и список аудиозаписей, подходящих под запрос. Эти альбомы и аудиозаписи - пустые - содержат только неполные id. Нужно загрузить интересущий альбом по id для получения полной информации об альбоме.
2. **act:load_section**. Загрузка полного альбома по его `id`, полученного из шага 1 или заданного вручную (например аудиозаписи пользователя: **<owner_id>_-1**). Возвращает полную информацию об альбоме включая список аудиозаписей. Аудиозаписи не имеют URL'ов.
3. **act:reload_audio**. Пере-загрузка аудиозаписей по их `id` пачками по 10 штук для получения (зашифрованных) URL этих аудиозаписей. Обычно эти `id` аудиозаписей берутся из пердыдущего шага.

API отвечает простым JSON-ом и его достаточно легко обрабатывать. Приведу для примера ответ на запрос `load_section`:
```JSON
<!--{
    "paylod": [
        0, // Error Code; 0 means no error
        [  // Complete playlist object
            {
            "type": "playlist",
            "ownerId": -2000880598,
            "id": 3880598,
            "isOfficial": 1,
            "title": "Simulation Theory",
            "titleLang": 3,
            "subTitle": "Super Deluxe",
            "description": "",
            "rawDescription": "",
            "authorLine": "<a class=\"audio_pl_snippet__artist_link\" href=\"https://vk.com/artist/muse\">Muse</a>",
            "authorHref": "",
            "authorName": "<a class=\"audio_pl_snippet__artist_link\" href=\"https://vk.com/artist/muse\">Muse</a>",
            "infoLine1": "Альтернатива<span class=\"dvd\"></span>2018",
            "infoLine2": "2,388,485 plays<span class=\"dvd\"></span>21 tracks",
            "lastUpdated": 1566877650,
            "listens": "2388485",
            "coverUrl": "https://sun9-6.userapi.com/c849216/v849216671/15bf9e/W7-U7QQReW4.jpg",
            "editHash": "",
            "isFollowed": false,
            "followHash": "fe9a577548cde795d9",
            "accessHash": "9b580930deb7e8fff9",
            "addClasses": "audio_pl__has_thumb audio_pl__canfollow official audio_numeric audio_pl__type_main_only audio_pl__has_shuffle audio_pl__has_subtitle audio_pl__can_add_to_clubs",
            "gridCovers": "",
            "isBlocked": false,
            "list": [
                [
                    45200941,
                    -2001200941,
                    "",
                    "Algorithm",
                    "Muse",
                    246,
                    -1,
                    0,
                    "",
                    0,
                    66,
                    "",
                    "[]",
                    "8e432c93bee2c9890b//276f6fedee8f006daf///edb03441653b58741c/",
                    "https://sun9-41.userapi.com/c849216/v849216671/15bfa4/NYSqlB1vjNk.jpg,https://sun9-38.userapi.com/c849216/v849216671/15bfa1/igEKSaWB7eA.jpg",
                    {
                        "duration": 246,
                        "content_id": "-2001200941_45200941",
                        "puid22": 14,
                        "account_age_type": 3,
                        "_SITEID": 276,
                        "vk_id": 5567597,
                        "ver": 251116
                    },
                    "",
                    [
                        {
                            "id": "8099015328710656381",
                            "name": "Muse"
                        }
                    ],
                    "",
                    [
                        -2000880598,
                        3880598,
                        "9b580930deb7e8fff9"
                    ],
                    "d867bf7fR0hEm9h5CWqmPjx7h7GpfL4rpOKtvzW9seTA_VfYfeud_4MCvA",
                    0,
                    1,
                    true,
                    "945b0eed31293b1abe",
                    false
                ],
                // ... other audio objects
            ],
            "hasMore": 0,
            "nextOffset": 2000,
            "blockId": false,
            "totalCount": 21,
            "totalCountHash": ""
        },
            "html blob"
        ]
    ],
    "statsMeta": {}, // etc
    "langPack" // etc
    // ...
    // other metadata and template fields
}
```

Поле *list* - список аудиозаписей плейлиста (все аудиозаписи до *nextOffset*, который по умолчанию - 2000). Сами аудиозаписи представлены в привычном формате простого списка - такой же, как и в атрибутах `data-audio`.

Этот список распаковывается в объект, используя индекс:  
```json
{
	"AUDIO_ITEM_INDEX_ID":           0,
	"AUDIO_ITEM_INDEX_OWNER_ID":     1,
	"AUDIO_ITEM_INDEX_URL":          2,
	"AUDIO_ITEM_INDEX_TITLE":        3,
	"AUDIO_ITEM_INDEX_PERFORMER":    4,
	"AUDIO_ITEM_INDEX_DURATION":     5,
	"AUDIO_ITEM_INDEX_ALBUM_ID":     6,
	"AUDIO_ITEM_INDEX_AUTHOR_LINK":  8,
	"AUDIO_ITEM_INDEX_LYRICS":       9,
	"AUDIO_ITEM_INDEX_FLAGS":        10,
	"AUDIO_ITEM_INDEX_CONTEXT":      11,
	"AUDIO_ITEM_INDEX_EXTRA":        12,
	"AUDIO_ITEM_INDEX_HASHES":       13,
	"AUDIO_ITEM_INDEX_COVER_URL":    14,
	"AUDIO_ITEM_INDEX_ADS":          15,
	"AUDIO_ITEM_INDEX_SUBTITLE":     16,
	"AUDIO_ITEM_INDEX_MAIN_ARTISTS": 17,
	"AUDIO_ITEM_INDEX_FEAT_ARTISTS": 18,
	"AUDIO_ITEM_INDEX_ALBUM":        19,
	"AUDIO_ITEM_INDEX_TRACK_CODE":   20,

	"AUDIO_ITEM_HAS_LYRICS_BIT":     1,
	"AUDIO_ITEM_CAN_ADD_BIT":        2,
	"AUDIO_ITEM_CLAIMED_BIT":        4,
	"AUDIO_ITEM_HQ_BIT":             16,
	"AUDIO_ITEM_LONG_PERFORMER_BIT": 32,
	"AUDIO_ITEM_UMA_BIT":            128,
	"AUDIO_ITEM_REPLACEABLE":        512,
	"AUDIO_ITEM_EXPLICIT_BIT":       1024,
}
```
В конце индеска присутствуют "маски" флагов. Их нужно битово помножить на значение "AUDIO_ITEM_INDEX_FLAGS" для получения соответствующего bool значения, например  
```python
hasLyrics = data_audio[index["AUDIO_ITEM_INDEX_FLAGS"]] & index["AUDIO_ITEM_HAS_LYRICS_BIT"]
```

В свою очередь, `HASHES` (элемент [13]), раскладывается на следующие "хэши" разложением по слэшу "/" со следующими индексами:
```json
{
    "addHash": 0,
    "editHash": 1,
    "actionHash": 2,
    "deleteHash": 3,
    "teplaceHash": 4,
    "urlHash": 5
}
```
Например хэши из примера выше - `8e432c93bee2c9890b//276f6fedee8f006daf///edb03441653b58741c/` - разложатся следующим образом: 
слэшу "/":
```json
{
    "addHash": "8e432c93bee2c9890b",
    "editHash": "",
    "actionHash": "276f6fedee8f006daf",
    "deleteHash": "",
    "replaceHash": "",
    "urlHash": "edb03441653b58741c"
}
```

После всей этой обработки, получается объект аудиозаписи (названия полей исключительно на усмотрение имплементирующего):
```json
{
    "AudioID": 45200941,
    "OwnerID": -2001200941,
    "Title": "Algorithm",
    "Subtitle": "",
    "Performer": "Muse",
    "Duration": 246,
    "Lyrics": 0,
    "URL": "",
    "Context": "",
    "Extra": "[]",
    "AddHash": "8e432c93bee2c9890b",
    "EditHash": "",
    "ActionHash": "276f6fedee8f006daf",
    "DeleteHash": "",
    "ReplaceHash": "",
    "URLHash": "edb03441653b58741c",
    "CoverURLs": "https://sun6-19.userapi.com/c849216/v849216671/15bfa4/NYSqlB1vjNk.jpg",
    "CoverURLp": "https://sun6-14.userapi.com/c849216/v849216671/15bfa1/igEKSaWB7eA.jpg",
    "CanEdit": false,
    "CanDelete": false,
    "CanAdd": false,
    "IsLongPerformer": false,
    "IsClaimed": false,
    "IsExplicit": false,
    "IsUMA": false,
    "IsReplaceable": false,
    "Album": "-2000880598_3880598_9b580930deb7e8fff9",
    "AlbumID": -1,
    "TrackCode": "8ea2740blEmHtZUq-i6iNAnsl3cdpog"
}
```
> CoverURLs и CoverURLp: мальнькая и средняя обложки альбома. Полноразмерная обложка находится в поле "CoverUrl" самого плейлиста (предыдущий ответ)

В этом объекте не хватает нескольких полей, в том числе URL, это нормально. Теперь нужно отправить запрос `reload_audio` указав `id` аудио, перечисленных через запятую.

`id` аудиозаписи складывается следующим образом: `<ownerID>_<audioID>_<actionHash>_<URLHash>`. 

> Если не хватает какого-нибудь хэша хотя бы в одном `id` из 10 возможных - АПИ выдаст ошибку на весь запрос.

Пример ответа на запрос `reload_audio`:
```json
<!--{
    "payload": [
        0, // Error Code. 0 - no error
        [  // Array of requested audios, here we requested only one.
            [
                [
                    45200941,
                    -2001200941,
                    "https://vk.com/mp3/audio_api_unavailable.mp3?extra=yu51n182ntHWuZnqowvUngiUEgrmohvOqwzLAfKWxOmZzLLTzMHoAu1Hmffkuc1Vyt0Yvs91tMfMmc1imd1QnZr1nevjAMrZDLq5A19lzgnYre94vdvSnMKTDuLArgiTAhq5nI9SmuHvtJjstZyXBNnOC1i1DxyVDe42vNGUveTYnLHSlKS4EunvowvRm2fMAKH3BuLLqxyVDfPWyZqYtI9FwwTpoeK4n3KWBxjFnKDbtMHczurFrd8Wy3rLrdLyBw9rsgLLnZH0C292uuu5vwzuAZe1BI1eAwvkwM1wv21nwMGVuG#AqSOota",
                    "Algorithm",
                    "Muse",
                    246,
                    -1,
                    0,
                    "",
                    0,
                    66,
                    "",
                    "[]",
                    "8e432c93bee2c9890b//276f6fedee8f006daf///edb03441653b58741c/",
                    "https://sun6-19.userapi.com/c849216/v849216671/15bfa4/NYSqlB1vjNk.jpg,https://sun6-14.userapi.com/c849216/v849216671/15bfa1/igEKSaWB7eA.jpg",
                    {
                        "duration": 246,
                        "content_id": "-2001200941_45200941",
                        "puid22": 14,
                        "account_age_type": 3,
                        "_SITEID": 276,
                        "vk_id": 5567597,
                        "ver": 251116
                    },
                    "",
                    [
                        {
                            "id": "8099015328710656381",
                            "name": "Muse"
                        }
                    ],
                    "",
                    [
                        -2000880598,
                        3880598,
                        "9b580930deb7e8fff9"
                    ],
                    "7a4949900lsmB7Y1u_uW1wcFWIaiO34",
                    0,
                    0,
                    true,
                    "945b0eed31293b1abe",
                    false
                ]
            ],
            false,
            "b9b7eb1b5dfd9870af",
            []
        ]
    ],
    "statsMeta": {}, // etc
    "loaderVersion": "" // etc
    // ... 
    // etc
}
```

В ответе мы находим то же самое "сырое" аудио, что уже получили раньще в составе плейлиста, но уже с (зашифрованной) URL. Осталось только расшифровать хорошо нам всем знакомым `перестановочным шифром цезаря` и заменить ссылку с **.m3u8** (HLS) на **.mp3**. 

Последний пункт удобен и быстр, но необязателен. Трек можно скачать и "сшить" в .mp3 использую FFmpeg (#298 )

Лимит в 40 запросов в минуту не позволяет таким образом в одночасье "скачать" большие алюбомы (личные аудиозаписи некоторых заядлых меломанов), но подходит для подавляющего больщинства пользователей и уж тем более студийных альбомов.

Если все-таки нужно сделать много запросов в ограниченное время, то есть решение. Сервер применяет лимиты на запросы не по IP адресу, а по `remixsid`. Если в какой-то момент программа "уперлась" в потолок - можно просто переавторизоваться, или иметь "под боком" несколько предавторизованных `remixsid` токенов и подменить его на условном 41-ом запросе `reload_audio`.

Пример имплементации использования вышеописанного протокола:
- [POST запросы](https://github.com/arkhipovkm/py-musify/blob/master/musify/al_audio.py)
- [Audio Object](https://github.com/arkhipovkm/py-musify/blob/master/musify/al_audio_object.py)

**Comment by sertraline** [comment]
Привет. Я стащил vk_api для своего бота и частично починил аудио (плейлисты, альбомы, аудио пользователя и стена). За основу взял https://github.com/python273/vk_api/pull/340, но он уже не работал. Конкретнее: GET превратился в POST, соответственно местами приходит html, местами json и местами html завернутое в json.

Если раньше часть песен просто была недоступна, то теперь часть песен блокируется только с мобильной версии, аудио приходит с невалидным хешем и строчкой в жисоне `reason: subscription`, думаю здесь очевидно чего оно хочет.

Я хотел сделать пулл реквест, но так как реквест выше так и не приняли предлагаю просто [посмотреть на файл](https://github.com/sertraline/awful-bot/blob/master/core/vk_api/audio.py) если у кого-нибудь есть интерес.
