### ISSUE TITLE
3 запроса одновременно

### ISSUE THREAD

**Issue by Vast-Nectarine** [python273/vk_api#347]
_ВКонтакте позволяет отправлять 3 запроса одновременно. Почему бы не реализовать это?_

**Comment by python273** [comment]
ВК позволяет до 3 запросов в секунду отправлять юзерам и (вроде) 25 ботам, ограничение в библиотеке на 3 запроса уже есть. Именно _одновременно_ можно через https://vk.com/dev/execute отправлять до 25

**Comment by Vast-Nectarine** [comment]
Как я знаю, метод execute можно вызвать 3 раза одновременно. Т.е. за N секунд получить не 1 response, а 3 -> в 3 раза быстрее.
