### ISSUE TITLE
no access_token passed

### ISSUE THREAD

**Issue by Dominux** [python273/vk_api#350]
Хочу написать бота, который будет публиковать на стене сообщества посты

И уже битый час мучаюсь с авторизацией через `access_token`

Вот мой код:

```python
vk_session = vk_api.VkApi(
    login=vk_data['login'],
    token=vk_data['dev']['accessToken'],
    app_id=vk_data['appId'],
    client_secret=vk_data['serviceKey']
)
vk_session.auth(token_only=True)
vk = vk_session.get_api()
print(vk.wall.post(
    message="Hello world",
    owner_id=vk_data['dev']['clubNumber'],
    from_group=1
))
```

Проблема в том, что с передачей пароля всё происходит на-раз-два

А вот с этими ключами доступа я уже запутался.
Пытаюсь передавать `сервисный ключ` в параметр `client_secret`

В самой [доке](https://vk-api.readthedocs.io/en/latest/vk_api.html) написано, что:

>client_secret – Защищенный ключ приложения для Client Credentials Flow авторизации приложения (https://vk.com/dev/client_cred_flow). Внимание: Этот способ авторизации устарел, рекомендуется использовать сервисный ключ из настроек приложения.

Перелистывая кучу документации самого вк, я запутался ещё сильнее

Понятия не имею, в чём я допускаю ошибку

**Comment by python273** [comment]
если уже есть токен, то его нужно просто передать в `VkApi` и не вызвать `auth`

**Comment by Dominux** [comment]
@python273, пробовал уже

Выходит такое исключение:

```python
vk_api.exceptions.ApiError: [27] Group authorization failed: method is unavailable with group auth.
```

**Comment by python273** [comment]
У токена группы нет прав на постинг, нужно использовать токен юзера

**Comment by Dominux** [comment]
Спасибо!
Я справился
УРА!

Если кто-то сталкнётся с этой же проблемой, то получите access_token с помощью [этой спасительной инструкции](https://devman.org/qna/63/kak-poluchit-token-polzovatelja-dlja-vkontakte/)
