### ISSUE TITLE
Keyboard didn`t work in messages.send()

### ISSUE THREAD

**Issue by Jeeeeeeeeeja** [python273/vk_api#353]
Trying to send keyboard, there is an error 'vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: keyboard contains incorrect JSON' even if I send empty one.
![image](https://user-images.githubusercontent.com/10745893/80345386-b524ef00-8871-11ea-8a34-6df318b110f6.png)
![image](https://user-images.githubusercontent.com/10745893/80345406-bb1ad000-8871-11ea-97ed-969af83d8417.png)
I found nothing about this error in the internet and documentation. Also I tried, to send keyboard from examples, the same error.

### Окружение

vk_api: 11.8.0

API: 5.103

### Пример

```python
bot = vk_api.VkApi(token=TOKEN)
longpoll = VkBotLongPoll(bot, GROUP_ID)
vk = bot.get_api()
empty_keyboard = {"buttons": [], "one_time": True}
vk.messages.send(peer_id=peerid,
                 keyboard=empty_keyboard,
                 message='test',
                 random_id=rd.randint(0, 10000000))
```

**Comment by edwardgushchin** [comment]
Если мне не изменяет память, клавиатуру нужно пропускать через json.dumps

**Comment by Jeeeeeeeeeja** [comment]
Я пробовал и через keyboard = VkKeyboard(), там если память не изменяет, уже само всё пропускается, такая же проблема

**Comment by edwardgushchin** [comment]
> Возможно это из-за ранее созданной клавиатуры, в которой я случайно поставил флаг "one_time"

Нет, проблема точно не в этом.
Сейчас пересмотрел свой код, вот пару советов:

1. Заменить двойные кавычки на одинарные
2. Переместить блок с кнопками после ключа 'one_time'
3. Все таки нужно keyboard оборачивать в json.dumps, это важно
4. На будущее, в payload модно засунуть все что угодно, туда json тоже дополнительно нужно оборачивать в json.dumps.

Попробуйте следующий код:

```
empty_keyboard = {'one_time': False, 'buttons': []}
vk.messages.send(peer_id=peerid,
    keyboard=json.dumps(empty_keyboard),
    message='test',
    random_id=rd.randint(0, 10000000)
)
```

> но как её тогда удалить?

Удалить никак, только отправить пустую клавиатуру.

**Comment by Jeeeeeeeeeja** [comment]
Ну я через longpoll работаю, а payload это для callback api вроде, сейчас попробую ваше решение и отпишу

**Comment by Jeeeeeeeeeja** [comment]
Да, надо было оборачивать. Спасибо огромное за помощь!
