### ISSUE TITLE
Проблема с запросом 'users.get'

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [python273/vk_api#36]
Выкидывается ошибка при исполнении запроса:

    with vk_api.VkRequestsPool(vk_session) as pool:
        user = pool.method('users.get',{"user_ids":[user_id]})

Ошибка:

    path/to/python2.7/site-packages/vk_api/vk_tools.py", line 247, in execute
        self.pool[i + x][2].update(response[x])
    ValueError: dictionary update sequence element #0 has length 3; 2 is required

То есть ожидается получения `dict'a`, а вместо него получаем `list` вида:

    [{u'first_name': First Name, u'last_name': Last Name, u'id': user_id}]

**Comment by python273** [comment]
Да, VkRequestsPool не работает с списками пока

**Comment by GrigoriyMikhalkin** [comment]
Планируется это как-то исправлять в мастере? Для себя, я, пока что, пофиксил это простой проверкой типов.

**Comment by python273** [comment]
Залил фикс в dev ветку (https://github.com/python273/vk_api/commit/852723995d35bbfa386db5273f3647a321cb8710), ответ будет записываться с ключем list

**Comment by python273** [comment]
Теперь можно поставить через pip
