### ISSUE TITLE
Фото по id

### ISSUE THREAD

**Issue by semen7907** [python273/vk_api#364]
Подскажите, как то можно получить ссылку на фото профиля человека по id?

**Comment by krutoypan3** [comment]
Отправляешь запрос users.get и указываешь что нужно получить фото. Примерно так: response=vk.users.get(user_ids=event.object.from_id, fields='photo_max')
Ответ будет примерно таким: [{"id": 267141542, "first_name": "\u0410\u0440\u0442\u0435\u043c", "last_name": "\u041e\u0433\u0430\u043d\u0435\u0441\u044f\u043d", "is_closed": false, "can_access_closed": true, "photo_max": "https://sun2-3.userapi.com/c206728/v206728023/10bdd3/V5VlawHewaM.jpg?ava=1"}]
В конце "photo_max" и есть твое фото
