### ISSUE TITLE
Как получить "недоступные товары"?

### ISSUE THREAD

**Issue by baffolobill** [python273/vk_api#37]
Привет,

Кто-нибудь знает, как получить товары из вкладки "недоступные товары"?

`market.get` возвращает только список продаваемых товаров. Если знать `id` товаров, то можно вызвать `market.getById`. Но в этом случае надо у себя хранить все добавленные товары.

Пробовал в двух группах, в одной - пользователь является администратором, в другой - владельцем. Видимо, проблема не в правах доступа, но именно на это и похоже.

**Comment by python273** [comment]
https://vk.com/support?act=new_api

**Comment by baffolobill** [comment]
Ответ поддержки Vk:

> Увы, неактивные товары можно получить только зная их id. Можете сохранять в отдельную базу при отключении.
