### ISSUE TITLE
Access denied: group docs are disabled

### ISSUE THREAD

**Issue by vovaekb** [python273/vk_api#371]
Мне нужно получить список статей в группе (метод docs.get). При создании объекта задаю логин, пароль и id приложения и права доступа к документам и группам (scope='groups, docs'). При выполнении запроса получаю ошибку:

```bash
vk_api.exceptions.ApiError: [15] Access denied: group docs are disabled
```

### Окружение

vk_api: 11.8.0

API: 5.120 (последняя)

### Пример

```python
vk_session = vk_api.VkApi(login='+79221275150', password='password', app_id=7550219, token='tT4khjSUdr8et8q1N0Ru', scope='groups, docs')
    vk_session.auth()
    vk = vk_session.get_api()

    group_id = 73519170
    posts_response = vk.docs.get(owner_id=-73519170)
```

**Comment by python273** [comment]
токен не нужно передавать

**Comment by vovaekb** [comment]
> токен не нужно передавать

спасибо за комментарий!

**Comment by python273** [comment]
так помогло? еще может `, ` нужно на `,` поменять, у вк когда-то где-то не принимало перечисление с пробелом

**Comment by vovaekb** [comment]
> так помогло? еще может `, ` нужно на `,` поменять, у вк когда-то где-то не принимало перечисление с пробелом

кажется в API Вконтакте нет метода для получения статей в сообществе. Решил классическим парсингом. Спасибо!
