### ISSUE TITLE
Неправильное ограничение на количество кнопок в строке клавиатуры

### ISSUE THREAD

**Issue by van-burgerberg** [python273/vk_api#374]
В документации написано, что ограничение на количество кнопок в строке клавиатуры равно 5, как для стандартного, так и для inline-отображения. А у вас в библиотеке стоит ограничение в 4 кнопки.

**_Максимальный размер стандартной клавиатуры — 5 × 10. Максимальное количество клавиш: 40._**

Об inline-отображении:
**_Её максимальный размер составит 5 × 6. Максимальное количество клавиш: 10._**

В вашем коде:
`if len(current_line) >= 4:
     raise ValueError('Max 4 buttons on a line')`

**Comment by python273** [comment]
Исправлено в 11.9.0
