### ISSUE TITLE
Есть ли шифрование в self.auth() ?

### ISSUE THREAD

**Issue by OlegKorn** [python273/vk_api#377]
_Есть ли шифрование в self.auth()? Можете сделать нечто вроде starttls() в SMTP?_

vk_api: _5.122_

### Пример

```python

vk_session = vk_api.VkApi(
      'num', 
      "pass"
)

vk_session.auth()
```

**Comment by python273** [comment]
Есть, взаимодействие с ВК происходит по протоколу [HTTPS](https://ru.wikipedia.org/wiki/HTTPS)
