### ISSUE TITLE
vk_api не может авторизироваться

### ISSUE THREAD

**Issue by pynista** [python273/vk_api#380]
При попытке воспользоватся vk_api получается ошибка
`vk_api.exceptions.AuthError: Unknown API auth error`

Дальнейшее изучение показывает наличие следующей ошибки:
`{'error': 'invalid_request', 'error_description': 'application is disabled'}`

В чем дело и как это исправить?

**Comment by LencoDigitexer** [comment]
Тоже самое. python 3.7.8

**Comment by python273** [comment]
Хм, ВК сам отключил дефолтное приложение, я обратно включил

**Comment by python273** [comment]
Вообще рекомендую себе отдельное [standalone приложение создавать](https://vk.com/editapp?act=create) и передавать через `app_id`
