### ISSUE TITLE
Проблемы с авторизацией

### ISSUE THREAD

**Issue by familiarstr4ng3r** [python273/vk_api#382]
Житель Украины, для авторизации использовал прокси. В случае входа через номер+пароль (даже верного пароля) получаю исключение vk_api.exceptions.BadPassword: Bad password. Пробовал вход через токен - vk_api.exceptions.ApiError: [29] Rate limit reached
Есть шансы на успех?

### Окружение

vk_api: 11.9.0

API: ? не использую ?

### Тестировал прокси на работоспособность вот так

```python
link = "https://api.vk.com/method/users.get?user_id=210700286&v=5.52"
response = requests.get(link, proxies = proxies)
jsonResponce = response.json()
print(jsonResponce)
```

### При указании верных данных все равно vk_api.exceptions.BadPassword: Bad password

```python
proxies = {
    'https': 'https://51.161.116.223:3128'
}

s = requests.Session()
s.proxies.update(proxies)

vk_session = vk_api.VkApi('номер', 'пароль', session=s)
vk_session.auth()

vk = vk_session.get_api()
```

### Авторизация используя токен vk_api.exceptions.ApiError: [29] Rate limit reached
```python
token = vk_api.VkApi(token=tokenData, session=s)
vk = token.get_api()
```

**Comment by username391** [comment]
Попробуй указывать прокси напрямую в сессию vk_api, а не передавая свою
my_proxies = {
    'https': 'https://51.161.116.223:3128'
}`

vk_session = vk_api.VkApi(email, password)
vk_session.http.proxies.update(my_proxies)
`

**Comment by python273** [comment]
Попробуй использовать socks5 прокси:

`$ pip install -U requests[socks]`
```python3
vk_session.http.proxies = {
    'http': 'socks5:// ...',
    'https': 'socks5:// ...'
}
```

Если не будет работать можешь отправить лог запросов и я посмотрю:
```python
vk_session = vk_api.VkApi('номер', 'пароль', session=s)
from vk_api.utils import enable_debug_mode
enable_debug_mode(vk_session, print_content=True)
vk_session.auth()
```
Из лога нужно убрать логины/пароли и поменять пароль в вк и отправить лог на vk_api@python273.pw файлом
