### ISSUE TITLE
Проблемы с двухфакторной аутентификацией 

### ISSUE THREAD

**Issue by Genomorf** [python273/vk_api#383]
Перестала работать двухфакторная аутентификация.
### Код хэндлера и auth 
```python
def auth_handler():
    key = input("Enter authentication code: ")
    remember_device = True
    return key, remember_device

vk_admin = vk_api.VkApi(login=login, password=password, auth_handler=auth_handler)
```
### Ошибка vk_api.exceptions.TwoFactorError: Two factor authentication failed

```python
Traceback (most recent call last):
  File "bot_logic_album.py", line 20, in <module>
    vk_admin.auth(token_only=True)
  File "/usr/local/lib/python3.6/dist-packages/vk_api/vk_api.py", line 175, in auth
    self._auth_token(reauth=reauth)
  File "/usr/local/lib/python3.6/dist-packages/vk_api/vk_api.py", line 226, in _auth_token
    self._vk_login()
  File "/usr/local/lib/python3.6/dist-packages/vk_api/vk_api.py", line 298, in _vk_login
    self._pass_twofactor(response)
  File "/usr/local/lib/python3.6/dist-packages/vk_api/vk_api.py", line 346, in _pass_twofactor
    raise TwoFactorError('Two factor authentication failed')
vk_api.exceptions.TwoFactorError: Two factor authentication failed
```

### Окружение
Версия vk-api: _Version: 11.9.0_
Python 3.7
IDE PyCharm

**Comment by python273** [comment]
Нужно затестить фикс:
` pip install https://github.com/python273/vk_api/archive/master.zip`

**Comment by vaga9938** [comment]
> Нужно затестить фикс:
> ` pip install https://github.com/python273/vk_api/archive/master.zip`

Спасибо фикс работает.

**Comment by Genomorf** [comment]
> 
> 
> > Нужно затестить фикс:
> > ` pip install https://github.com/python273/vk_api/archive/master.zip`
> 
> Спасибо фикс работает.

Прошу прощения, я видимо не до конца понял. Я прописал эту строчку как в PyCharm, так и в терминале, но ничего не изменилось. Надо что-то еще было сделать, кроме как просто выполнить команду?

**Comment by python273** [comment]
Исправлено в 11.9.1. Можно поставить как обычно `pip3 install -U vk_api`
