### ISSUE TITLE
Помогите решить ошибку с vkapi

### ISSUE THREAD

**Issue by MrKerya** [python273/vk_api#386]
![Screenshot_2020-12-14-19-05-46-99_4bbea2983defcba323392b274842bf2c](https://user-images.githubusercontent.com/69014277/102104878-bd04c400-3e3f-11eb-99e8-784384c0b7b4.jpg)

**Comment by nedogimov** [comment]
> ![Screenshot_2020-12-14-19-05-46-99_4bbea2983defcba323392b274842bf2c](https://user-images.githubusercontent.com/69014277/102104878-bd04c400-3e3f-11eb-99e8-784384c0b7b4.jpg)
> 

for event in longpoll.listen():
    ...

**Comment by MrKerya** [comment]
> > ![Screenshot_2020-12-14-19-05-46-99_4bbea2983defcba323392b274842bf2c](https://user-images.githubusercontent.com/69014277/102104878-bd04c400-3e3f-11eb-99e8-784384c0b7b4.jpg)
> 
> for event in longpoll.listen():
> ...

Там все есть, цикл есть этот, но почему не работает?
