### ISSUE TITLE
НУжна помощь

### ISSUE THREAD

**Issue by Stepan-coder** [python273/vk_api#389]
Здравствуйте, оставьте пожалучста хотябы 1 пример для работы с коллбек кнопками. Примеры из интернета не работают у event нет ни поля obj ни поля object. Соответственно я не могу получить ничего (из того, чего хотелось бы). Заранее спасибо
### Окружение

vk_api: _вставить версию_

API: _вставить версию_

### Пример

```python
_вставить код_
```

**Comment by FrozenYT** [comment]
Доброго времени суток, каким образом ты получаешь "event"?? Короче говоря:
Ты получаешь "event" из Long Poll API или Callback API?
Так же вопрос, ты хочешь создать VK бота на группы? Или на странице.
Проще говоря, если ты юзаешь LongPoll то какой? VkBotLongPoll или VkLongPoll?

Вот пример как правильно коннектиться к ГРУППЕ через токен.
```python
vk_session = vk_api.VkApi(token='*ТВОЙ_ТОКЕН*') 
longpoll = VkBotLongPoll(vk_session, *АЙДИ_ГРУППЫ*)
#Пример: longpoll = VkBotLongPoll(vk_session, 1) 
vk = vk_session.get_api()
```
Возможно у тебя не получается выцепить obj и object из-за того, что ты не отбираешь эвенты через цикл. Вот тебе пример отбора: 
```python
try:
	for event in longpoll.listen():
		if event.type == VkBotEventType.MESSAGE_NEW:
                	print(event.obj['message'])
                	print(event.object.message)
except:
        print('Ошибка')
```

**Comment by Stepan-coder** [comment]
Доброго времени суток! Спасибо за ответ! Я уже разобрался ( я читал документацию и использовал VKLongPool с группой) и по своей глупости пытался достать object из Event’a (теперь разобрался как этим пользоваться (уже месяца как 1.5-2)) Спасибо огромное за библиотеку, вы лучший(ая)!!!

  
>Вторник, 16 февраля 2021, 4:28 +05:00 от FrozenYT ***@***.***>:
> 
> 
>Доброго времени суток, каким образом ты получаешь "event"?? Короче говоря:
>Ты получаешь "event" из Long Poll API или Callback API?
>Так же вопрос, ты хочешь создать VK бота на группы? Или на странице.
>Проще говоря, если ты юзаешь LongPoll то какой? VkBotLongPoll или VkLongPoll?
>Вот пример как правильно коннектиться к ГРУППЕ через токен.
>vk_session = vk_api.VkApi(token='*ТВОЙ_ТОКЕН*') 
>longpoll = VkBotLongPoll(vk_session, *АЙДИ_ГРУППЫ*)
>#Пример: longpoll = VkBotLongPoll(vk_session, 1) 
>vk = vk_session.get_api()
>Возможно у тебя не получается выцепить obj и object из-за того, что ты не отбираешь эвенты через цикл. Вот тебе пример отбора:
>try:
>	for event in longpoll.listen():
>		if event.type == VkBotEventType.MESSAGE_NEW:
>                	print(event.obj['message'])
>                	print(event.object.message)
>except:
>        print('Ошибка')
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Степан Бородин
