### ISSUE TITLE
vk_api (VK PAY Bug or flaw)

### ISSUE THREAD

**Issue by FrozenYT** [python273/vk_api#392]
\~ENG\~:
Good day, I and my testers get an error:
"Unable to complete the operation. Please try again later." when trying to transfer money through VK PAY in the official VK application through the Android and IOS system..

I'm using keyboard callback: https://vk-api.readthedocs.io/en/latest/keyboard.html
I use the class: VkKeyboard, method: add_vkpay_button
Transferred data hash: "action=transfer-to-group&group_id=\*\*\*\*\*\*"
and tried to transfer data hash: "action=transfer-to-group&group_id=\*\*\*\*\*\*&aid=10"

When you click on the button through their application, on Android or on IOS, the transfer is made not to the group, but to yourself, thus the error "Unable to complete the operation. Please try later."

This problem with translating to oneself occurs ONLY through the application:
![yU7VjlgNLIA](https://user-images.githubusercontent.com/67555241/108002319-4d0de800-7000-11eb-9018-28df49d4eb90.jpg)

Everything works fine from any browser (PC, Android, IOS):
![zELc8H1ZMkw](https://user-images.githubusercontent.com/67555241/108002288-39fb1800-7000-11eb-9d35-e74e62856f49.jpg)

\~RUS\~:
Доброго времени суток, у меня и у моих тестеров вылезает ошибка:
"Невозможно совершить операцию. Попробуйте позже." при попытке перевода денег через VK PAY в официальном приложении ВКОНТАКТЕ через систему Android и IOS.

Использую keyboard callback: https://vk-api.readthedocs.io/en/latest/keyboard.html
Использую класс VkKeyboard метод add_vkpay_button
Передавал данные hash: "action=transfer-to-group&group_id=\*\*\*\*\*\*"
и пытался передавать данные hash: "action=transfer-to-group&group_id=\*\*\*\*\*\*&aid=10"

При нажатии на кнопку через их приложение что на Android что на IOS перевод совершается не в группу, а самому себе, тем самым возникает ошибка "Невозможно совершить операцию. Попробуйте позже."

Данная проблема с переводом самому себе возникает ТОЛЬКО через приложение: 
![yU7VjlgNLIA](https://user-images.githubusercontent.com/67555241/108002319-4d0de800-7000-11eb-9018-28df49d4eb90.jpg)

С любого браузера (PC, Android, IOS) всё работает отлично:
![zELc8H1ZMkw](https://user-images.githubusercontent.com/67555241/108002288-39fb1800-7000-11eb-9d35-e74e62856f49.jpg)
### Окружение

vk_api: 11.9.1

Long Poll API: 5.130

### Пример

```python
keyb = VkKeyboard(one_time=False, inline=True)
keyb.add_vkpay_button(hash='action=transfer-to-group&group_id=******&aid=10')
keyb.add_line()
keyb.add_callback_button('❌ ******', payload={"type": "canel_payment"})
# message_ediit its def message_edit(id=peer_id ,msgid = message_id , message = TEXT, keyboards = keyboard)
message_edit(id=fromid, msgid=msgid, message=f"******", keyboards=keyb.get_keyboard())
```

**Comment by python273** [comment]
Это лучше в поддержку ВК по апи написать и скинуть им вывод `keyb.get_keyboard()`

**Comment by FrozenYT** [comment]
Я туда тоже написал, подумал вдруг всё таки проблема в vk_api а не в самом виджете VK PAY.
