### ISSUE TITLE
Необработанные ошибки в VkTools.get_all

### ISSUE THREAD

**Issue by vadym-markov-ntnx** [python273/vk_api#397]
Необработанные ошибки в VkTools.get_all . Это явно 2 несвязанные между собой ишуи, просто проявились в одном и том же месте

### Окружение

vk_api: 11.8.0

API: 5.130

### Пример
```python
token = 'token'
vk_session = vk_api.VkApi(token=token, api_version='5.130')
vk = vk_session.get_api()
tools = vk_api.VkTools(vk_session)
group_id = -1980
wall = tools.get_all('wall.get', 100, {'owner_id': group_id}) 
# Get error 500
piece_of_wall = vk.wall.get(owner_id=group_id)
# piece_of_wall contains 100 posts

group_id = -40747355
wall = tools.get_all('wall.get', 100, {'owner_id': group_id})
# Get "Can't load items. Check access to requested items"
# ApiError: [13] Runtime error occurred during code invocation: response size is too big
piece_of_wall = vk.wall.get(owner_id=group_id)
# piece_of_wall contains 100 posts
```

**Comment by python273** [comment]
> Get error 500

Это на стороне сервера что-то

> Can't load items. Check access to requested items

VkTools не показывает оригинальную ошибку. В репозитории оно обновлено, можно потестить:
`pip install https://github.com/python273/vk_api/archive/master.zip`

> Runtime error occurred during code invocation: response size is too big

Бывает слишком большой ответ, можно уменьшать `max_count`

**Comment by vadym-markov-ntnx** [comment]
500 ошибка получается стабильно на определенном списке груп. Явно проблема с vkscript на стороне сервера, но как дебажить - непонятно
По второй ошибке попробую с мастером
