### ISSUE TITLE
Сразу после восстановления произошла ошибка при попытки авторизовать аккуант

### ISSUE THREAD

**Issue by CrazyNeron** [python273/vk_api#399]
_добавить описание_

### Окружение

vk_api: _вставить версию_

API: _вставить версию_

### Пример

```python
    acc["session"].auth(token_only=True)
  File "C:\Users\CrazyNeron\AppData\Local\Programs\Python\Python38-32\lib\site-p
ackages\vk_api\vk_api.py", line 173, in auth
    self._auth_token(reauth=reauth)
  File "C:\Users\CrazyNeron\AppData\Local\Programs\Python\Python38-32\lib\site-p
ackages\vk_api\vk_api.py", line 221, in _auth_token
    self._api_login()
  File "C:\Users\CrazyNeron\AppData\Local\Programs\Python\Python38-32\lib\site-p
ackages\vk_api\vk_api.py", line 450, in _api_login
    params = response.url.split('#', 1)[1].split('&')
IndexError: list index out of range
```

Вообщем поразберался я значит в чём дело и выяснил, что тут: File "C:\Users\CrazyNeron\AppData\Local\Programs\Python\Python38-32\lib\site-p
ackages\vk_api\vk_api.py", line 450, in _api_login
    params = response.url.split('#', 1)[1].split('&')

URL приходит ненормализованный, вместо нормальных симфолов типо такие: %23 %2F %2F%2F %3D0%26
поэтому возникает ошибка, просьба исправьте

**Comment by python273** [comment]
dup #398
