### ISSUE TITLE
Как передать дополнительные поля используя VkRequestsPool?

### ISSUE THREAD

**Issue by Firues** [python273/vk_api#40]
Разработчик творения отправил сюда:
https://github.com/python273/vk_api/blob/master/vk_api/vk_tools.py#L169
Но я испробовал все возможные варианты уже.  
Кто-нибудь может подсказать синтаксис, пожалуйста? 
Я пытаюсь получить fields - counters у метода users.get
Otherwise I'll hang myself. Really.

**Comment by python273** [comment]
> :param default_values: одинаковые значения для запросов

Туда добавляешь параметры, которые нужно передать во всех запросах
