### ISSUE TITLE
Проблема с получением больше 3 изображений

### ISSUE THREAD

**Issue by OlivkaFromHell** [python273/vk_api#404]
Если в сообщение из беседы больше трех изображений, то в event отображается только одно

Бот работает в беседе(не созданной группой) с ключом доступа сообщества
```
vk_session = vk_api.VkApi(token=token) 
vk = vk_session.get_api()

longpoll = VkBotLongPoll(vk_session, groupId)

for event in longpoll.listen():
    if event.type == VkBotEventType.MESSAGE_NEW:
        if event.from_chat: # если сообщение не пустое
            print(event)
```

vk_api: 11.9.3 (на 11.9.1, 11.8.0, 11.7.0 та же проблема)

`class 'vk_api.bot_longpoll.VkBotMessageEvent'>({'type': 'message_new', 'object': {'message': {'date': 1620386336, 'from_id': 136833224, 'id': 0, 'out': 0, 'peer_id': 2000000001, 'text': '', 'conversation_message_id': 1441, 'fwd_messages': [], 'important': False, 'random_id': 0, 'attachments': [{'type': 'photo', 'photo': {'album_id': -3, 'date': 1620386331, 'id': 457258422, 'owner_id': 136833224, 'has_tags': False, 'access_key': 'bcb3f12564cb19d823', 'sizes': [{'height': 75, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=75x75&quality=96&sign=182c36edeee6b04dcb5aa57f22818260&c_uniq_tag=HvWh5_Hq1AfedOmy45Sf4lZkN5ii4iDx5mdzWJjntQs&type=album', 'type': 's', 'width': 75}, {'height': 130, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=130x130&quality=96&sign=1e7cab0ae6fa9c7393372ada239a148e&c_uniq_tag=dHiY_cQbRRVrI5nI3JY90YnB9mQpU6TTtPZpACKMtgg&type=album', 'type': 'm', 'width': 130}, {'height': 604, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=604x604&quality=96&sign=d715dbff98019819d00c4146f7e5221f&c_uniq_tag=b4isUDdadi5reTBn--55Tu3ZuTicx-1jvSrEQtH-3D8&type=album', 'type': 'x', 'width': 604}, {'height': 807, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=807x807&quality=96&sign=65d2994a96ca1fd3df025cc384fe5393&c_uniq_tag=DjMlvyzrGfR2xWGj-4IaHaFRQRv2-aa-rO0Zcr-zWL8&type=album', 'type': 'y', 'width': 807}, {'height': 1080, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=1280x1280&quality=96&sign=80dedce6094c337769e170218eb0f092&c_uniq_tag=qiW2SkDCcXxhbdpvWz-ShSf7RaZCMYb5KsoD4JGMqxM&type=album', 'type': 'z', 'width': 1080}, {'height': 2160, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=2160x2160&quality=96&sign=a2141bf66e79c2ded64772c441e48001&c_uniq_tag=7gMVlr95hgsFtB2b7QfMzaxXGLnS_i0Tt0V0gq9MxfY&type=album', 'type': 'w', 'width': 2160}, {'height': 130, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=130x130&quality=96&sign=1e7cab0ae6fa9c7393372ada239a148e&c_uniq_tag=dHiY_cQbRRVrI5nI3JY90YnB9mQpU6TTtPZpACKMtgg&type=album', 'type': 'o', 'width': 130}, {'height': 200, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=200x200&quality=96&sign=d07e8f8f12fa731e2cf676e2fe1c459b&c_uniq_tag=MHq4Bn3Z9My9MkOcsHClsi4dvf_M1NUDK2f0H3x5bHY&type=album', 'type': 'p', 'width': 200}, {'height': 320, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=320x320&quality=96&sign=d1b0710a974e7242f0ffe39f928a2189&c_uniq_tag=-pT8pz1t3m30s9Qc5pKqltb-BwnW97gmzoEnlkVmdHo&type=album', 'type': 'q', 'width': 320}, {'height': 510, 'url': 'https://sun9-34.userapi.com/impg/4PhMicCnQc9GtAyuIwkyv2G2RojoMMtYlFdRoQ/HIboVaICexI.jpg?size=510x510&quality=96&sign=6fef82af6883fd0a0964d9ec854d7b00&c_uniq_tag=7kQIOWpMzCxsvRUBSrnSWNphLh5U2LJEzEIw2eNJo6g&type=album', 'type': 'r', 'width': 510}], 'text': ''}}], 'is_hidden': False, 'is_cropped': True}, 'client_info': {'button_actions': ['text', 'vkpay', 'open_app', 'location', 'open_link', 'callback', 'intent_subscribe', 'intent_unsubscribe'], 'keyboard': True, 'inline_keyboard': True, 'carousel': False, 'lang_id': 0}}, 'group_id': 202528897, 'event_id': 'b86451a7838d0873c7d868c2dfc834c6a96a4372'})>`

Если кол-во фотографий в сообщении 3 и меньше, то все нормально:

`class 'vk_api.bot_longpoll.VkBotMessageEvent'>({'type': 'message_new', 'object': {'message': {'date': 1620386690, 'from_id': 136833224, 'id': 0, 'out': 0, 'peer_id': 2000000001, 'text': '', 'conversation_message_id': 1443, 'fwd_messages': [], 'important': False, 'random_id': 0, 'attachments': [{'type': 'photo', 'photo': {'album_id': -3, 'date': 1620386686, 'id': 457258429, 'owner_id': 136833224, 'has_tags': False, 'access_key': '0f0cd989aa51553576', 'sizes': [{'height': 50, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=75x50&quality=96&sign=30c786770f873f467f0f133e3bd8468f&c_uniq_tag=BtArwbLX3TwrbjnyxAmOVazNKI3LoUEW4dXxKuBZ5ng&type=album', 'type': 's', 'width': 75}, {'height': 87, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=130x87&quality=96&sign=16d2538042a6cf6ca87ec81595d318c8&c_uniq_tag=vew7TrESz_YTWGqyqX5rpInGICo9d1KJ5GunsRUeqP0&type=album', 'type': 'm', 'width': 130}, {'height': 403, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=604x403&quality=96&sign=a96e3f55ce402fb000a487c78917f47a&c_uniq_tag=DmXv83orzUEKKlQDZwgU_PM2sUtEyGq5Iv6NyEPTh38&type=album', 'type': 'x', 'width': 604}, {'height': 539, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=807x539&quality=96&sign=4caa1fbe1b3a96d462558119f3d552bb&c_uniq_tag=Qre0cuotAGYKXlr38rxuGuVTvVQuZhkeuE-1VKns3Y0&type=album', 'type': 'y', 'width': 807}, {'height': 855, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=1280x855&quality=96&sign=6560cf4228c97cfa110a65f2975b3c59&c_uniq_tag=SRuWDrNbJ5kHbE1vvJ_IHL0m-3ciC7Z6R6-ziZdvLok&type=album', 'type': 'z', 'width': 1280}, {'height': 1710, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=2560x1710&quality=96&sign=c320c8193cfc92dae001dd171b48403d&c_uniq_tag=9TvJwgRdbI9YZaI5vGhJ63jwTjLH7YgKkrM-DyVfSJ8&type=album', 'type': 'w', 'width': 2560}, {'height': 87, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=130x87&quality=96&sign=16d2538042a6cf6ca87ec81595d318c8&c_uniq_tag=vew7TrESz_YTWGqyqX5rpInGICo9d1KJ5GunsRUeqP0&type=album', 'type': 'o', 'width': 130}, {'height': 134, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=200x134&quality=96&sign=be3d7086b5391d377fb3c44347965d66&c_uniq_tag=JnNEyby8a03CzJOXwtJVqEqZe-07_adHDgkfHWwPiOw&type=album', 'type': 'p', 'width': 200}, {'height': 214, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=320x214&quality=96&sign=0e01813b754cd00f677626884eab98c6&c_uniq_tag=2LjKygomtDrJoWyVasEzi8pakVHIQAwPIKnHi44Fyys&type=album', 'type': 'q', 'width': 320}, {'height': 341, 'url': 'https://sun9-41.userapi.com/impg/LaS2zJVoQ2N7m3jVVeGodSAoV7cDGauXeuQgIQ/cz6jMdpENJk.jpg?size=510x341&quality=96&sign=339865e28bc54a6942208fa0ba8ad134&c_uniq_tag=9TFjQseMUDwn1jitvLXOnM3W-9OBJjz5JUo2XIM94rw&type=album', 'type': 'r', 'width': 510}], 'text': ''}}, {'type': 'photo', 'photo': {'album_id': -3, 'date': 1620386687, 'id': 457258430, 'owner_id': 136833224, 'has_tags': False, 'access_key': '676cbe04cac3475108', 'sizes': [{'height': 50, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=75x50&quality=96&sign=f7bf14484f77bb90bf432e6e0f8ffcc0&c_uniq_tag=uRSutYz3tIkpFiDHE2t-CAvE2GL32GA0d4euk13Wmzw&type=album', 'type': 's', 'width': 75}, {'height': 87, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=130x87&quality=96&sign=c70353a58f6e73cfc2a955bd582cd4ee&c_uniq_tag=ua-eggrTIAIABhYC_UjkhWs2ZmjHpAOqB4M6XEL5KzE&type=album', 'type': 'm', 'width': 130}, {'height': 403, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=604x403&quality=96&sign=7c8ad83fe756220c5a40d52ff103da01&c_uniq_tag=Jk73530bi900pTy_meTA0cakCYY_k8nDDGKfr7BljVs&type=album', 'type': 'x', 'width': 604}, {'height': 539, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=807x539&quality=96&sign=8305d8aebb2116d5dfaa6e585ca539a0&c_uniq_tag=S3xXbq72kPnYx7EOvWVKAMS02ehP4sRuZOV9HZyorWU&type=album', 'type': 'y', 'width': 807}, {'height': 855, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=1280x855&quality=96&sign=cc8802800d8ca39db02357038f0134a6&c_uniq_tag=9yV62jwyadKTe4AHeu9DgD7h4fQgbTyS2b4wOoSMGFo&type=album', 'type': 'z', 'width': 1280}, {'height': 1710, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=2560x1710&quality=96&sign=5969510017c94818a002bc767f6cd6be&c_uniq_tag=Xsp-N5Xd-R1xtA523Hcj42C_DwE39QAEatemIh7ybuo&type=album', 'type': 'w', 'width': 2560}, {'height': 87, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=130x87&quality=96&sign=c70353a58f6e73cfc2a955bd582cd4ee&c_uniq_tag=ua-eggrTIAIABhYC_UjkhWs2ZmjHpAOqB4M6XEL5KzE&type=album', 'type': 'o', 'width': 130}, {'height': 134, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=200x134&quality=96&sign=e6e66972800d0055bf7b8743eb01d074&c_uniq_tag=dNEiuAv0c3Ff1U6m3OiMkvn6Mb8vicl44LQDC5CTh0U&type=album', 'type': 'p', 'width': 200}, {'height': 214, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=320x214&quality=96&sign=405cc6496a92fc83310013aac61fc250&c_uniq_tag=HAft0GbD-qrphV_w3MjJ_SvCSCFLsOTc0s7f13iSTkE&type=album', 'type': 'q', 'width': 320}, {'height': 341, 'url': 'https://sun9-24.userapi.com/impg/NkvuJxsscDaYU7rKr1K1kLyNotiX-BcoOn3ytA/x1C-TyOyqM8.jpg?size=510x341&quality=96&sign=8db448dcc7bfe7d4e2609323277941b0&c_uniq_tag=OieQzd386G5_43ank-9ZJ4LNGt6atQyt8Yp7_RNyX6E&type=album', 'type': 'r', 'width': 510}], 'text': ''}}, {'type': 'photo', 'photo': {'album_id': -3, 'date': 1620386688, 'id': 457258431, 'owner_id': 136833224, 'has_tags': False, 'access_key': '593bc5ed035d03af41', 'sizes': [{'height': 50, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=75x50&quality=96&sign=d9d565ff575d5576a38ccc46a8ea2924&c_uniq_tag=fHtOb7FBFkTHIn0XKnyYKV04IwqbG5YklzrnzcxIUrY&type=album', 'type': 's', 'width': 75}, {'height': 87, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=130x87&quality=96&sign=8b6c2b89eb63fc219825bfb7d5a92d23&c_uniq_tag=cHdJTeMu2r-RCpcqhAUc6Yh-SluFRGpxtEqm5-0r1ZU&type=album', 'type': 'm', 'width': 130}, {'height': 403, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=604x403&quality=96&sign=bceb423b5f464ffba3309554297be8fa&c_uniq_tag=UKeiKeNI9aSMFMZIoIEU4cmAoD6WKdNc9PyPyd9qBiI&type=album', 'type': 'x', 'width': 604}, {'height': 539, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=807x539&quality=96&sign=d9563d050baf9bff04238555aa90df47&c_uniq_tag=AG3QTXwPHve-7lc2zQiMKFVFku351KbNNCaT1BFPuYg&type=album', 'type': 'y', 'width': 807}, {'height': 855, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=1280x855&quality=96&sign=c813aaa3ce88bae77aef6dd520fca2b6&c_uniq_tag=ewh3Zc7DMoXp97B7fS5vPFTtL-mKZBR9dt8fJbupElU&type=album', 'type': 'z', 'width': 1280}, {'height': 1710, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=2560x1710&quality=96&sign=228596087c932124543fe05ce990a862&c_uniq_tag=CUHTpA2k5NMDTow1tVuI8mzHd7KXqh4uoRy9wJSMzOQ&type=album', 'type': 'w', 'width': 2560}, {'height': 87, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=130x87&quality=96&sign=8b6c2b89eb63fc219825bfb7d5a92d23&c_uniq_tag=cHdJTeMu2r-RCpcqhAUc6Yh-SluFRGpxtEqm5-0r1ZU&type=album', 'type': 'o', 'width': 130}, {'height': 134, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=200x134&quality=96&sign=bad76f12ce151e326a6727c709ee2d2e&c_uniq_tag=u239SNodE0eOmI2sgwOqxmGWJTGH6R3JsvGD33nAE7g&type=album', 'type': 'p', 'width': 200}, {'height': 214, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=320x214&quality=96&sign=87e959fed4427c717175722939abab96&c_uniq_tag=XpzI9JCAyzlBfCPIeEeuSZkyyKSAF1TFrjWch_sagCs&type=album', 'type': 'q', 'width': 320}, {'height': 341, 'url': 'https://sun9-6.userapi.com/impg/LuI0-Tg_uL9t1u-iDEAqRnR3Gw1pKRq_aoHHdg/VUhjPoW8flE.jpg?size=510x341&quality=96&sign=e554cb1acb3176bcdc6e36f4c7097149&c_uniq_tag=Egg3rMtYvw5pqm_OoEuqGEASve_dWs4dQJfJZve6was&type=album', 'type': 'r', 'width': 510}], 'text': ''}}], 'is_hidden': False}, 'client_info': {'button_actions': ['text', 'vkpay', 'open_app', 'location', 'open_link', 'callback', 'intent_subscribe', 'intent_unsubscribe'], 'keyboard': True, 'inline_keyboard': True, 'carousel': False, 'lang_id': 0}}, 'group_id': 202528897, 'event_id': '7014de99fe78bd8d8117a2a3fa914e8db3da8e22'})>`

**Comment by python273** [comment]
Это лучше в поддержке ВК спрашивать

**Comment by monosans** [comment]
Столкнулся с этой же проблемой.

Ответ поддержки:
```
Если все вложения не вмещаются в событие, они будут урезаны только до одного. В таком случае полную информацию о сообщении нужно дополнительно получать через messages.getById.

Чтобы определить, обрезано ли событие, нужно проверить параметр is_cropped. Он возвращается для версий API не ниже 5.103.
```
