### ISSUE TITLE
vk_api.exceptions.ApiError: [29] Rate limit reached

### ISSUE THREAD

**Issue by NikitaYezhov** [python273/vk_api#411]
у меня ошибка в строке `vk_session.method('status.set', {'text' : output})`, она у меня одна на весь код выводит что-то, не считая авторизации, я не знаю как эту проблему решить

**Comment by python273** [comment]
https://vk.com/dev.php?method=errors
> 29 | Достигнут количественный лимит на вызов метода

**Comment by NikitaYezhov** [comment]
А какой он у status.set?
Там есть лишь:
newsfeed.search — 1000 вызовов в сутки;
wall.search — 1000 вызовов в сутки;
wall.get — 5000 вызовов в сутки.

**Comment by Romz24** [comment]
Сейчас заметил что перестал работать метод `photos.get`, возвращает ошибку `Rate limit reached`.

Самое забавное, что я его вообще до этого не вызывал. Первый же вызов, и сразу ошибка что я уперся в лимит...

**Comment by DimaAnime** [comment]
Хотел получить общие группы участников, подписанных на определённую группу. На входе программа принимает id группы, на выходе список общих групп.  Сначала использую метод "groups.getMembers" через execute, получаю 25000 участников за раз, затем метод "groups.get" для каждого участника, также через execute по 25 участников можно прогнать за раз. Примерно после 5-6 тысяч участников получаю ошибку "[29] Rate limit reached". Я так понимаю единственный способ это обойти использовать несколько аккаунтов.
Однако есть сайт (https://vk.barkov.net/auditory.aspx), который делает выше описанную работу используя мой аккаунт вк, и у него таких ограничений нет, даже после того как в моей программе также использующей мой аккаунт, уже даже 1 раз не даёт сделать. Возможно ли что на данном сайте используют запрос с разных аккаунтов, тагда откуда у них их столько, или есть другой способ, как такое можно провернуть? Просто сменить токкен уже пробовал, похоже данная ошибка связанна именно с вк аккаунтом.
