### ISSUE TITLE
Нерабочий код из документации

### ISSUE THREAD

**Issue by Pro100rus32** [python273/vk_api#417]
Последняя версия библиотеки. Я взял код, вот:

```
import vk_api

vk_session = vk_api.VkApi('+71234567890', 'mypassword') #понятное дело я ввёл сюда верные данные от аккаунта
vk_session.auth()

vk = vk_session.get_api()

print(vk.wall.post(message='Hello world!'))
```

Ошибка:

`vk_api.exceptions.ApiError: [5] User authorization failed: no access_token passed.`

**Comment by python273** [comment]
У меня работает. Могу посмотреть лог запросов:

```python
import vk_api
from vk_api.utils import enable_debug_mode

def auth_handler():
    return input("Enter authentication code: "), True

vk_session = vk_api.VkApi('+123', 'asd', auth_handler=auth_handler)
enable_debug_mode(vk_session, print_content=True)

vk_session.auth()
vk_session.method('users.get')
```

Перед запуском поменять пароль в ВК, запустить, из лога убрать логины/пароли, поменять пароль еще раз и отправить лог на vk_api@python273.pw файлом

**Comment by Pro100rus32** [comment]
> У меня работает. Могу посмотреть лог запросов:
> 
> ```python
> import vk_api
> from vk_api.utils import enable_debug_mode
> 
> def auth_handler():
>     return input("Enter authentication code: "), True
> 
> vk_session = vk_api.VkApi('+123', 'asd', auth_handler=auth_handler)
> enable_debug_mode(vk_session, print_content=True)
> 
> vk_session.auth()
> vk_session.method('users.get')
> ```
> 
> Перед запуском поменять пароль в ВК, запустить, из лога убрать логины/пароли, поменять пароль еще раз и отправить лог на [vk_api@python273.pw](mailto:vk_api@python273.pw) файлом

Этот код не работает, нужен токен для этого `vk.wall.post(message='Hello world!')`

Примерно вот так:

`vk_session = vk_api.VkApi(login, password,auth_handler=auth_handler, token=access_token)`

Спасибо за ответ)

**Comment by python273** [comment]
> Этот код не работает

Какой этот?

> нужен токен для 

Если переданы логин с паролем, то токен должен быть получен при вызове `vk_session.auth()`. Можно без логина с паролем напрямую передавать токен, но и вызывать `auth` не нужно

**Comment by Pro100rus32** [comment]
> Какой этот?

Который в документации. Для работы, нужно передавать ещё и токен. Я не знаю, нужно ли так только для аккаунта с двухфакторкой, или для всех.

Дублирую ошибку:
`vk_api.exceptions.ApiError: [5] User authorization failed: no access_token passed.`
