### ISSUE TITLE
Не создаётся конфиг файл json после удаления.

### ISSUE THREAD

**Issue by Pro100rus32** [python273/vk_api#418]
Я зашёл в аккаунт с двухфакторной аутентификацией.
У меня появился .json файл, и я его удалил, что бы создать его по другому пути

```
def auth_handler():
    key = input("Enter authentication code: ")
    remember_device = True #но как бы я его не менял, json больше не создаётся.
    return key, remember_device
```

Я хотел изменить путь, по которому создаётся этот файл, но он не создаётся больше xD

Пытался поменять среду, перезагружал комп, удалял перетаскивал скрипт в другую папку - бесполезно. Хоть файл должен создаваться по пути относительно скрипту.

**Comment by python273** [comment]
Без кода не знаю что происходит. `.json` файл создается при вызове `auth`, с двухфакторной аутентификацией он не связан. `remember_device` вроде вообще сломан

**Comment by Pro100rus32** [comment]
Странно, но это исправило проблему.
```
vk_session = vk_api.VkApi(login, password,auth_handler=auth_handler)
vk_session.auth(reauth=True)
```
