### ISSUE TITLE
Передача аргументов в handler

### ISSUE THREAD

**Issue by Pro100rus32** [python273/vk_api#419]
Как я могу добавить к примеру один аргумент к функции, в хендлере капчи:

` vk_api.VkApi(login, password,auth_handler=auth_handler(message), captcha_handler=captcha_handler)`
 
 Там передаётся сама captcha, но добавить другой аргумент я не могу.
 
 Пытался и так:
 `captcha_handler=captcha_handler(message, captcha)`
 
 И так:
` captcha_handler=captcha_handler(message)`
  
  Но увы, не работает.

**Comment by python273** [comment]
```python
def make_handler(qwe):
    def handler(...):
        ...
    return handler
```
или
```python
class FancyHandler:
    def __init__(self, qwe):
        self.qwe = qwe
    def __call__(self, ....):
        ....

```

**Comment by NeuralAIM** [comment]
Немного не понял, прошу прощение. Можете показать на этом примере:
```
def captcha_handler(captcha, msg):
    # тут типо код
    pass


vk_api.VkApi(login, password, captcha_handler=captcha_handler(msg)
```

Мне нужно передать `msg`, не потеряв `captcha`

**Comment by Pro100rus32** [comment]
Немного не понял, прошу прощение. Можете показать на этом примере:

```
def captcha_handler(captcha, msg):
    # тут типо код
    pass


vk_api.VkApi(login, password, captcha_handler=captcha_handler(msg)
```
Мне нужно передать `msg`, не потеряв `captcha`'у
