### ISSUE TITLE
Ошибка при использовании VkRequestsPool

### ISSUE THREAD

**Issue by VolanDeVovan** [python273/vk_api#42]
with vk_api.VkRequestsPool(session) as pool:
    pool.method('messages.addChatUser', {'chat_id': *, 'user_id': *** })
    pool.method('messages.removeChatUser', {'chat_id': *, 'user_id': ***}) 
При использовании такого кода после исполнения появляется ошибка

> Start while
> Traceback (most recent call last):
>   File "vkflood.py", line 49, in <module>
>     vkFlood(session)
>   File "vkflood.py", line 44, in vkFlood
>     pool.method('messages.removeChatUser', {'chat_id': 2, 'user_id': 372675505}) 
>   File "/usr/lib/python3.4/site-packages/vk_api/vk_tools.py", line 150, in __exit__
>     self.execute()
>   File "/usr/lib/python3.4/site-packages/vk_api/vk_tools.py", line 285, in execute
>     self.pool[i + x][2].update(response[x])
> TypeError: 'int' object is not iterable
>

**Comment by Firues** [comment]
Так у вас же написано: TypeError: 'int' object is not iterable

**Comment by VolanDeVovan** [comment]
а где ошибка в коде? Все верно же

**Comment by VolanDeVovan** [comment]
start while это если что обычный принт перед кодом. Там цикла нет . Только with

**Comment by python273** [comment]
Да, сейчас есть проблема с пуллом, он не может возвращать все типы. Я пофикшу, но это ломает обратную совместимость

**Comment by python273** [comment]
@VolanDeVovan залил апдейт в dev ветку, можно потестить, но нужно будет пофиксить скрипт

Обновленный пример:
https://github.com/python273/vk_api/blob/dev/examples/requests_pool.py

**Comment by python273** [comment]
Пофикшено в версии 8.0
