### ISSUE TITLE
Не удаётся залогиниться

### ISSUE THREAD

**Issue by MarSoft** [python273/vk_api#43]
Был скрипт, написанный с использованием этой библиотеки. Сегодня после долгого перерыва попытался запустить, получил ошибку - Bad Password или типа того.
Оказалось, что мой старый пароль по каким-то причинам недействителен. Поменял пароль, указал новый в скрипте. Теперь получаю такую ошибку:
```
Traceback (most recent call last):
  File "./vkaudio.py", line 14, in <module>
    api.authorization()
  File "/home/mars/.local/lib/python3.5/site-packages/vk_api/vk_api.py", line 121, in authorization
    self.vk_login()
  File "/home/mars/.local/lib/python3.5/site-packages/vk_api/vk_api.py", line 188, in vk_login
    raise AuthorizationError('Unknown error. Please send bugreport.')
vk_api.vk_api.AuthorizationError: Unknown error. Please send bugreport.
```
Как и было запрошено, отправляю багрепорт.
Ошибка была выброшена при анализе response.url; вот его полное значение: `https://vk.com/login?act=slogin&role=fast&redirect=1&to=&s=1&__q_hash=b191745b2f299190b7575eeccd6e02ce`

**Comment by MarSoft** [comment]
Версия модуля стояла `7.2`. Обновился до `7.4` — то же самое.

**Comment by python273** [comment]
Модуль явно не обновлен, возможно ты обновил его для python2, а запускаешь в python3
