### ISSUE TITLE
При использовании блокируется аккаунт вк.

### ISSUE THREAD

**Issue by ChunaevAnton** [python273/vk_api#433]
Вылетает вот такая ошибка - Unknown error (AUTH; no sid). Please send bugreport to GitHub or vk_api@python273.pw . После этого попытался с браузера зайти на страничку вк и оказалось что из за подозрительной активности страницы аккаунт временно ограничили... Помогите исправить ошибку пожалуйста.

**Comment by python273** [comment]
#432
