### ISSUE TITLE
При использовании блокируется страничка вк.

### ISSUE THREAD

**Issue by ChunaevAnton** [python273/vk_api#435]
При использовании блокируется страничка вк. Вот код как у меня: 
 login, password = '*****', '****'
    vk_session = vk_api.VkApi(login, password)

    try:
        vk_session.auth(token_only=True)
    except vk_api.AuthError as error_msg:
        print(error_msg)
        return

**Comment by ChunaevAnton** [comment]
Может я его не так прописываю?

**Comment by Alex0007** [comment]
Подтверждаю, начали блокировать страницу со вчерашнего дня.

**Comment by python273** [comment]
#432
