### ISSUE TITLE
Ошибки в библиотеке 

### ISSUE THREAD

**Issue by SPRAVEDLIVO** [python273/vk_api#439]
Проверка авторизации по токену неисправна.
При инициализации объекта VkApi с невалидным токеном, не выводится никакая ошибка

### Окружение

vk_api: 11.9.7

API: 5.92

### Пример

```python
a = VkApi(token="invalidtoken").get_api() # no errrors at initialisation
```

**Comment by drygdryg** [comment]
Мне кажется, это не ошибка, а нормальное поведение библиотеки. Токен не валидируется при создании объекта `VkApi`. Если вы вызовете какой-либо метод с неверным токеном, то получите ошибку API.
