### ISSUE TITLE
Не работает авторизация по логину и паролю

### ISSUE THREAD

**Issue by wex335** [python273/vk_api#451]
_Вчера утром все было хорошо, а сегодня перестала работать авторизация. Библиотеку использую для получения куков вк для дальнейшей работы с ними. Часть ошибки:
Traceback (most recent call last):
 File "/home/wex/vkparser/test.py", line 11, in <module>
 print(s.auth(reauth=True))
 File "/usr/local/lib/python3.9/dist-packages/vk_api/vk_api.py", line 184, in auth
 self._auth_cookies(reauth=reauth)
 File "/usr/local/lib/python3.9/dist-packages/vk_api/vk_api.py", line 193, in _auth_cookies
 self._vk_login()
 File "/usr/local/lib/python3.9/dist-packages/vk_api/vk_api.py", line 330, in _vk_login
 raise AuthError(get_unknown_exc_str('AUTH; no sid'))
vk_api.exceptions.AuthError: Unknown error (AUTH; no sid). Please send a bugreport to GitHub: https://github.com/python273/vk_api/issues_

### Пример

```python
   S = VkApi(login="", password="")
   S.auth()
```

**Comment by alex-bul** [comment]
Аналогичная проблема. Судя по всему это зависит от айпи устройства, т.к. на одном ПК авторизация проходит успешно, а на другом нет. Правда при использовании прокси не работает. Возвращается 7 код ошибки ( parent.onLoginFailed(7, {"email":"","expire":1}) ), что означает этот в документации не указано

**Comment by alex-bul** [comment]
Решил проблему для себя с помощью [этого способа](https://github.com/python273/vk_api/issues/432#issuecomment-974808408). Сработало с прокси.

**Comment by StepanovK** [comment]
А в чем способ? Добавить `User-agent` мне не помогло. Человек пишет про удаление` vk_config.v2.json`, но я не понял, в какой момент его нужно удалять (в коде он этого не делает). Руками перед запуском - не сработало

**Comment by mewforest** [comment]
А почему закрыт тикет? Та же проблема при авторизации нового аккаунта возникла сегодня.
