### ISSUE TITLE
AUTH; no sid Ошибка при авторизации

### ISSUE THREAD

**Issue by scpstories** [python273/vk_api#455]
```py

import vk_api

vk_session = vk_api.VkApi(login=Login, password=Pass)
vk_session.auth(token_only=True)
```
Пишет ошибку: Unknown error (AUTH; no sid). Please send a bugreport to GitHub:

**Comment by bettapy** [comment]
![изображение_2022-04-11_231141075](https://user-images.githubusercontent.com/94528452/162784163-4936cb44-db83-41a1-b2bd-c7b4498661cc.png)
