### ISSUE TITLE
API auth error (no login cookies)

### ISSUE THREAD

**Issue by Nikita2305** [python273/vk_api#456]
При попытке авторизоваться по логину и паролю получаю AuthError('API auth error (no login cookies)'). Взял способ авторизации из #432. Код работал до вчерашнего дня.

Чем это обусловлено?

### Окружение

vk_api: 11.9.6

### Пример

```python
os.system("rm ./" + VK_CONFIG_PATH)
self.vk_session = vk_api.VkApi(
        self.login, self.password,
        captcha_handler=captcha_handler,
        config_filename=VK_CONFIG_PATH
)
self.vk_session.http.headers['User-agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0'
self.vk_session.auth(token_only=True)
```

**Comment by prokofyev** [comment]
Появилась та же проблема. Что-то изменилось на стороне VK, видимо.

**Comment by adamakalshchikov** [comment]
[Так](https://github.com/python273/vk_api/pull/457) работает

**Comment by adamakalshchikov** [comment]
[Убрал](https://github.com/python273/vk_api/pull/457) проверку наличия куки 'l', и заработало

**Comment by sideloading** [comment]
Does this fix still? I am getting the same error even after installing PR #457
Python 3.6.6

**Comment by Nikita2305** [comment]
> Does this fix still?

It worked a few days before, but now I'm getting the same.
