### ISSUE TITLE
Невозможность авторизации (CookieConflictError)

### ISSUE THREAD

**Issue by Yura2108** [python273/vk_api#458]
При попытке авторизоваться через логин/пароль ловлю ошибку: requests.cookies.CookieConflictError: There are multiple cookies with name, 'remixsid'. До этого была проблема с куками #456, исправил, теперь эта

### Окружение

vk_api: 11.9.7 (latest)

### Пример
```
vk_session = vk_api.VkApi(login, password, auth_handler=_auth_handler)
vk_session.http.headers['User-agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0'
vk_session.auth()
```

**Comment by MJaroslav** [comment]
Раз закрыл, то решение бы показал.
