### ISSUE TITLE
Ошибка авторизации 

### ISSUE THREAD

**Issue by IBM51OO** [python273/vk_api#459]
Использую стандартный пример из авторизации 
import vk_api

vk_session = vk_api.VkApi('+7999999999, '*****')
vk_session.auth()

vk = vk_session.get_api()

print(vk.wall.post(message='Hello world!'))

но выдает ошибку 

in _api_login
raise AuthError('API auth error (no login cookies)')
vk_api.exceptions.AuthError: API auth error (no login cookies)

**Comment by StepanovK** [comment]
Аналогичная проблема :(
Сравнительно недавно появилась. Авторизация по токену работает. Похоже, контакт что-то поменял

**Comment by waslost0** [comment]
Гляньте  [457 PR](https://github.com/python273/vk_api/pull/457)
