### ISSUE TITLE
Сохраненная сессия не подтягивается при перезапуске

### ISSUE THREAD

**Issue by DanyaSWorlD** [python273/vk_api#470]
При каждом перезапуске скрипта требуется ввод 2FA начиная с 16.07.2022. 
До этого скрипт работал по месяцу, прежде чем попросить ввести код 2FA еще раз.

### Окружение

vk_api: 11.9.6 / 11.9.9. (Обновление до последней версии не помогло).

API: 5.92

### Пример

```
        # Init Client
        self.vk = vk_api.VkApi(
            self.vk_login, self.vk_password,
            scope=65536 | 262144 | 8192 | 131072 | 4,
            # функция для обработки двухфакторной аутентификации
            auth_handler=VkAuth.auth_handler,
            captcha_handler=VkAuth.captcha_handler
        )
```

**Comment by DanyaSWorlD** [comment]
Скрипт крутится 24/7 на Ubuntu server 18.04 LTS под Python 3.7. Запуск через Systemd, соответственно руками с консоли ввести не особо получается, т.к. это скрвис. 

Раньше можно было запустить руками, получить vk_config и запустить сервис.

**Comment by omegastripes** [comment]
Попробуйте вот это решение https://github.com/python273/vk_api/issues/362#issuecomment-642396050

**Comment by DanyaSWorlD** [comment]
Хм, в таком случае теряется доступ
`vk_api.exceptions.ApiError: [15] Access denied: no access to call this method`
