### ISSUE TITLE
"Доработали формат запросов.. " при запуске

### ISSUE THREAD

**Issue by TheBogler** [python273/vk_api#486]
_Я запускаю бота. Хочу взять последний пост с группы, но бот не запускается и выдает данный текст_
Доработали формат запросов: теперь ключ доступа можно передавать в заголовке Authorization. Подробнее: vk.cc/ckcZmh.

### Окружение

vk_api: _11.9.9_

API: _-_

### Пример
```python
import vk_api

# Авторизуемся в ВКонтакте
vk_session = vk_api.VkApi(token='TKN',app_id=51636106)

# Получаем объект API
vk = vk_session.get_api()

s=vk.wall.get(domain='apiclub',count=2)
print(s)
```

**Comment by python273** [comment]
это текст поста https://vk.com/apiclub?w=wall-1_399821
