### ISSUE TITLE
Метод audio.get

### ISSUE THREAD

**Issue by skar404** [python273/vk_api#49]
Будет в будущем реализован метод `audio.get` миную блокировку от vk?

**Comment by LiberBear** [comment]
Лично я думаю, что нет, ведь это библиотека для работы с официальной API, в которой будут только те методы что позволит сам вк

**Comment by skar404** [comment]
Я бы не сказал что "Для авторизации в ВК используется симуляция действий пользователя" это является официальный способ работы с API VK, но речь не об этом.

**Comment by python273** [comment]
Ну если кто-то захочет реализовать, то будет

Делайте модулем вроде `vk_audio` (как сейчас `vk_tools` например)
