### ISSUE TITLE
vk_api.exceptions.AuthError: Unknown API auth error

### ISSUE THREAD

**Issue by Sdravstvuite** [python273/vk_api#497]
_Ошибка vk_api.exceptions.AuthError: Unknown API auth error при попытке авторизоваться. Пытался всеми способами, что смог найти, но ничего не помогает, хотя до этого, пользуясь вашей библиотекой все спокойно работало. Пробовать с помощью access_token не вариант, т.к. я хотел как раз с помощью вашей библиотеки получать его с разных аккаунтов._

### Окружение

vk_api: _11.9.9_

API: _5.81, но использую библиотеку только в работе с аккаунтом, а не сообществом._

### Пример

```python
from vk_api import vk_api
import dont_touch as dt
vku = vk_api.VkApi(login=dt.LOGIN, password=dt.PASS, app_id=dt.APP_ID)
vku.auth()
```

**Comment by python273** [comment]
версия в репозитории вроде работает
`python3 -m pip install --force-reinstall https://github.com/python273/vk_api/archive/master.zip`
