### ISSUE TITLE
К сожалению не работает tools.get_all для команды board.getComments

### ISSUE THREAD

**Issue by avostryakov** [python273/vk_api#52]
Пробую по примеру получить все сообщения в топике группы:

tools = vk_api.VkTools(vk_session)
comments = tools.get_all('board.getComments', 100, {'group_id': 122522055, 'topic_id': 28354335})

Внутри эта команда возвращает response пустой (поле items=None):
response = self.vk.method('execute', {'code': run_code})

Вообще аналогичная команда из API работает нормально:
response = vk.board.getComments(group_id=22522055, topic_id=28354335, count=100)

но так как скачивать много, то хотелось использовать пакетный режим по 25 команд

**Comment by python273** [comment]
> {'group_id': 122522055
> group_id=22522055

**Comment by avostryakov** [comment]
**Дополнение:**
Я копнул поглубже и там такая ошибка от API:
vk_api.vk_api.ApiError: [100] One of the parameters specified was missing or invalid: invalid tid

Эта же ошибка, если выполнять:
tools = vk_api.VkTools(vk_session)
comments = tools.get_all_slow('board.getComments', 100, {'group_id': 122522055, 'topic_id': 28354335})

И дело не в кавычках вокруг group_id, я уже напрямую js скрипт писал где оставил вызов только одного метода

**Comment by python273** [comment]
> 122522055
> 22522055

Падает потому что нет такого треда. Я добавил проверку items на None

**Comment by avostryakov** [comment]
Извини, затупил. Действительно :)

**Comment by avostryakov** [comment]
Можешь еще поправить в vk_tools.py, строка 137:

items = list(self.get_all_slow(method, max_count, values, key, limit))
на 
items = list(self.get_all_slow_iter(method, max_count, values, key, limit))

**Comment by avostryakov** [comment]
Извини, допиши еще в этот item: добавить в команду get_all параметр offset, чтобы он мог снаружи задаваться, внутри убрать offset=0. Иначе не возможно скачать больше первых 2500 сообщений.

**Comment by python273** [comment]
> Иначе не возможно скачать больше первых 2500 сообщений.

Почему?

**Comment by avostryakov** [comment]
Похоже опять туплю. Все можно. Единственно нельзя начать не сначала, но это
мне не нужно. Спасибо за либу, все работает!

Thank you!
Anatoly Vostryakov,
email to: a.vostrjakov@gmail.com

//////

2017-02-15 19:15 GMT+03:00 Kirill <notifications@github.com>:
