### ISSUE TITLE
Поддержка Django

### ISSUE THREAD

**Issue by GitBib** [python273/vk_api#54]
Планируете добавить поддержку Django?

**Comment by python273** [comment]
Что понимается под поддержкой Django?

**Comment by GitBib** [comment]
Хранение данных в модели и все что с этим связано.

**Comment by python273** [comment]
В смысле хранение токена и кук?

**Comment by GitBib** [comment]
Да, именно. Проект на Django перевел на сервер. И чет он не находит и не создает файл vk_config.json.

**Comment by Vanpitkinobi** [comment]
Там надо переопределить пару методов и научить vk_api хранить настройки в базе данных(ну это если по правильному), а может просто вы не в ту папку разместили, либо не все права доступа дали

**Comment by python273** [comment]
Встроенной поддержки сохранения конфига в джанго моделях не будет. Но сделал возможность передавать свой класс конфига (или функцию, возвращающюю инстанс): https://github.com/python273/vk_api/commit/ec7f08377a652a7ede6c3667e80c6c6805238aa9

```
config = {
    '+79012345678': {
        'remixsid': '123',
        'forapilogin': {'p': '456', 'l': '1'},
        'token': {'access_token': 'dead'}
    }
}

vk_session = vk_api.VkApi(
    login='python@vk.com',
    password='password',
    config=lambda login, filename: MemoryConfig(login, settings=config)
)
```

**Comment by GitBib** [comment]
Есть идея как сделать ещё проще. 
Когда у нас нету config:
```
vk_session = vk_api.VkApi(
    login='+79012345678',
    password='password',
    config_filename = None,
)
vk_session.auth()
config = vk_session.get_config()
```
А далее уже сохраняем config как нам удобно...

Когда у нас есть config:
```
config = {
        'remixsid': '123',
        'forapilogin': {'p': '456', 'l': '1'},
        'token': {'access_token': 'dead'}
}

vk_session = vk_api.VkApi(config=config)
)
vk_session.auth_config()
```
И так будет удобнее ^_^
Как ты считаешь?
