### ISSUE TITLE
How to use two-factor authorization?

### ISSUE THREAD

**Issue by dE1l** [python273/vk_api#60]
Error message 'No handler for two-factor authorization'.  How to use this handler?

**Comment by dE1l** [comment]
:param auth_handler: Функция для обработки двухфакторной аутентификации,
                              должна возвращать строку с кодом и
                              булевое значение, означающее, стоит ли запомнить
                              это устройство, для прохождения аутентификации.

Please, add this information to Wiki

**Comment by skar404** [comment]
Точно также как в примере с капчей, но еще нужно передать 2 параметр `remember_device`

А вот сам код получения code и remember_device: https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L213

To translate text you can use: https://translate.google.ru/

**Comment by skar404** [comment]
@dE1l  https://github.com/skar404/vk_api/blob/master/examples/auth_handler.py
