### ISSUE TITLE
Не проходит капча,

### ISSUE THREAD

**Issue by GitBib** [python273/vk_api#62]
Почему то после долго использование начинает такое показывать.
Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
['ApiError: [9] Flood control: too much captcha requests', '  File ".......", line 71, in invgroup', '  File "vk_api/vk_api.py", line 450, in method']

**Comment by GitBib** [comment]
И такой вопрос как обойти "Validation required: please open redirect_uri in browser"?

**Comment by python273** [comment]
> Flood control: too much captcha requests

¯\\\_(ツ)_/¯

> И такой вопрос как обойти "Validation required: please open redirect_uri in browser"?

В идеале получать токен там, где он используется. Сейчас автоматической обработки этой ошибки нет, но возможно получится использовать [VkApi.security_check](https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L236) с переданным `response`

**Comment by GitBib** [comment]
Есть возможность от этой ошибки: "Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)"?

**Comment by python273** [comment]
Ну это уже Sentry руаегся, что слишком много ошибок
