### ISSUE TITLE
Always SSL error when I try to auth

### ISSUE THREAD

**Issue by virus-on** [python273/vk_api#64]
> C:\Python27\python.exe C:/PycharmProjects/alb_poster/poster.py
> C:\Python27\lib\site-packages\vk_api\vk_api.py:137: DeprecationWarning: Please replace `VkApi.authorization` with `VkApi.auth` and `AuthorizationError` with `AuthError`
>   DeprecationWarning
> C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   SNIMissingWarning
> C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecurePlatformWarning
> Traceback (most recent call last):
>   File "C:/PycharmProjects/alb_poster/poster.py", line 56, in <module>
>     vk_session = vk_auth(LOGIN, PASSWORD)
>   File "C:/PycharmProjects/alb_poster/poster.py", line 20, in vk_auth
>     vk.authorization()
>   File "C:\Python27\lib\site-packages\vk_api\vk_api.py", line 140, in authorization
>     return self.auth(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\vk_api\vk_api.py", line 123, in auth
>     if not self.check_sid():
>   File "C:\Python27\lib\site-packages\vk_api\vk_api.py", line 286, in check_sid
>     response = self.http.get(url).json()
>   File "C:\Python27\lib\site-packages\requests\sessions.py", line 501, in get
>     return self.request('GET', url, **kwargs)
>   File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Python27\lib\site-packages\requests\adapters.py", line 497, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [Errno 1] _ssl.c:499: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> 
> Process finished with exit code 1

**Comment by virus-on** [comment]
Same using vk.auth

**Comment by python273** [comment]
> An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

**Comment by virus-on** [comment]
The time has come...
