### ISSUE TITLE
Django поддержка v2

### ISSUE THREAD

**Issue by GitBib** [python273/vk_api#76]
Продолжая тему #54 
Есть идея как сделать ещё проще.
Когда у нас нету config:

```
vk_session = vk_api.VkApi(
    login='+79012345678',
    password='password',
    config_filename = None,
)
vk_session.auth()
config = vk_session.get_config()
```
А далее уже сохраняем config как нам удобно...

Когда у нас есть config:

```
config = {
        'remixsid': '123',
        'forapilogin': {'p': '456', 'l': '1'},
        'token': {'access_token': 'dead'}
}

vk_session = vk_api.VkApi(config=config)
)
vk_session.auth_config()
```
И так будет удобнее ^_^
Как ты считаешь?

**Comment by python273** [comment]
Не, уже есть возможность свои бекенды для сохранения делать. И то что ты описал можно сделать с `MemoryConfig`

**Comment by GitBib** [comment]
Как я правильно понимаю нужно передавать обратно логин и пароль? Или можно в этом случаи обойтись только логином?

**Comment by python273** [comment]
https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L118

Сейчас проблема в том, что если пароль не передан, то данные из конфига не загрузятся. Нужно как-то исправить

**Comment by python273** [comment]
Реализовал тут:
https://github.com/python273/vk_api/pull/77
