### ISSUE TITLE
Установка access_token

### ISSUE THREAD

**Issue by ArmanPrestige** [python273/vk_api#78]
Есть ли на данный момент возможность использовать уже готовый токен? Что я имею в виду - у меня есть токен (который я получил, пройдя авторизацию, но не через модуль vk_api) и я не хочу выполнять повторно авторизацию, а хочу используя этот токен делать запросы с помощью модуля vk_api.

Что-то вроде

`api = vk_api(my_token_here)`

**Comment by python273** [comment]
https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L56
