### ISSUE TITLE
Каталог софта

### ISSUE THREAD

**Issue by python273** [python273/vk_api#88]
Есть идея сделать каталог софта в вики, написанного с использованием vk_api. Это могут быть скрипты полезные для обычных юзеров вроде:
- сохранение/отчистка фоток, сообщений, стены
- статистика/визуализация
- Machine Learning

так и для администраторов пабликов:

- боты
- автоматизация модерации
- автогенерируемый контент ([/r/Pics](https://vk.com/r_pics))

Требования:
- очевидно опенсурс на GitHub
- в README.md должно быть описание и инструкция по запуску
- более-менее чистый код (PEP8, Pythonic)

Скидывайте ваши репозитории с коротким описанием :full_moon_with_face:

**Comment by Fogapod** [comment]
https://github.com/Fogapod/VKBot/tree/0.1.0dev 🤔
Бот для адроида

В разработке

**Comment by python273** [comment]
¯\\\_(ツ)_/¯
