### ISSUE TITLE
JSONDecodeError на longpoll

### ISSUE THREAD

**Issue by graynk** [python273/vk_api#92]
При использовании longpoll (практически как в примере) он работает некоторое время без проблем, но через пару часов без трафика падает с ошибкой декодинга:
<class 'json.decoder.JSONDecodeError'>
Expecting value: line 1 column 1 (char 0)
Гугл показал только [что-то](https://stackoverflow.com/questions/16573332/jsondecodeerror-expecting-value-line-1-column-1-char-0#16575064) про библиотеку simplejson, которой у меня не установлено (поэтому requests ее использовать как бы и не может)

Код:
```
longpoll = VkLongPoll(vk_session)

for event in longpoll.listen():
        if event.type == VkEventType.MESSAGE_NEW and event.to_me:
            if event.attachments and 'fwd' in event.attachments:
                #do stuff
```

**Comment by python273** [comment]
Можно унаследоваться от VkLongPoll и добавить в listen попытки переотправить запрос
https://github.com/python273/vk_api/blob/master/vk_api/longpoll.py#L207-L213

Модуль не должен обрабатывать ошибки подключения, странные ответы серверов ВК и т.д.
