### ISSUE TITLE
Невозможно авторизоваться через токен.

### ISSUE THREAD

**Issue by semjef** [python273/vk_api#93]
Я авторизуюсь таким образом:

`vk_session = vk_api.VkApi(token=token)`
`vk_session.http.proxies = proxies`
`vk_session.auth(token_only=True)`

Как я понял, ошибка в том, что в функции auth всегда идёт проверка наличия логина и даже при token_only. И не очень понял как работает 
`
self.token = self.storage.setdefault(
                'token', {}
            ).setdefault(
                'app' + str(self.app_id), {}
            ).get('scope_' + str(self.scope))
`

скорее просто затирая этот токен.

**Comment by python273** [comment]
Вызывать auth при передаче токена не нужно
