### ISSUE TITLE
Unknown error. Please send bugreport: https://vk.com/python273

### ISSUE THREAD

**Issue by xkord** [python273/vk_api#94]
Возникает exception в данном куске кода.
```python
try:
    self.vk_session.auth()
except vk_api.AuthError as e:
    logger.critical('%s', e)
```
При этом продолжает корректно работать.

```python
vk_api.VkTools(self.vk_session)
tools = vk_api.VkTools(self.vk_session)
members = tools.get_all('groups.getMembers', 1000, {'group_id': self.group_id})
```

Возвращает список подписчиков корректно

**Comment by python273** [comment]
Какая версия модуля?

**Comment by xkord** [comment]
8.7

10 Окт 2017 г. 13:07 пользователь "Kirill" <notifications@github.com>
написал:

**Comment by python273** [comment]
Скорее всего нужно обновить модуль

**Comment by xkord** [comment]
Да, помогло, теперь выкинуло в captcha_handler. Все работает.

**Comment by xkord** [comment]
Спасибо.

**Comment by xkord** [comment]
Удивительно, что несмотря на то, что капчу не решил, продолжало работать.

**Comment by python273** [comment]
Вообще сейчас по дефолту проверяются куки от ВК и если запросы напрямую к ВК не делаются, то можно вызывать auth с `token_only=True` и так не будут проверяться куки

**Comment by xkord** [comment]
А на какие методы это распространяется? Я так понимаю, на все, которые не
являются активными(сделать репост, поставить лайк, отправить смс) и/или
требующими доступ к личной приватной информации (кого лайкал текущий
пользователь, список встреч текущего пользователя и т. д.)
То есть wall.get, friends.get, groups.get users.getFollowers, photos.get,
video.get, likes.getList и т. д. Можно использовать с token_only = True.

10 Окт 2017 г. 13:28 пользователь "Kirill" <notifications@github.com>
написал:

Вообще сейчас по дефолту проверяются куки от ВК и если запросы напрямую к
ВК не делаются, то можно вызывать auth с token_only=True и так не будут
проверяться куки

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/python273/vk_api/issues/94#issuecomment-335430365>, or mute
the thread

**Comment by python273** [comment]
Ну в модуле напрямую только VkAudio запросы делает

**Comment by xkord** [comment]
Понял, спасибо

10 Окт 2017 г. 15:33 пользователь "Kirill" <notifications@github.com>
написал:
