### ISSUE TITLE
Бан аккаунта

### ISSUE THREAD

**Issue by heyyyoyy** [python273/vk_api#97]
Использую авторизацию через логин, пароль. Вчера вечером просто массово забанили 4 акка, за лимиты не выходил, да и никаких рассылок или других вещей не делал. 
У кого ещё такая проблема? Есть мнение из за чего это произошло?

**Comment by SnoUweR** [comment]
Подтверждаю. Мой левый акк, на котором через vk_api по крону каждый час в закрытую группу постилась запись, тоже забанили вчера вечером.

**Comment by heyyyoyy** [comment]
тоже через крон гоняю, но интересно то, что дали бан аккаунтам , которые на этой библиотеке сидят, а на другой библиотеке аккаунт не забанили

**Comment by myusernamenone** [comment]
+1

**Comment by heyyyoyy** [comment]
app id вроде не участвует при авторизации через логин пароль

**Comment by myusernamenone** [comment]
@heyyyoyy участвует, он сразу добавляет пользователя в app с id 2895443 

https://github.com/python273/vk_api/blob/master/vk_api/vk_api.py#L155

**Comment by heyyyoyy** [comment]
не в этом месте, но да участвует) тогда надо будет со своим приложением попробовать

**Comment by myusernamenone** [comment]
@heyyyoyy да, но возможно проблема в этом.

**Comment by BlackMetalMusic** [comment]
А я думал, что дело в том, что я через Амстердам сидел.
Один акк, либу использую только для переписки из консоли.

**Comment by Norgat** [comment]
Обновилось приложение контакта на смартфоне. Думаю надо обновить appid в либе на новый или использовать свой.

**Comment by heyyyoyy** [comment]
@BlackMetalMusic кстати тоже амстердам, но до этого все норм было

**Comment by myusernamenone** [comment]
@BlackMetalMusic под бан попали из: Амстердама, России и Италии (что так-то не вижу связи со страной)
vk_api v9.1 и авторизация по login и password, не менял default app.

**Comment by heyyyoyy** [comment]
Ну если у кого подействует смена айдишника, то дайте знать,
а то сам только вечером смогу проверить

**Comment by python273** [comment]
Перезалил с другим app_id. Лучше меняйте стандартные `api_version, app_id, scope`

**Comment by heyyyoyy** [comment]
@python273 спасибо, надо проверить будет

**Comment by drdemons** [comment]
Таже проблема и в поддержки как раз сказали о том что рекомендуется использовать APP_ID своего приложения 

"Чтобы подобных недоразумений не возникало, при составлении запросов к API следует использовать API_ID своего приложения.


С лучшими пожеланиями,
Команда поддержки VK
"

**Comment by python273** [comment]
Напишите если баны будут после обновления на 9.1.1. Возможно стоит убрать стандартные `api_version, app_id, scope`

**Comment by heyyyoyy** [comment]
@python273 я сегодня со своим app id попробую
просто все работало месяца два стабильно, а тут разом всех накрыли 
и тех поддержка одному из забаненых аккаунтов ответила «а не пользовались ли вы какими нибудь приложениями?» 
может вк новые алгоритмы тестирует

**Comment by python273** [comment]
Ага, вообще я не уверен с чем это связано, с приложением или не очень разрешенным способом аутентификации. Подобные баны уже были за использование секрета android приложения с прямой аутентификацией

**Comment by heyyyoyy** [comment]
@python273 самое бы оптимальное это через токен и своё приложение, думаю за такое бан точно не дадут

**Comment by heyyyoyy** [comment]
две недели работает стабильно, всем большое спасибо за помощь
