### ISSUE TITLE
Пост на стену паблика (группы) с фото и текстом?

### ISSUE THREAD

**Issue by koddr** [python273/vk_api#99]
Приветствую.

Подскажите, как реализовать постинг фото с текстом на стену паблика (группы) от имени этого паблика (группы)? Возможно ли это вообще, средствами данной библиотеки?

Заранее спасибо.

**Comment by python273** [comment]
Пример загрузки изображений:
https://github.com/python273/vk_api/blob/master/examples/upload_photo.py

метод для постинга: https://vk.com/dev/wall.post

**Comment by koddr** [comment]
Спасибо, разобрался. Оказалось проще простого 👍
